- Makefile.am
> Also install hoqdep on `make install`

- contrib/HoTTBook.v
- theories/Basics/Overture.v
- theories/hit/Truncations.v
I was surprised that we didn't have this yet.  (Unless I missed it?)
> path-spaces of truncations (Theorem 7.3.12)

- theories/TruncType.v
- theories/Types/Nat.v
Define `<`, `<=`, `>`, `>=`, classify the path space of `nat`, and prove that `nat` is an hSet.
Also make a module for making `is_true` a coercion.  This is one way to start off some definitions of #654.
> Nat Properties

- Makefile_targets.mk
- theories/HoTT.v
- theories/Spaces/Nat.v
- theories/TruncType.v
- theories/Types/Bool.v
- theories/Types/Nat.v
We need to depend on [TruncType], so we can't live in [Types/].
Note: This is enough to build chain categories and the category of simplicial (h)sets and of semisimplicial (h)sets.
> Add a separate file of theorems about [nat]

- Makefile_targets.mk
- theories/categories.v
- theories/categories/Category/Morphisms.v
- theories/categories/Category/Notations.v
- theories/categories/Category/Sigma.v
- theories/categories/Category/Sigma/Core.v
- theories/categories/Category/Sigma/OnObjects.v
- theories/categories/Category/Sigma/Univalent.v
- theories/categories/Category/Subcategory/Full.v
- theories/categories/ChainCategory.v
- theories/categories/Notations.v
- theories/categories/SemiSimplicialSets.v
- theories/categories/SimplicialSets.v
- theories/categories/Utf8.v
This is on top of #667 and #669.
> Port the category of simplicial sets from catdb

- theories/Idempotents.v
We can now be caught up with Coq trunk, as of the time of this pull request!
> Bump trunk

- STYLE.md
- theories/Basics/Overture.v
This is necessary for getting #691 to work.
> Add a reversed version of [rapply]

- theories/EquivalenceVarieties.v
I wanted to see how many judmental laws @peterlefanulumsdaine's
definition of equivalence supported.   It turns out it doesn't support
as many as I had hoped.  Are there other definitions that support other
laws judgmentally?
> Add relational definition of equivalence

- git.md
> Adding small git tutorial

- Makefile_targets.mk
- theories/HoTT.v
- theories/hit/Coeq.v
- theories/hit/Flattening.v
- theories/hit/Join.v
- theories/hit/Pushout.v
And define pushouts in terms of them.  That way we could in theory apply the existing flattening lemma to pushouts directly.
> Move homotopy coequalizers into their own file

- Makefile_targets.mk
- theories/Basics/PathGroupoids.v
- theories/HoTT.v
- theories/Spaces/Int.v
- theories/Types/Forall.v
- theories/hit/Circle.v
- theories/hit/Coeq.v
* Functoriality and double recursion/induction for coequalizers
* Put `Int` in its own file
* Define the circle as a coequalizer and prove that it is 1-truncated and 0-connected
* The action of `S1` on a type family is iteration of an equivalence
> More about coequalizers and the circle

- theories/Modalities/ReflectiveSubuniverse.v
- theories/Tactics/RewriteModuloAssociativity.v
- theories/Tests.v
> Use rewrite@A more in O_coeq_cmp_eisretr

- theories/Fibrations.v
- theories/Modalities/Lex.v
- theories/Modalities/ReflectiveSubuniverse.v
Also including the 3x3 lemma for fibers (`hfiber_functor_hfiber`).
> If a reflective subuniverse preserves fibers, it is a modality (and lex)

- theories/Types/Prod.v
(Mainly to check that what I wrote in the book is correct)
> Add a coherence for associativity of path_prod_pp

- Makefile_targets.mk
- theories/Comodalities/CoreflectiveSubuniverse.v
- theories/HoTT.v
A sort of no-go theorem about what happens if we try to dualize modalities naively.
> A naive coreflective subuniverse is uniquely determined by an hprop

- theories/Basics/UniverseLevel.v
I wrote them out when trying to work around #754.  I didn't end up needing them, but I figure they might be useful eventually.
> Add some definitions for lifting equivalences

- autogen.sh
In lieu of a full fix for issue #780, this pull request adds a warning message suggesting a workaround in case the issue arises.
> Add warning message in autogen.sh, re #780

- _CoqProject
- theories/Basics/Notations.v
- theories/Basics/Trunc.v
- theories/HoTT.v
- theories/Pointed.v
- theories/Spectra/Coinductive.v
- theories/Spectra/Spectrum.v
- theories/hit/Truncations.v
I'm not planning to do any more of this in Coq right now, but I thought I might as well commit it so that anyone else who wants to build on it can.
> A bit of messing around with spectra

- etc/ci/install_coq_dot_deps.sh
Fix the travis build of graphviz
> Specify a version of graphviz that works on precise

- theories/Basics/Overture.v
This will let us work on things like #805 's
https://github.com/HoTT/HoTT/pull/805#issuecomment-224292617
> Override the [reflexivity] tactic

- theories/Spaces/Int.v
- theories/categories/NatCategory.v
- theories/hit/Circle.v
- theories/hit/Interval.v
Time diff: https://gist.github.com/SkySkimmer/a5ab2ec9d79474e75297feba87eb9b3a
> Put more types in Type0 (not Bool)

- contrib/HoTTBook.v
- theories/EquivalenceVarieties.v
- theories/Types/Universe.v
`HoTTBook.v` was way behind in coding up what has actually been implemented.  I started updating it some, but ran out of steam for now towards the end of chapter 6.
> Updating HoTTBook.v (through section 6.12)

- theories/HIT/Coeq.v
Proof that Coeq f g <~> Coeq g f.
> Symmetry for Coeq

- .travis.yml
- etc/ci/install_coq.sh
Now that I've fixed my ppa to have graphviz for trusty, this should bring #846 a little bit closer to being mergeable.  Assuming Travis is happy with this PR, I don't see any downsides of merging this now.
> Use Trusty on Travis

- .travis.yml
We weren't doing anything with them, and they add a lot of noise.
> Don't cat the per-line timing logs on travis

- coq/theories/Init/Datatypes.v
- coq/theories/Init/Logic.v
- coq/theories/Init/Specif.v
- coq/theories/Unicode/Utf8_core.v
- theories/Spaces/BAut.v
These two commits should be 8.6 compatible but are needed for 8.7 due to some bugfixes in Coq.
> Tweaks for 8.7, 8.6 compatible part

- theories/Types/Universe.v
There's already a Univalence hypothesis in the section.
> remove a duplicate hypothesis

- contrib/HoTTBookExercises.v
The full solution to 1.8 is very tedious, I've only completed part of it myself. 
I'm not sure if my solution properly reflects what 2.1 was asking, especially whether or not I was supposed to use functional extensionality.
> contrib/HoTTBookExercises: Solutions to several exercises

- theories/Classes/implementations/assume_rationals.v
- theories/HIT/V.v
- theories/Modalities/Lex.v
- theories/Types/Universe.v
This should be backwards compatible (with previous Coq ignoring the unknown option).
> Explicitate Existing Instance for Axioms (coq/coq#6183).

- theories/Classes/implementations/assume_rationals.v
> Forgot to Existing Instance Qdec Qjoin Qlattice.

- contrib/HoTTBookExercises.v
> contrib/exercises: solution to npaths

- _CoqProject
- theories/Spaces/Card.v
- theories/Types/Empty.v
Several operations and lemmas from Chapter 10 of the HoTT book.
I also wanted to update the `HoTTBook.v` file, but it looks like it's a bit out of sync with the book, as processing it as it is currently gives me an error:
```
$ cat ../book/*.aux | etc/Book.py contrib/HoTTBook.v
Reading content of *.aux files from standard input...
Statistics:
3661 lines of input
2677 lines skipped
430 labels found
0 labels confused me
Reading contrib/HoTTBook.v
***** FATAL ERROR: entry defn:set contanins something that looks like a marker, please fix this first.
```
But overall this is a pretty straightforward implementation, but I am not 100% sure about the changes to the `Empty.v` that I made.
> Implement some theory of cardinal numbers

- coq/theories/Init/Peano.v
- coq/theories/Init/Specif.v
This removes the reliance on compatibility support for old versions.
> Fixes for coq/coq#6791.

- _CoqProject
- theories/Basics/Decidable.v
- theories/Basics/Equivalences.v
- theories/Classes/implementations/binary_naturals.v
- theories/Classes/implementations/peano_naturals.v
I have implemented a variant on binary naturals, that I learned from Martín Escardó and Cory Knapp, given directly as one inductively defined type.
```coq
Inductive binnat : Type :=
| bzero   :           binnat  (* zero *)
| double1 : binnat -> binnat  (* 2n+1 *)
| double2 : binnat -> binnat. (* 2n+2 *)
```
This allows doing computations with larger naturals than the unary presentation.
I have placed the code in `Classes/implementations`. Feedback is very welcome as I don't consider myself a Coq expert at all.
> Binary naturals

- etc/ci/install_coq_dot_deps.sh
As per #883, we are tracking Coq master with our master branch.  I've updated coq-dpdgraph to the latest commit on its coq-trunk branch, and updated coq-scripts to its latest commit (because why not?).  This will
hopefully fix the issues we've been having recently with graphs on Travis, though I haven't looked into them much.  (I'm a bit worried that one of the failures to build seems to be a result of cabal not being able to resolve dependencies for the packages we're looking for...)
> Update coq submodule

- theories/Classes/interfaces/canonical_names.v
- theories/Classes/tactics/ring_pol.v
- theories/Classes/theory/additional_operations.v
- theories/Types/Bool.v
Time diff: https://gist.github.com/SkySkimmer/55d3835550db6722137af3940a181bd7
This time everything just went through.
> Put more types in Type0

- theories/Types/Prod.v
A simple addition. I didn't find anything for `path_prod` and `inverse`, and I had to use this lemma in some other formalisation.
> Add `path_prod_V` (from Section 2.6)

- coq/theories/Init/Datatypes.v
- coq/theories/Init/Notations.v
- coq/theories/Unicode/Utf8_core.v
- theories/Basics/Utf8.v
- theories/Classes/implementations/natpair_integers.v
- theories/Classes/implementations/peano_naturals.v
- theories/Classes/interfaces/canonical_names.v
- theories/Classes/interfaces/integers.v
- theories/Classes/interfaces/naturals.v
- theories/Classes/interfaces/orders.v
- theories/Classes/orders/lattices.v
- theories/Classes/orders/nat_int.v
- theories/Classes/orders/naturals.v
- theories/Classes/orders/orders.v
- theories/Classes/orders/semirings.v
- theories/Classes/orders/sum.v
- theories/Classes/tactics/ring_quote.v
- theories/Classes/theory/additional_operations.v
- theories/Classes/theory/int_abs.v
- theories/Classes/theory/naturals.v
- theories/Classes/theory/rationals.v
- theories/HIT/Truncations.v
- theories/Utf8.v
See discussion at the (largely unrelated) issue #934 .
> Make \/ mean hor, not sum.  Use |_| if sum is intended.

- theories/HProp.v
Do we have this already anywhere?
> A map is an embedding as soon as its ap's have sections.

- theories/Basics/Overture.v
- theories/Categories/NatCategory.v
- theories/Categories/Pseudofunctor/FromFunctor.v
- theories/Classes/interfaces/abstract_algebra.v
- theories/Classes/interfaces/canonical_names.v
- theories/Classes/interfaces/orders.v
As talked about in #991.
However now we cannot build. First problem is in Sum.v and is not the last.
> changed implicit hints to reference core

- _CoqProject
- theories/Classes/implementations/family_prod.v
- theories/Classes/implementations/field_of_fractions.v
- theories/Classes/implementations/list.v
- theories/Classes/implementations/natpair_integers.v
- theories/Classes/implementations/ne_list.v
- theories/Classes/interfaces/canonical_names.v
This is the first of a series of commits implementing parts of universal algebra in HoTT. The complete code can be found at https://github.com/andreaslyn/hott-classes. It is based on math classes, https://github.com/coq-community/math-classes.
This commits contains the preliminary definitions. Following commits will contain definitions and results about: algebra, homomorphism, isomorphism, subalgebra, product algebra, the three isomorphism theorems.
> Universal algebra: preliminary definitions.

- _CoqProject
- theories/Classes/interfaces/ua_algebra.v
This is the second universal algebra pull request. The first one: https://github.com/HoTT/HoTT/pull/1007
> Universal algebra: Definition of algebra

- coq/theories/Init/Tactics.v
> Declare hint databases in the prelude

- _CoqProject
- theories/Classes/implementations/ne_list.v
- theories/Classes/interfaces/ua_algebra.v
- theories/Classes/interfaces/ua_congruence.v
- theories/Classes/interfaces/ua_setalgebra.v
- theories/Classes/theory/ua_homomorphism.v
- theories/Classes/theory/ua_prod_algebra.v
- theories/Classes/theory/ua_quotient_algebra.v
- theories/Classes/theory/ua_subalgebra.v
This will be used to develop a univalent category of algebras and homomorphisms for a signature.
> New lemmas and some cleanup.

- _CoqProject
- theories/Cubical.v
- theories/Cubical/Cube.v
- theories/Cubical/DPath.v
- theories/Cubical/Square.v
- theories/HoTT.v
In partial response to #978, here are some lemmas about squares and cubes that I started working on a while ago.  They're very incomplete because I had a specific purpose in mind at the time rather than setting out to write a complete library for squares and cubes, but I did try to choose relatively predictable names for the lemmas and their arguments at least.
If this seems to be a worthwhile starting point, we could merge it and then others could work on improving and adding to it (i don't have the time to work on it further myself right now) -- that would probably be easier than trying to develop it it a branch or a fork and only merging it when it looks more complete.  It compiles and doesn't affect any existing code (so using it is completely optional).
> some stubby cubical stuff

- theories/Spaces/Finite.v
as discussed in #1031. This makes working with `Fin n` for small values of `n` a bit easier.
> added finite induction tactic

- theories/Basics/Overture.v
> fixed printing of equivalences, closes #1000

- _CoqProject
- theories/Classes/theory/ua_first_isomorphism.v
- theories/Classes/theory/ua_prod_algebra.v
- theories/Classes/theory/ua_second_isomorphism.v
- theories/Classes/theory/ua_subalgebra.v
There is also a specialization of the first isomorphism theorem and some cleanup.
> Universal algebra: the second isomorphism theorem

- theories/Categories/ExponentialLaws/Law2/Law.v
See https://github.com/coq/coq/issues/10480
This is in preparation for a fix (https://github.com/coq/coq/pull/10476), but should be backward compatible (to be tested).
> Avoid relying on `Export` bug

- theories/Basics/Overture.v
> changed Sect to unfold after two arguments, close #1050

- _CoqProject
- theories/HIT/Spheres.v
- theories/Homotopy/HomotopyGroup.v
- theories/Homotopy/Pi1S1.v
- theories/Pointed.v
I have rewritten HomotopyGroup.v and added some lemmas such as the distribution over products. I have added PiS1.v in /Homotopy/ too. In order to do this I have added a few lemmas to Pointed.v.
I am thinking about possibly breaking up Pointed.v into smaller files which will easier to navigate and work with. (They will still be indexed by Pointed.v).
Once the Torus PR is pulled, I will also add a computation of Pi1 of the Torus later. I currently also have a half finished file for PinSn lying around which I may finish soon.
> improved HomotopyGroup.v and added Pi1S1

- theories/Types/Sum.v
this was highlighted in #1054 . This should save around 6s in compilation.
> optimised Types/Sum.v

- _CoqProject
This was meant to be part of the Torus PR but since that one is making travis cry I will add this change separately whilst I work out what is wrong with the other.
I haven't bothered giving sections to subfolders but those are typically easier to navigate than the rest.
> organising _CoqProject

- theories/HIT/Join.v
- theories/HIT/Pushout.v
- theories/HIT/epi.v
- theories/Modalities/Closed.v
I also took the opportunity to make `pushout_ind` agree with `pushout_rec` about which arguments are implicit.
> pushouts commute with sigmas

- INSTALL.md
Once Travis passes and this is merged, I will tag `V8.10`, make a release, and update opam.
> Update submodule to Coq V8.10.0

- theories/Basics/Overture.v
- theories/Classes/implementations/family_prod.v
- theories/Classes/interfaces/canonical_names.v
- theories/Classes/interfaces/ua_congruence.v
- theories/Classes/orders/orders.v
- theories/Classes/theory/premetric.v
- theories/Classes/theory/ua_first_isomorphism.v
- theories/Classes/theory/ua_quotient_algebra.v
- theories/Classes/theory/ua_second_isomorphism.v
- theories/Classes/theory/ua_third_isomorphism.v
- theories/HIT/quotient.v
- theories/Spaces/Finite.v
Changed relation to adhere to conventions set out in #120.
> changed relation to Relation

- _CoqProject
Somehow this crept in in the last PR but because travis was complaining about other things I failed to notice it.
> removed redundent line from _CoqProject

- contrib/HoTTBookExercises.v
- theories/Algebra/AbelianGroup.v
- theories/Basics/Contractible.v
- theories/Basics/Overture.v
- theories/Basics/Trunc.v
- theories/Categories/Functor/Prod/Universal.v
- theories/Categories/InitialTerminalCategory/Functors.v
- theories/Categories/InitialTerminalCategory/NaturalTransformations.v
- theories/HProp.v
- theories/Homotopy/BlakersMassey.v
- theories/Modalities/Open.v
- theories/Pointed/Loops.v
- theories/PropResizing/Nat.v
- theories/Types/Empty.v
- theories/Types/Unit.v
> renamed BuildContr to Build_Contr

- theories/Algebra/AbelianGroup.v
- theories/Algebra/Congruence.v
- theories/Algebra/Group.v
- theories/Algebra/QuotientGroup.v
- theories/Algebra/Subgroup.v
- theories/Classes/interfaces/abstract_algebra.v
- theories/Classes/interfaces/canonical_names.v
- theories/Classes/theory/groups.v
- theories/Classes/theory/lattices.v
My suggestion at https://github.com/HoTT/HoTT/issues/976#issuecomment-561823453 seems to work, except for the notation `(.* x)`.  But I'm not a real big fan of that notation anyway, so I don't mind using lambdas instead.
> Replace & for sg_op with scopes for * and +, close #976

- _CoqProject
- theories/Homotopy/HSpace.v
I have added the definition of H-space and the equivalences induced when the space is 0-connected.
This closes #984.
> H-spaces, closes #984

- theories/Homotopy/Join.v
I have added an induction principle for Join including it's computation rule. This make it easier to work the the join.
> Induction principle for Join

- theories/Homotopy/HSpace.v
> fixed HSpace after generalizable variables removed

- _CoqProject
- theories/Homotopy/EMSpace.v
This relies on #1148. See the last commit here.
I couldn't in the end make the argument slicker as suggested in #1086 since I got really confused what was going on. Instead I have opted to put all the important lemmas in EMSpace.v. Currently it works and no doubt there is a nicer way to do this argument but for what I want to do with it it is fine.
> Eilenberg-MacLane spaces

- theories/Algebra/QuotientGroup.v
> removed univalence from quotient group

- Makefile.am
- configure.ac
- etc/ci/generate_and_push_doc.sh
We now display a bit more timing info, including on proviola builds
> Better timing stats

- _CoqProject
- theories/Cubical.v
- theories/Cubical/DPathCube.v
- theories/Cubical/DPathSquare.v
- theories/Cubical/PathCube.v
- theories/Cubical/PathSquare.v
- theories/Homotopy/ClassifyingSpace.v
- theories/Homotopy/Join.v
- theories/Limits/Pullback.v
- theories/Spaces/Torus/Torus.v
- theories/Spaces/Torus/TorusEquivCircles.v
Renamed Square and Cube to PathSquare and PathCube respectively. We have a library of squares in development in the wildcat branch currently so this is in preparation for that. This closes mikeshulman/HoTT#38.
> renamed cubical library

- INSTALL.md
As discussed in #1172. closes #1172
> updated windows install instructions

- theories/Pointed/pTrunc.v
Here are some results about pointed truncations that I had lying around. These proofs could probably be simpler in some palces. I'm not sure if univalence can be removed either.
> results on pTr

- theories/Categories/Category/Sigma/Univalent.v
Reduces the file's type checking time from 17s to < 3s on my system.
> Speed up typeclass search in .../Category/Sigma/Univalent.v

- theories/Modalities/ReflectiveSubuniverse.v
> fixed #817

- theories/Basics/Overture.v
- theories/Basics/PathGroupoids.v
- theories/Classes/implementations/field_of_fractions.v
- theories/Classes/implementations/natpair_integers.v
- theories/Classes/implementations/peano_naturals.v
- theories/Classes/isomorphisms/rings.v
- theories/Classes/tactics/ring_pol.v
- theories/Classes/tactics/ring_quote.v
- theories/Classes/theory/rings.v
- theories/Cubical/PathCube.v
- theories/Cubical/PathSquare.v
- theories/Spaces/Torus/TorusEquivCircles.v
- theories/Types/Prod.v
> replaced ap2 with ap011 and removed ap2

- theories/Algebra/AbelianGroup.v
@Alizter I finally had a chance to look at what you did.  Great work!
> AbelianGroup.v: simplify some proofs and avoid Univalence; fix typos

- theories/Modalities/ReflectiveSubuniverse.v
> removed funext from proof of O_inverts_functor_sigma_to_SepO

- theories/Extensions.v
- theories/Modalities/ReflectiveSubuniverse.v
Closes #1233 
Thanks for the help Mike!
> Adjust things so that O_rec is inverse to equiv_o_to_O

- theories/Extensions.v
- theories/Modalities/ReflectiveSubuniverse.v
Adds a converse to `O_inverts_by_yoneda`, and a converse to the converse (in a different sense).
> Add Lemma 1.23 from RSS to ReflectiveSubuniverses.v

- theories/Modalities/Descent.v
- theories/Modalities/Modality.v
- theories/Modalities/ReflectiveSubuniverse.v
- theories/Modalities/Separated.v
There are still some very slow parts in ReflectiveSubuniverses.v, but fixing them will require more thought that I'll leave for someone else to tackle in another PR.
> Shave about 2s off of four Modality/ files

- theories/Limits/Equalizer.v
Another small thing that I didn't end up needing, but that we may as well add.
> Add functor_equalizer

- theories/Modalities/ReflectiveSubuniverse.v
This version is handy for some WIP.
> Add equiv_o_conn_map

- theories/Cubical/DPath.v
- theories/Cubical/DPathCube.v
- theories/Cubical/DPathSquare.v
- theories/Cubical/PathCube.v
- theories/Cubical/PathSquare.v
- theories/Homotopy/Suspension.v
- theories/Modalities/Separated.v
- theories/Spaces/Torus/TorusEquivCircles.v
I have bundled up the equivalences in the cubical library. As discussed in #1217. So this closes #1217.
> bundled up equivalences in cubical library

- theories/Spaces/Finite.v
> Modulo map for Fin

- .github/workflows/ci.yml
I've updated the CI script to stop it from cancelling other jobs if one of them fails.
> stopped jobs from getting cancelled

- theories/Types/Equiv.v
- theories/Types/Sigma.v
> Shorter and cleaner proof of hprop_isequiv

- theories/Basics/Equivalences.v
- theories/Types/Forall.v
This lemma isn't actually used anywhere else in the library, so it's unclear how important it is to have at all.
> Simpler definition of equiv_functor_forall_covariant

- theories/Algebra/AbelianGroup.v
I've removed some unnecessary Funext that was being used here. Unfortunately removing a section has caused some diff noise.
While this PR is open, I wouldn't mind adding some speed ups. I've tried to find some but it just seems to be slow. If anyone has any ideas how we can speed this up I am listening.
> removed unnecessary funext from AbelianGroup.v

- theories/Algebra/AbelianGroup.v
> Remove funext entirely from AbelianGroup by using wild categories

- theories/Limits/Pullback.v
Our fancy new technology enables an easy proof of the 3x3 lemma for pullbacks.
> The 3x3 lemma for pullbacks, close #1174

- INSTALL.md
Once this is merged, I will make a release. See #1291
> Update submodule to Coq V8.11.0

- theories/Cubical/DPath.v
- theories/Cubical/DPathCube.v
- theories/Cubical/DPathSquare.v
- theories/Cubical/PathCube.v
- theories/Cubical/PathSquare.v
This closes #1290. I also did some general clean up here and there while I was at it. The proofs in PathCube are pretty slow but I couldn't work out how to speed them up.
> Clean up in Cubical library

- .github/workflows/ci.yml
As per
https://bugs.launchpad.net/ubuntu/+source/npm/+bug/1809828 and
https://askubuntu.com/a/1092849/223605.  Closes #1318
I haven't tested this, but let's see if it works
> Hopefully fix npm issue

- etc/ci/install_coq.sh
As per https://github.com/coq/coq/issues/12115#issuecomment-616498778
Hopefully fixes the CI issue on master.
Closes coq/coq#12115
> make coqocaml rather than coqlight

- Makefile.am
- coq/theories/Init/Hexadecimal.v
- coq/theories/Init/Nat.v
- coq/theories/Init/Numeral.v
- coq/theories/Init/Prelude.v
> WIP: [coq] Adapt to coq/coq#11948

- contrib/HoTTBookExercises.v
~~Not sure if this provides any insight.~~
> [Exercise 1.11] Can be solved easily with some insight

- contrib/HoTTBookExercises.v
~~Seems simple enough, but I wonder if I've addressed the question in the book correctly.~~
Edit: I think I've solved it correctly this time.
> [Exercise 1.5] Completed with lots of help from @herbelin

- contrib/HoTTBookExercises.v
> [Exercise 1.5] Don't clobber global names {sum, ind}

- theories/Classes/implementations/pointwise.v
I didn't check but this should be backwards compatible.
> Fix w.r.t. coq/coq#12532.

- coq/theories/Init/Notations.v
- theories/Analysis/Locator.v
- theories/Basics/Notations.v
- theories/Basics/Utf8.v
- theories/Classes/implementations/field_of_fractions.v
- theories/Classes/implementations/peano_naturals.v
- theories/Classes/interfaces/abstract_algebra.v
- theories/Classes/interfaces/orders.v
- theories/Classes/orders/lattices.v
- theories/Classes/orders/naturals.v
- theories/Classes/orders/orders.v
- theories/Classes/orders/semirings.v
- theories/Classes/theory/additional_operations.v
- theories/Classes/theory/naturals.v
- theories/Classes/theory/premetric.v
- theories/Types/Bool.v
A proposal addressing #1335.  Marking as draft so it doesn’t get merged until we’ve discussed whether further tweaks are desirable.
> Changed ‘~’ and ‘~~’ to bind tightly (level 35)

- _CoqProject
- theories/Homotopy/SuccessorStructure.v
Here is a definition of "successor structure", i.e. type with an endofunction. This is a useful notion to consider when thinking about exact sequences, spectra and spectral sequences. This was originally written by @fpvandoorn.
> successor structures

- contrib/HoTTBookExercises.v
The third part seems to be somewhat tricky.
> [Exercise 1.12] All three parts are relatively straightforward

- theories/Modalities/ReflectiveSubuniverse.v
> Removed universe annotations in ReflectiveSubuniverse.v for coq #3811

- theories/Algebra/Groups/FreeGroup/ListQuotient.v
There was an unfinished proof in #1365 that I just noticed. Silly me. Luckily it isn't anything big.
> finished unfinished proof of words_rec_coh

- theories/Basics/Overture.v
- theories/Tests.v
Register a few things so that the discriminate tactic starts working.
Co-authored-by: Hugo Herbelin <Hugo.Herbelin@inria.fr>
> [Overture] Get discriminate working

- theories/Algebra/ooGroup.v
- theories/WildCat/Paths.v
- theories/WildCat/Type.v
- theories/WildCat/Yoneda.v
> remove extra exports in wildcat library

- .github/workflows/ci.yml
Hopefully this fixes our CI issues
> added libzarith-ocaml-dev dependency to ci

- README.md
Clicking the github actions badge should now take users to the latest CI builds on master.
Closes #1389
> Added link to actions page for github actions branch

- .github/workflows/ci.yml
> Update version of setup-python

- INSTALL.md
I had to do this before I could compile our currently pinned Coq.
> mention in INSTALL that you need to install zarith from opam

- INSTALL.md
On top of #1409 (as discussed there).
> separate out gtk dependencies in copy-paste lines in INSTALL

- _CoqProject
- theories/Algebra/Universal/Algebra.v
- theories/Algebra/Universal/Homomorphism.v
This is the first PR developing infinitary universal algebra. The next PR will contain a predicate `IsEquational` for algebras with equations.
Later PRs will define (univalent) category of algebras and construct direct product, subalgebra and quotient. There is moreover a proof which shows that constructively the quotient map cannot generally be surjective.
I think we should remove or deprecate the old (finitary) universal algebra when the infinitary has been merged, since the infinitary universal algebra supersedes the finitary.
> Algebra, homomorphism and isomorphism

- theories/Algebra/Groups/Group.v
We create a new hint database for basic group lemmas and introduce a new tactic `grp_auto` that uses them.
An example of where this is useful is the construction of the direct product. If you find any other places this could be used let me know!
We can of course make this tactic much smarter with rewriting etc. but I am unsure how useful this will really be. It might also be worth noting that if a group has a decidable word problem, then we ought to have a decision procedure to solve equalises for us. Again, unsure if this is worth it.
This comes from #1436.
> auto for groups

- contrib/HoTTBookExercises.v
I never managed to write down the full induction principle for the torus when I formalized it. I am now fairly certain that using the Cubical library was not so helpful here. In the future, I hope to write some lemmas about higher dependent paths which should make stating the induction principle much nicer.
For now though, I've added some of the exercises.
> added Torus exercises

- _CoqProject
This will make my life nicer while we wait for a real fix to https://github.com/HoTT/HoTT/issues/1454
> pass `-native-compiler ondemand`

- theories/Basics/Overture.v
I'll do some timing checks later
> mark eisadj as globally Opaque

- Makefile.coq.local
> add TIMING=1 by default to silence noise

- _CoqProject
> disabled -native-compiler ondemand option due to noise

- theories/Basics/Equivalences.v
- theories/Spaces/Spheres.v
- theories/Truncations/Connectedness.v
> Miscellaneous cleanups

- theories/Basics/Equivalences.v
Replace `first` with `+` in `build_record` and `build_record_with_evars` so that `make_equiv` and `make_equiv_contr_basedpaths` do more backtracking in their search.  Also factor out two `cbn`s, so they aren't undone and redone in some cases.
I checked the timing, and it makes no significant difference for the building of the library.
Closes #1506.
> Add more backtracking to make_equiv and make_equiv_contr_basedpaths

- theories/Pointed/Loops.v
- theories/WildCat/Core.v
- theories/WildCat/FunctorCat.v
- theories/WildCat/NatTrans.v
- theories/WildCat/Opposite.v
- theories/WildCat/Yoneda.v
Here are some lemmas about nat equivs that were developed in @jdchristensen's Hurewicz project. I believe they are useful to have in the main library now so I am creating this PR.
> Some lemmas about nat equivs

- theories/HFiber.v
- theories/Homotopy/WhiteheadsPrinciple.v
- theories/Modalities/Modality.v
- theories/Truncations/Connectedness.v
Another round of minor cleanups that I've accumulated over a few weeks.  Each commit is independent.
> Minor cleanups

- etc/generate_coqproject.sh
> stop using .git to find .v files and instead use find

- theories/HoTT.v
> Add Sets and Bouquet to HoTT.v

- theories/Colimits/Colimit.v
> Simplified Coeq definition of Colimit

- theories/Homotopy/ClassifyingSpace.v
- theories/Homotopy/EMSpace.v
- theories/Homotopy/HomotopyGroup.v
- theories/Modalities/ReflectiveSubuniverse.v
- theories/Pointed/Loops.v
Adds a few small results about EM spaces, and cleans up a few proofs.
> A few minor things about Eilenberg-Mac Lane spaces

- theories/Colimits/Pushout.v
- theories/Types/Sum.v
<s> Depends on #1577 </s>
Sum functors and then pushout functors preserve homotopies
> Pushout 2 functor

- theories/Categories.v
For some files I am planning to add later, we get a naming clash. Therefore I am fully qualifying the imports in this file.
> Fully qualified names in Categories.v

- theories/PathAny.v
Should be backwards compatible.
> Adapt w.r.t. coq/coq#15198.

- theories/Homotopy/EncodeDecode.v
- theories/PathAny.v
I had this laying around, probably wouldn't hurt to add to the library.
Technically we could refactor a few proofs in the library to go through this, but I am not sure we would gain much.
> encode-decode lemmas

- .github/workflows/ci.yml
- hott.opam
> update to coq 8.15

- .github/workflows/ci.yml
Hopefully this should allow the CI to finish. I just noticed also that we haven't been deploying doc for a while so that should be fixed.
> Make dpdgraph job more lenient and increase stacksize.

- theories/Basics/Overture.v
- theories/Basics/Tactics.v
- theories/Basics/UniverseLevel.v
- theories/Categories/Category/Morphisms.v
- theories/Categories/Functor/Attributes.v
- theories/Classes/interfaces/abstract_algebra.v
- theories/Classes/interfaces/canonical_names.v
- theories/Classes/interfaces/integers.v
- theories/Classes/interfaces/naturals.v
- theories/Classes/interfaces/orders.v
- theories/Classes/interfaces/rationals.v
- theories/Classes/theory/premetric.v
- theories/Diagrams/DDiagram.v
- theories/Homotopy/CayleyDickson.v
- theories/Homotopy/HSpace.v
- theories/Sets/Ordinals.v
- theories/WildCat/Core.v
- theories/WildCat/Opposite.v
We clean up various warnings that will be introduced in 8.16.
> Misc warning cleanups

- theories/Basics/Utf8.v
- theories/Categories/Monoidal/MonoidalCategory.v
We define a monoidal category.
> Monoidal cat

- contrib/HoTTBookExercises.v
Using intuitionistic De Morgan's law.
> [Exercise 1.13] Solved double negation of excluded middle

- contrib/HoTTBook.v
- theories/Spaces/Circle.v
There was a question about this at HoTT/book#1123, and I didn't see it in the library, so I formalized it directly.
> universal property of the circle (Lemma 6.2.9 in the Book)

- .github/workflows/ci.yml
> [CI] get rid of redundent steps

- theories/Categories/LaxComma/CoreLaws.v
It can be rather noisy and it is not like we actually pay attention to it today anyway.
> remove Time from CoreLaws.v

- theories/Algebra/AbGroups/AbSES/BaerSum.v
- theories/Basics/Notations.v
- theories/WildCat/Bifunctor.v
- theories/WildCat/Monoidal.v
- theories/WildCat/SetoidRewrite.v
> Monoidal wildcat

- theories/Modalities/Localization.v
- theories/Modalities/ReflectiveSubuniverse.v
We had some compat code leftover.
> remove 8.15 compat

- STYLE.md
- theories/Classes/implementations/natpair_integers.v
- theories/Spaces/No/Core.v
- theories/Spaces/No/Negation.v
Attempting https://github.com/HoTT/Coq-HoTT/pull/1006 again
> Fix unfolding of private recursors

- .github/workflows/ci.yml
- coq-hott.opam
- dune-project
Bumping minimal version to 8.17.
> prepare for 8.17

- theories/Algebra/Groups/Lagrange.v
- theories/Algebra/Groups/QuotientGroup.v
- theories/Algebra/Rings/Ideal.v
- theories/Analysis/Locator.v
- theories/Homotopy/SuccessorStructure.v
> make a few Spaces.Finite Require statements more specific

- etc/emacs/run-etags.sh
- theories/Basics/Contractible.v
- theories/EquivGroupoids.v
- theories/Homotopy/Join/Core.v
- theories/Homotopy/Join/JoinSusp.v
- theories/WildCat/TwoOneCat.v
Just a few cleanups I have found as I work on other things.
> Miscellaneous cleanup

- theories/Modalities/Lex.v
- theories/Modalities/Localization.v
- theories/Modalities/ReflectiveSubuniverse.v
Remove a workaround for Coq <= 8.11.
> ReflectiveSubuniverse: workaround no longer needed

- etc/Book.py
> Typo Fix in Book.py

- theories/Basics/PathGroupoids.v
- theories/Homotopy/Join/Core.v
- theories/Spaces/TwoSphere.v
The third commit is almost entirely white space.
> A few very minor cleanups

- etc/coqcstriprequires.py
- theories/Algebra/Groups/Group.v
- theories/Homotopy/HSpace/Core.v
- theories/Homotopy/HSpace/Moduli.v
- theories/Types/Unit.v
- theories/WildCat/Equiv.v
Also improves the comments in the coqcstriprequires.py script.
> Remove a few "Require" commands that aren't needed

- test/Classes/ring_tac.v
- test/WildCat/Opposite.v
- theories/WildCat/Opposite.v
- theories/dune
We had a few tests scattered around the library that I've moved into the test folder.
> cleanup tests scattered throughout library

- theories/WildCat/Products.v
- theories/WildCat/ZeroGroupoid.v
This gives a slightly simpler definition of `cate_prod_corec_inv`.
> add prod_0gpd_corec

- theories/Homotopy/BlakersMassey.v
This PR slightly speeds up one line near the end of the file.
It turns out that the line that was labelled "slow" is instantaneous.  I don't know what fixed that, but it's not this PR.  In fact, the whole file only takes 0.7s to process, and no line is slower than 0.1s.
> BlakersMassey: slight speedup

- theories/WildCat/Products.v
This PR just adds the diagonal map to a binary product in any wild category with that product.
> diagonal map into binary product

- theories/WildCat/Coproducts.v
- theories/WildCat/Opposite.v
<s>This is a formal dual of the proofs for the product. I haven't been able to get the proofs to follow definitionally from the functoriality of the products however. Opping in the presence of functors is something I find very confusing so to be more practical I just reproved it. </s>
Using lemmas about functors on opposite categories we can derive the functionality of coproducts using the functoriality of products.
> functoriality of binary coproducts

- theories/Basics/PathGroupoids.v
- theories/Types/Paths.v
We've probably worked with this in disguise a few times. Having a name and lemmas about it will make reasoning much easier.
Afterwards I'll submit a PR and show how it is useful for deriving functoriality results for GraphQuotient.
> transport011: transport over 2 1-paths and lemmas about them

- theories/Basics/Notations.v
- theories/Colimits/Coeq.v
- theories/Colimits/Colimit_Sigma.v
- theories/Colimits/GraphQuotient.v
- theories/Colimits/Pushout.v
- theories/Cubical/DPath.v
- theories/Cubical/DPathSquare.v
- theories/Cubical/PathSquare.v
- theories/WildCat/Opposite.v
Minor changes.  The commit messages give a good summary.
The commits are independent, but don't interfere, so can be read together or apart.
> Miscellaneous things related to recent changes

- .github/workflows/ci.yml
- coq-hott.opam
- dune-project
- flake.nix
- theories/Basics/Overture.v
This is a draft for now as we need to decide whether or not to do this yet.
> [8.18] bump minimal version to Coq 8.18

- contrib/HoTTBookExercises.v
- theories/Classes/implementations/peano_naturals.v
Renamed some functions from Exercise 1.8 to avoid collisions
> [Chapter 1 Exercise] Solved

- theories/Basics/PathGroupoids.v
- theories/WildCat/Paths.v
> Add missing coherences from WildCat/Paths.v to PathGroupoids.v

- flake.lock
> flake update

- theories/WildCat/Opposite.v
- theories/WildCat/PointedCat.v
The opposite category of a pointed category is again pointed.
> Opposite pointed category

- contrib/HoTTBookExercises.v
- theories/Types/Sum.v
Stated and proved Exercise 2.8.
Not sure about whether the definition of code_sum is adequate. Any suggestions are welcome.
> Prove coproduct type ap functoriality

- theories/Analysis/Locator.v
The issue in https://github.com/HoTT/Coq-HoTT/issues/1336 appears to have disappeared. Not really sure what the issue was but at least it was resolved.
Fix #1336
> Locator: Require can be combined again

- theories/Basics/Decidable.v
This commit is from #1929. I ended up using this elsewhere outside of #1929 so I deemed it was of interest on its own.
> abstract out some idioms for dealing with decidable types

- theories/Algebra/Rings/Module.v
Some lemmas about finite sums of scalars and module elements and how the left action interacts with them.
> finite sums and modules

- theories/Algebra/Rings/Module.v
Lemma about the left action on a negation in a left module.
> left action on negation

- theories/Spaces/Nat/Core.v
This is a simple lemma that comes in useful later. We could probably give a shorter proof with commutativity of nat addition, but I would prefer to keep this earlier on.
> injectivity of nat addition

- flake.nix
This lets you setup coq master with nix. To use it you do `nix develop --impure`. (`--impure` is required because `master` is a rolling version and cannot have a hash so it is not a "pure" evaluation according to nix.)
> nix: add coq master to nix flake

- .github/workflows/ci.yml
I'll merge this as soon as it is green since it is just a routine version bump.
> chore(ci): update to checkout@v4

- theories/Algebra/Rings/Matrix.v
In this PR we:
- Define a predicate on matrices `IsSymmetric`. Symmetric matrices are invariant under transposition.
- Show various operations and matrices are closed under being symmetric.
> symmetric matrices

- theories/Algebra/Rings/Matrix.v
In this PR we define what is means for a matrix to be skew-symmetric and prove some basic closure properties.
> skew-symmetric matrices

- test/WildCat/Opposite.v
- theories/WildCat/Monoidal.v
In this PR we introduce some lemmas for dealing with monoidal structures on the opposite category.
> opposite monoidal categories

- theories/WildCat/Coproducts.v
- theories/WildCat/Products.v
In this PR, we add some more results about coproducts. This includes the following:
- Bifunctoriality results
- Products and coproducts in opposite categories
- The cocartesian monoidal structure
- And various miscellaneous results
> more on coproducts

- theories/Algebra/Rings/Matrix.v
- theories/Algebra/Rings/Module.v
In this PR we introduce right R-modules as left module over the opposite ring and derive all the properties we have for left R-modules from them. Most of the work here is just giving the right module names for the left module definitions and lemmas. We don't prove anything new.
> right R-modules

- theories/Algebra/AbGroups/Abelianization.v
- theories/Algebra/Groups/FreeGroup.v
- theories/Algebra/Groups/GroupCoeq.v
- theories/Colimits/Coeq.v
> introduce Coeq_ind_hprop and use it

- theories/Algebra/Rings/KroneckerDelta.v
- theories/Algebra/Rings/Matrix.v
- theories/Algebra/Universal/Operation.v
- theories/BoundedSearch.v
- theories/Spaces/Finite/FinInduction.v
- theories/Spaces/Finite/FinNat.v
- theories/Spaces/Finite/FinSeq.v
- theories/Spaces/Finite/Finite.v
- theories/Spaces/List/Theory.v
- theories/Spaces/Nat/Arithmetic.v
- theories/Spaces/Nat/Core.v
This is part 3 of the cleanup of Nat following:
- #2028 
- #2040
In this PR we:
- Show various properties of subtraction
- Show all movement lemmas for summands around a `<=` or `<`.
- Show monotonicity of powers
- Move and reprove "strong induction" for nat. This will be a useful lemma when we start characterizing divisibility.
We have some TODOs which I will complete when I find the time:
> Cleanup of Nat.v part 3

- theories/Algebra/AbGroups/Cyclic.v
See https://github.com/HoTT/Coq-HoTT/issues/2022
> Added proof for ab_mul_cyclic_in

- theories/Basics/Decidable.v
- theories/Spaces/List/Theory.v
- theories/Spaces/Nat/Division.v
We define what it means to be a prime number and give a decision procedure for deciding if a given nat is prime. We give the first 8 primes as examples of this procedure.
This fixes #2008.
> Prime numbers

- theories/Algebra/AbGroups/Abelianization.v
In this PR we show that abelianization is a functor.
> Functoriality of abelianization

- theories/Algebra/AbGroups/FreeAbelianGroup.v
- theories/Algebra/Groups/FreeGroup.v
In this PR we show that `FreeGroup` is a functor. Together with #2064, this allows us to show that `FreeAbGroup` is a functor also.
> Functoriality of FreeGroup

- theories/Spaces/Finite/Finite.v
- theories/Spaces/Nat/Core.v
- theories/Spaces/Nat/Factorial.v
We develop some theory about factorials in a new file `Spaces/Nat/Factorial.v`. This will be useful for some upcoming work on binomial coefficients.
Notably we show that `(n! * m! | (n + m)!)` which is actually quite a tricky proof to get right. We have to induct on `n + m` rather than just `n` or `m`.
This is a draft for now as it depends on #2063.
> Nat: theory about factorials

- INSTALL.md
I've added some more information about the Coq Platform and opam versions as discussed in #2045.
> doc: update INSTALL.md about opam and platform versions

- theories/Basics/Notations.v
- theories/Categories/Comma.v
- theories/Categories/Comma/Core.v
- theories/Categories/Comma/Notations.v
- theories/Categories/Comma/Utf8.v
- theories/Classes/theory/ua_first_isomorphism.v
- theories/Classes/theory/ua_quotient_algebra.v
- theories/Classes/theory/ua_second_isomorphism.v
- theories/Classes/theory/ua_third_isomorphism.v
- theories/Spaces/Nat/Binomial.v
- theories/Spaces/Nat/Core.v
- theories/Spaces/Nat/Division.v
In this PR we introduce binomial coefficients as discussed in #2048. We prove basic identities about binomial coefficients, including the factorial formula.
In order to prove all of this, we also add a few more division lemmas.
> Nat: binomial coefficients

- .github/workflows/ci.yml
> fix version of upload artifact in alectryon job

- theories/Algebra/Groups/FreeProduct.v
We use the relevant list lemmas in FreeProduct.v which allows us to remove some redundant lemmas.
> cleanup FreeProduct.v

- STYLE.md
Our STYLE.md had become very out of date.  I've fixed the things I am aware of.  I'd like to merge this quickly, because I'm introducing the library to my class tomorrow.  So if there are further things to update, let's leave those for a followup PR.
> STYLE.md: many updates throughout

- theories/Algebra/AbGroups/Abelianization.v
- theories/Algebra/Rings/Localization.v
I noticed that we had some warnings about comments, so I've gone ahead and fixed them.
> fix coqdoc warnings

- theories/Pointed/Loops.v
Some small style tweaks I did when reading through.
> small style tweaks in Loops.v

- theories/Basics/Overture.v
- theories/Homotopy/Wedge.v
- theories/Types/Sigma.v
This makes it easier to read and write.
> introduce implicit arguments for sig_rec

- theories/Colimits/Colimit_Flattening.v
- theories/Homotopy/Syllepsis.v
- theories/Spaces/List/Paths.v
- theories/Spaces/List/Theory.v
- theories/Types/Sigma.v
A bunch of small things, mostly unrelated.  The commit messages give a summary.
> Misc cleanups

- STYLE.md
> remove NullHomotopy from STYLE.md

- theories/Types/Sum.v
These were missing and are straightforward to prove.
> functoriality lemmas for sum

- theories/Homotopy/Join/Core.v
I had a need for one of these, and I noticed that their could be some utility with stating a few more elsewhere.
> add and use more Join_ind lemmas

- theories/Algebra/Groups/Group.v
I added the rest of these lemmas since I found some use for them elsewhere.
> complete and organise grp_moveL_1M type lemmas

- .github/workflows/ci.yml
This is the recommended fix in https://github.com/coq-community/docker-coq-action/releases/tag/v1.5.1
> ci: fix permission issues in dev

- theories/Algebra/Groups/Group.v
This just slightly speeds up the build.
> Group: Make isunitpreserving_grp_homo opaque

- theories/Homotopy/Join/Core.v
- theories/Metatheory/ImpredicativeTruncation.v
> Join/Core, ImpredicativeTruncation: fix typos in comments

- theories/Basics/Equivalences.v
- theories/Homotopy/ClassifyingSpace.v
- theories/Types/Paths.v
Each commit is independent, and the commit messages explain them.
> Miscellaneous minor fixes

- STYLE.md
> remove mention of travis in STYLE.md and replace with GitHub actions

- theories/Basics/Equivalences.v
- theories/Basics/Overture.v
- theories/Basics/PathGroupoids.v
- theories/Basics/Trunc.v
- theories/Homotopy/EMSpace.v
- theories/Homotopy/EvaluationFibration.v
- theories/Homotopy/HomotopyGroup.v
- theories/Homotopy/Join/Core.v
- theories/Pointed/Loops.v
- theories/Pointed/pSusp.v
- theories/Spaces/List/Theory.v
- theories/Truncations/Connectedness.v
- theories/WildCat/Core.v
Another round of fixes and cleanups that I've accumulated.  Each commit is independent and small, and the change is described in the commit message.  The library builds after each commit.
> Miscellaneous clean ups and fixes
