HoTT/Coq-HoTT

coq/theories/Init/Specif.v

Now we won't see any more `{ x : _ | ... }` in the output; the type will
always appear.

Update sigma notations

---

theories/Basics/Overture.v

This allows us to force [function_scope] without opening it.

Give a key to function_scope

---

Makefile_targets.mk
theories/Constant.v
theories/HoTT.v

I'm proposing the name "conditionally constant" for a function that factors through the propositional truncation of its domain, to be distinguished from "weakly constant functions" which map all pairs of inputs to equal outputs and "constant functions" which factor through `Unit`.  This commit formalizes some basic facts about when weakly constant functions are conditionally constant, from the paper of Kraus, Escardo, Coquand, and Altenkirch.

conditionally constant functions

---

theories/Types/Sigma.v

Needed for classifying when a full subprecategory is actually a category.

Miscellaneous sigma lemmas

---

Makefile_targets.mk
contrib/HoTTBook.v
theories/Basics/Contractible.v
theories/Basics/Overture.v
theories/Basics/PathGroupoids.v
theories/Basics/Pointed.v
theories/HoTT.v
theories/ObjectClassifier.v
theories/PType.v
theories/Types/Paths.v
theories/Types/Sigma.v
theories/hit/Suspension.v

If anyone can manage to prove that the loop-suspension adjunction isomorphism given in the book is natural with respect to pointed maps, I'd love to see it!  I had to resort to a different definition using a unit and counit.
I am kind of pleased with the tactic `pointed_reduce`.  I had always expected that one of the more annoying things about HoTT for a classical homotopy theorist would be that basepoints can't be preserved strictly, so we have to carry around paths relating them everywhere.  But if we set things up correctly, then usually most of those paths can be path-inducted-away when actually proving things.

Pointed types and the loop-suspension adjunction

---

STYLE.md
theories/Basics/Overture.v
theories/Modalities/ReflectiveSubuniverse.v
theories/UnivalenceImpliesFunext.v
theories/categories/Category/Sigma/Univalent.v

See #657 for discussion.  Mainly, this is a way to aggregate the changes
and allow discussion of the name `reapply` (for a combination of
`rapply` and `eapply`), so that the commit that bumps trunk will be
small.

Use [refine] rather than [apply] in more places

---

theories/Basics/Overture.v

This closes #641.
This makes progress towards #657.
This makes #628 possible to solve.
We do not bump trunk all the way to current trunk, because something
broke type inference and typeclass resolution, which now fail in places
they did not used to.

Bump trunk

---

.travis.yml
Makefile.am
configure.ac
etc/ci/test-install-target.sh

Previously, we had separate logic in Makefile.am and configure.ac for
dealing with symlinks to the standard library.  Since no one was testing
the install target regularly, they had gotten out of sync.  This was
causing hoqide to fail when the library was installed.
Now, the configure script makes a list of symlinks for the makefile to
copy over in the install target.  This should fix hoqide.  Additionally,
the install target should now work fine on (Windows) configurations
where symlinks don't work.
Finally, we now test each stdlib directory for existence before
symlinking to it.  This prevents us from installing dangling symlinks to
the system, which wouldn't serve any purpose.
Also, test the install target on travis.
I don't actually have an install with hoqide though, so someone with …

Actually install all of the symlinks to stdlib

---

Makefile_targets.mk
contrib/HoTTBookExercises.v
theories/Basics/Contractible.v
theories/Basics/Equivalences.v
theories/Basics/Overture.v
theories/Basics/PathGroupoids.v
theories/HoTT.v
theories/Idempotents.v
theories/Modalities/Modality.v
theories/Spaces/BAut.v
theories/Spaces/BAut/Bool.v
theories/Spaces/BAut/Bool/IncoherentIdempotent.v
theories/Spaces/BAut/Cantor.v
theories/Types/Bool.v
theories/Types/Equiv.v
theories/Types/Paths.v
theories/Types/Sigma.v
theories/Types/Sum.v
theories/Types/Universe.v
theories/hit/Connectedness.v

Here we characterize the center and 2-center of BAut(X), and use those to construct an example of a quasi-idempotent that cannot be extended to a coherent one (though, by the general splitting construction, its underlying pre-idempotent can).

Centers of BAut(X), BAut(Bool), and an incoherent idempotent

---

etc/ci/generate_and_push_dep_graphs.sh

It seems that `dot` is just bad at gigantic files.  Hopefully this will
fix #692.

Disable file-dep-graphs/hott-all.svg on travis

---

Makefile.am

This allows hyperlinking in pide to work correctly.
I've replaced the list of `*_VOFILES` with the single `ALL_VOFILES`; they expand to the same thing, and this one is less typing.

Also install .glob files

---

theories/Modalities/Accessible.v
theories/Modalities/Closed.v
theories/Modalities/Identity.v
theories/Modalities/Localization.v
theories/Modalities/Modality.v
theories/Modalities/Nullification.v
theories/Modalities/Open.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Modalities/Topological.v
theories/hit/Truncations.v

With `Existing Class In` we can get rid of the need for most of the `_internal` fields for reflective subuniverses and modalities.  Unfortunately, I wasn't able to get rid of `O_ind_internal` and `O_ind_beta_internal` for modalities, since we need to have them already in order to prove that modalities are reflective subuniverses so that we can refer to the correct typeclass `In`.  (Suggestions are welcome...)

use Existing Class to get rid of some '_internal's

---

Makefile_targets.mk
STYLE.md
contrib/HoTTBook.v
theories/Basics/Overture.v
theories/HoTT.v
theories/Spaces/No.v

Although Coq doesn't support inductive-inductive types natively, I think I found a way of tricking it into defining the higher inductive-inductive surreals with a sort-of judgmental computation law on the point-constructor.  (I say "sort of" because the proof of cut-ness turns out to be a different axiom than the one one that you might hope it to be, but the options are judgmentally what you expect.)  If anyone can see a flaw in this definition (i.e. a way to escape from the trick and prove something that shouldn't be possible), please point it out.
I am somewhat astounded that Theorem 11.6.7 from the book turned out to be basically correct.  (-:O  And in retrospect, I'm not surprised that the definition of surreal addition was too simplistic and needed an enhanced double induction …

The surreal numbers

---

theories/hit/Suspension.v

It's no longer needed, now that we have explicit universe levels

Remove a universe hack

---

etc/ci/install_coq_dot_deps.sh

`cabal update` sometimes errors with
Downloading the latest package list from hackage.haskell.org
cabal: <socket: 3>: resource vanished
Now we retry multiple times.

Retry `cabal update` 10 times

---

Makefile_targets.mk
theories/HoTT.v
theories/Tactics/EquivalenceInduction.v

I've defined `equiv_induction`.
Unfortunately, it currently requires `Funext` in essentially all cases.  It should be possible to make it more fine-grained, so that we don't need `Funext` to deal with functions in one direction or the other, and only need it for equalities.
This closes #691.

Equivalence induction

---

Makefile_targets.mk
theories/Basics/PathGroupoids.v
theories/EquivGroupoids.v
theories/HoTT.v

Should we consider replacing [IsEquiv] with a definition that has more
judgmental properties, and doesn't require [Funext] for proving all of
the groupoid structure?  (Is there such a definition?)

Add 1-Groupoid structure of equivalences

---

Makefile.am
configure.ac

With a bit of help from stackoverflow, it's possible to not run coqdep when we run `make clean`.

Better `make clean` target

---

hoq-config.in

Do this by checking for the existence of `cygpath`, and Windowsifying
the paths if it exists.  This breaks machines with a `cygpath` in
`PATH` which don't support Windows paths, but such machines are rare,
I believe.

Fix hoqide on Windows

---

Makefile_targets.mk
theories/categories/Grothendieck/ToSet.v
theories/categories/Grothendieck/ToSet/Core.v
theories/categories/Grothendieck/ToSet/Morphisms.v
theories/categories/Grothendieck/ToSet/Univalent.v

An answer to Mike's suspicion on the mailing list.
It seems to be much, much, much easier to construct an equivalence `(s = d) ≃ (s ≅ d)` and prove it's carrier function equal to `idtoiso`, than it is to directly construct a function `(s ≅ d) → (s = d)` and prove that it's a section and retraction of `idtoiso`.  Any ideas if this is an instance of a more general property?  (Or ideas for why this is the case?)
If anyone want's to try their hand at pseduofunctor "path" algebra, there are [a few `admit`s left in this branch that does this construction for the Grothendieck construction for a pseudofunctor to cat](https://github.com/HoTT/HoTT/compare/master...JasonGross:grothendieck-cat-univalent#diff-91e920f8e0ee250520376601b86f019eR39).

Prove saturatedness - Grothendieck of F : C -> Set

---

Makefile_targets.mk
theories/HoTT.v
theories/hit/FreeIntQuotient.v

The quotient of a set by a free action of the integers can be defined as an untruncated homotopy coequalizer, but turns out to be a set automatically.  It ought to be true more generally that the homotopy quotient of a set by a free action of any group is again a set, but defining "homotopy quotient" in generality is tricky; for the integers we can do it by coequalizing the action of 1 with the identity.

quotients by free actions of Int

---

theories/Modalities/ReflectiveSubuniverse.v
theories/hit/Coeq.v

where "preserve" means "map them to colimits in the subuniverse, i.e reflected colimits".  The proof for coequalizers was really hard; I kind of hope I am missing something obvious that would make it easier.

reflectors preserve coproducts and coequalizers

---

theories/Modalities/ReflectiveSubuniverse.v
theories/Tactics/RewriteModuloAssociativity.v
theories/Tests.v

When the hypothesis contained `a @ (b @ c)` where the implicit arguments to `concat` did not match the implicit arguments inferred for `@concat _ _ _ _ a (@concat _ _ _ _ b c)` (according to `pattern`),
`left_associate_concat_in` looped, repeatedly finding `a @ (b @ c)`, and failing to associate it to the left, introducing constant transports that did nothing.
This is now fixed, by picking up and passing the implicit arguments, explicitly.
The comment in Modalities/ReflectiveSubuniverse.v has been updated; a naive use of `rewrite@A` causes the subsequent rewrite to fail.  I haven't tracked it down, but I suspect @mikeshulman wouldn't have much trouble updating the file.
This fixes #744; the test is now added to Tests.v.

Fix [rewrite@A]

---

contrib/Freudenthal.v
coq/theories/Init/Logic.v

In 8.5beta2, the built-in [admit] which uses [proof_admitted] is
replaced by one aliased to [shelve]; we bring it back so we can use it
in transparent proofs, in contrib/Freudenthal.v.

Add a local admit tactic to contrib/Frudenthal.v

---

theories/Fibrations.v
theories/Modalities/Closed.v
theories/Modalities/Identity.v
theories/Modalities/Lex.v
theories/Modalities/Localization.v
theories/Modalities/Modality.v
theories/Modalities/Nullification.v
theories/Modalities/ReflectiveSubuniverse.v
theories/hit/Truncations.v

There was one too-big universe coming from an application of `transitivity` to `Equiv` elsewhere, which I got rid of.  The collapsing of universes was due to repleteness not being able to move between universes, which seems like a serious bug in its own right, so I fixed it (though I had to introduce an extra "max" universe everywhere).  And in order to track those down I pretty much had to get rid of all the redundant universes anyway, so now it actually works.

Make Lex_Reflective_Subuniverses actually instantiate SigmaClosed

---

theories/Tactics/EquivalenceInduction.v
theories/Tests.v

This makes `equiv_induction` work even when typeclass resolution fully solves the side-condition.
Also add a test case from #754.

Make [equiv_induction] a bit more robust

---

configure.ac

Coq seems to have a different error message in newer versions

Make checking for symlink support more robust

---

theories/Spaces/BAut/Bool.v

A couple of these proofs were really unnecessarily complicated.  I'm not sure what I was thinking.  The shorter proofs speed the file up by almost 1/3.
Amusingly, I discovered this while _informalizing_ these proofs for a paper I'm writing.  There's probably a lesson in that.

Simplify some proofs in Spaces/BAut/Bool

---

theories/Basics/PathGroupoids.v
theories/hit/TwoSphere.v

I changed the type of S2_ind to match Chapter 6 of the HoTT Book, and changed S2_ind_beta_loop to S2_ind_beta_surf. I added some lemmas used in the definition of S2_rec_beta_surf to PathGroupoids.v.
I also constructed an equivalence S2 <~> Sphere 2 ([here](https://github.com/jdoughertyii/HoTT/blob/spheres_with_S2/theories/hit/Spheres.v#L78)), but it's not included in this pull request because it takes a full minute and a half to compile.  I don't know if that's something that would be worth trying to improve and submit.

define TwoSphere recursion

---

Makefile.am
_CoqProject
etc/dpdgraph-0.4alpha/hoqthmdep
hoq-config.in
hoqc
hoqdep
hoqide
hoqtop
hoqtop.byte

In standard coq, there is a `user-contrib` directory where additional libraries can be installed, and this is available automatically at the top level of the initial `LoadPath`, so that contributed libraries can be loaded by their own names, with no additional prefix.  This gives a canonical way for contributed libraries to invoke each other.
Currently, there doesn’t seem to be an analogous canonical place to install further libraries over the `HoTT` library.  The repo provides a `contrib` directory (currently containing three individual `.v` files), but this is not by default available in the `LoadPath`.
This pull request adds that `contrib` directory to the default `LoadPath` in `hoqtop` (and other scripts), making its contents available with no additional toplevel prefix, just like the …

Add `contrib` directory to default `LoadPath` of `hoqtop`, `hoqc`, etc.

---

theories/Basics/Overture.v
theories/Spaces/BAut/Cantor.v

It seems to me a minor but useful modification.
So that we can do:
`Example bla (A B : Type) : A <-> B.`
`symmetry.
etransitivity.
apply reflexivity.`
`Abort.`
This changes the order of the arguments of iff_compose.
By the way: could we tweak reflexivity so that we can write `reflexivity` instead of (`apply reflexivity`)?
(It would be useful for the `<~>` relation.)

Declare iff as a transitive, symmetric reflexive relation.

---

theories/Extensions.v
theories/Modalities/Modality.v

To be compatible with the new semantics of explicit universe
declarations in lemma statements (Coq pr #177, forward compatible).

Bugfix #4527 Add universe annotations

---

theories/Modalities/Identity.v

And now produces the right length-mismatch error
with Coq's PR #168 (backward compatible change).

Fix universe annotation that was silently ignored

---

STYLE.md
contrib/HoTTBookExercises.v
theories/Basics/Overture.v
theories/Extensions.v
theories/Idempotents.v
theories/Modalities/Accessible.v
theories/Modalities/Closed.v
theories/Modalities/Identity.v
theories/Modalities/Lex.v
theories/Modalities/Localization.v
theories/Modalities/Modality.v
theories/Modalities/Notnot.v
theories/Modalities/Nullification.v
theories/Modalities/Open.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Types/Unit.v

The only complicated fixing was in Modalities which needed changes in the universe annotations.
Universe minimization to Set is globally disabled so that we get lemmas like `Contr@{i} Unit` for all `i`. If Coq had cumulative inductive types like in http://advent-project.eu/pubs/cit-ictac15.pdf it might not be needed.
It is locally re-enabled in Idempotents to avoid a blowup in the number of universes (IsIdempotent goes from 4 to 51 universes), and for `Book_3_14` in the exercises to avoid some error.

Put Empty and Unit in Type0

---

contrib/Freudenthal.v
theories/Basics/PathGroupoids.v
theories/HIT/Spheres.v
theories/HIT/Suspension.v

Construct an equivalence S2 <~> Sphere 2. Rename beta principles for suspensions to match other HITs.  The compile time for Spheres.v is up to 3.3s, but this is as fast as I could get it.

S2 <~> Sphere 2

---

theories/HIT/Pushout.v

Proof that `pushout f g <~> pushout g f`, and results directly from functoriality of Coeq.
It might (?) be useful, in the spirit of forgetting that pushouts are defined via coequalizers, to have the whole Functoriality part of .Coeq redone for .Pushout, but so far this is the only result I really wanted to have without going back to Coeq.

Symmetry for pushout, pushouts preserve equivalences

---

coq/theories/Init/Notations.v
coq/theories/Program/Tactics.v
theories/Basics/Overture.v
theories/Categories/Adjoint/Functorial/Laws.v
theories/Categories/Pseudofunctor/FromFunctor.v
theories/Categories/Pseudofunctor/RewriteLaws.v
theories/Tactics/EquivalenceInduction.v
theories/Tactics/RewriteModuloAssociativity.v

- adapt to new ltac:(constr) syntax.
- `Global Unset Bracketing Last Introduction Pattern` set.
- @mattam82's tweaks for `Hint Extern` and class resolution.
- @mattam82's scoping backport in `Init.Notations`
Tested with:
```
The Coq Proof Assistant, version 8.5pl3 (November 2016)
compiled on Nov 29 2016 17:34:9 with OCaml 4.03.0
```

Basic 8.6 compatibility.

---

theories/HIT/Suspension.v

As you can see here: http://hott.github.io/HoTT/coqdoc-html/HoTT.HIT.Suspension.html
The nested comment just before [loop_susp_unit](http://hott.github.io/HoTT/proviola-html/HoTT.HIT.Suspension.html#loop_susp_unit) is badly handled and make the whole file corrupted.
As this comment is redundant, I propose to remove it.

Remove a nested comment to make proviola happy

---

_CoqProject
theories/Basics/Notations.v
theories/Basics/Overture.v
theories/Basics/PathGroupoids.v
theories/HIT/Colimits.v
theories/HIT/Colimits/Coequalizer.v
theories/HIT/Colimits/Colimit.v
theories/HIT/Colimits/Colimit_Prod.v
theories/HIT/Colimits/Colimit_Sigma.v
theories/HIT/Colimits/CommutativeSquares.v
theories/HIT/Colimits/Diagram.v
theories/HIT/Colimits/Flattening.v
theories/HIT/Colimits/MappingTelescope.v
theories/HIT/Colimits/Pushout.v
theories/Types/Forall.v
theories/Types/Paths.v
theories/Types/Sigma.v

Hi everyone,
This PR add the colimit library as described in https://github.com/HoTT/HoTT/issues/845.
Please feel free to comment.
Here are some debatable points on which I could work if you think they prevent merging:
* The tactic `funext` (I find it very convenient, but could be removed if you don't like it.)
* The notation `≃` which is utf8
* The lack of comments

Colimit library

---

theories/Basics/Equivalences.v

(contr_equiv_contr was renamed to contr_equiv in 01d2fdac)

Remove a no-longer-relevant comment

---

theories/Basics/Trunc.v
theories/Modalities/Closed.v
theories/Modalities/Identity.v
theories/Modalities/Notnot.v

This is part of an attempt to make the hpropresizing branch faster.  I'm not sure I picked the right universe to remove `theories/Modalities/Closed.v`; @mikeshulman, can you take a look at that change?

Give trunc_{contr,hprop,hset} only one universe

---

contrib/HoTTBook.v

I only noticed that it was a lemma in the book after #857 was merged.

Lemma 7.6.2 [IsTruncMap n.+1 f <-> IsTruncMap n (ap f)] to HoTTBook

---

theories/Categories/Adjoint/Composition/LawsTactic.v
theories/Categories/Adjoint/UnitCounit.v
theories/Categories/Category/Morphisms.v
theories/Categories/ExponentialLaws/Law4/Functors.v
theories/Categories/ExponentialLaws/Tactics.v
theories/Categories/Functor/Attributes.v
theories/Categories/Functor/Composition/Core.v
theories/Categories/Functor/Dual.v
theories/Categories/Functor/Paths.v
theories/Categories/Functor/Sum.v
theories/Categories/Grothendieck/PseudofunctorToCat.v
theories/Categories/Grothendieck/ToSet/Core.v
theories/Categories/NaturalTransformation/Composition/Core.v
theories/Categories/NaturalTransformation/Identity.v
theories/Categories/Pseudofunctor/FromFunctor.v
theories/Categories/SetCategory/Functors/SetProp.v
theories/Categories/UniversalProperties.v
theories/Categories/Yoneda.v

This paves the way for making `Functor C D` unify with `Functor C' D'` so long as the fields unify.  See #849.

Use functor notations [F _0 x] and [F _1 m] more

---

theories/Types/Forall.v

This is a port of `equiv-Π'` from HoTT-Agda, and a composition lemma about it that isn't in HoTT-Agda yet.  The composition lemma may be the first place where it matters that we defined isequiv_compose without adjointifying, so that both homotopies remain the explicitly given ones.

equiv_functor_forall_covariant and its composition.

---

theories/Modalities/Lex.v

Coqdoc has a special meaning for `%`, so we use unicode instead, so that coqdoc doesn't chop off the comment.  (Also change http to https.)

Improve a comment in Lex.v

---

theories/Modalities/Lex.v
theories/Modalities/Modality.v

Turns out the pullback lemma that "probably is not equivalent to lex-ness" is actually equivalent to lex-ness.

Two more characterizations of lex modalities

---

Makefile.am

This allows the library builds to be more reproducible, and they won't
include things people stuff in ~/.coqrc.  This is how coq_makefile does
things.

Don't load the user's resource file

---

theories/Modalities/Lex.v
theories/Modalities/Modality.v

It turns out that the main part of the characterization of accessible lex modalities in terms of modal-ness of the universe doesn't depend on accessibility and is an equivalent characterization of lex-ness for arbitrary modalities, namely that families of modal types indexed by a connected type are constant.

Factor out part of accessible lex modalities

---

STYLE.md
_CoqProject
theories/ExcludedMiddle.v
theories/HIT/Connectedness.v
theories/HoTT.v
theories/Spaces/BAut.v
theories/Spaces/BAut/Rigid.v
theories/Spaces/Universe.v
theories/Types/Empty.v
theories/Types/Sum.v
theories/Types/Universe.v

The part of https://homotopytypetheory.org/2017/01/26/parametricity-automorphisms-of-the-universe-and-excluded-middle/ having to do with automorphisms of the universe, plus a clever argument due to @peterlefanulumsdaine showing that we can swap `X*A` with `X*B` when `A` and `B` are rigid and connected while `X` is truncated.

Rigid types and automorphisms of the universe

---

.gitignore
Makefile.am

This way they can be ignored by file managers / emacs autocompletion/ etc without ignoring D language files.

Use .v.d suffix for Coq dependency files.

---

contrib/HoTTBook.v
theories/Spaces/No/Addition.v
theories/Spaces/No/Core.v
theories/Spaces/No/Negation.v

Basically, you can get a "notion of surreal numbers" by restricting the types parametrizing the left and right options in any way you like, and the basic theorems about order are completely unaffected, while addition and so on do just fine as long as the option sorts are closed under the appropriate operations.  In particular, this includes the plump ordinals from Exercise 11.17 in the book.  All kinds of generalized surreal numbers embed into the "maximal" surreal numbers, though I don't know of a good way to define their images intrinsically.  Finally, and interestingly, *every* surreal number is equal to one whose option sorts are decidable (i.e. either it has no left options or it has a left option, and either it has no right options or it has a right option).

Generalized surreal numbers parametrized by option sorts

---

theories/PropResizing/Truncations.v

Add an example that shows the benefit of propositional resizing for propositional truncation.
This is just for illustration - only two local definitions given.
I wanted to see what happens w/o resizing in this context, and my experiments are seen in a new sister file, see [my commit in another branch](https://github.com/rmatthes/HoTT/commit/6c38787d73fe0e21093753d0dc169dbe4f9081ce). Maybe that other part was obvious to you.

elaborate on example for prop. resizing for truncation

---

theories/Categories/ChainCategory.v

This patch makes HoTT compile after the changes in primitive projections introduced in PR coq/coq#984. It should be backward compatible with Coq 8.7.0.

Backward compatible fix w.r.t. changes in primitives projections

---

theories/Classes/implementations/natpair_integers.v

This fixes #899.
HoTTClasses wasn't merged in the branch for Coq CI so Coq broke it silently.

Fix primitive projections for Classes (see #898).

---

.gitmodules
.travis.yml
autogen.sh
coq/theories/Init/Notations.v
etc/ci/before_script.sh
etc/ci/install_coq.sh
etc/ci/install_dep_graphs_deps.sh

We update Travis building on #846, but following a bit more the recent Coq's Travis file. In particular, we include a non-broken Ocaml version which allows us to test Coq 8.7.
This seems ready to merge but could use some more refinements, in particular wrt the matrix and packages.
Also, there are good news, HoTT works well with current Coq trunk. I understand current Coq's policy is to treat compatibility breakages very seriously, thus I suggest the `trunk` build remains enabled.
Possible TODOs:

[travis] Ocaml.4.02.3 + Coq 8.7

---

_CoqProject
theories/Classes/implementations/bool.v
theories/Classes/implementations/hprop_lattice.v
theories/Classes/implementations/pointwise.v
theories/Classes/interfaces/abstract_algebra.v
theories/Classes/theory/lattices.v

These commits introduce classes `BoundedLattice` and `BoundedMeetSemiLattice`, and show that
- booleans
- `hProp`
- functions `A -> B` for a (bounded) lattice `B`
form bounded lattices.
Some context for this: we have been working on a [formalisation of Kuratowski-finite sets](https://github.com/nmvdw/HITs-Examples/tree/master/FiniteSets) in HoTT pre hottclasses. For those purposes we had some in-house typeclasses for unified notation and generalized lemmas. In particular, for many proofs about finite subobjects we relied on the fact that `hProp` and `A -> hProp` are bounded lattices.
We would like to port our code to the "new" HoTT enhanced with hottclasses. I think at least the `hProp` instances can be quite useful in general.
Pinging @nmvdw, @spitters.

A class for bounded lattices with some examples

---

theories/Basics/Overture.v
theories/Pullback.v
theories/Types/Record.v
theories/Types/Sigma.v

This PR propose to add notations for nested pairs, a feature I often wanted.
Unfortunately we cannot define a recursive notation like this one:
` Notation "( x ; .. ; y ; z )" := (existT _ x .. (existT _ y z) .. ) : fibration_scope. `
because of bug https://github.com/coq/coq/issues/6032.
I removed a few now unnecessary parentheses to test.
You can find them with `grep -R "(.*; (.*; .*))" *` (there are some false positive) ; there are not so much in the library.

Add notations (x ; y ; z) to ( x ; y ; z ; t ; u ; v )

---

INSTALL.md

Changing `proof-prog-name` has no effect for me. Maybe we should use `coq-prog-name`?

ProofGeneral variable for Coq

---

theories/Classes/theory/premetric.v
theories/Modalities/Accessible.v

This patch fixes the compilation of HoTT with the soon-to-be master branch of Coq. Indeed, PR coq/coq#6483 suppresses spurious universes generated by monomorphic effects in polymorphic proofs. Unluckily, it is not backward-compatible, although if desired I can use the same kind of hacks as in PR #906 to work around this.

Fix compilation in the check-poly-effects branch.

---

Makefile.am

In Coq master, coqchk supports being pasesd .vo files and no longer
supports unqualified library names.

Fix validate target

---

contrib/HoTTBookExercises.v
etc/Book.py

HoTTBookExercises.v has been validated with `make contrib', and this went well. However, there is issue #921. The warnings about Book_5_2 in HoTTBookExercises.v appear to stem from pedagogical considerations:
````
Query commands should not be inserted in scripts
prod_rect
: forall (A B : Type) (P : A * B -> Type), (forall (fst : A) (snd : B), P (fst, snd)) -> forall p : A * B, P p
The command has indeed failed with message:
In environment
ez := true : Bool
es := fun _ : nat => idmap : nat -> Bool -> Bool
The term "1" has type "Book_5_2_i = Book_5_2_i" while it is expected to have type "Book_5_2_i = Book_5_2_ii"
(cannot unify "Book_5_2_i" and "Book_5_2_ii").
The command has indeed failed with message:
In environment
ez := 1 : nat
es := fun _ : nat => S : nat -> nat -> nat
The term "1" has …
```

simpler proof of Exercise 6.9 not using univalence

---

etc/Book.py

Line 193 in Book.py broke HoTTBookExercises.v, for example, in Book_2_2 where references to Book_2_1 occur. I experimented with limiting substitution to contexts of the form `Definition Book_X_Y`. But then Exercise 2.3 was still broken, while it made sense to call the definition there Book_2_1_concatenation4. We probably don't need the substitution anymore, as the numbering in book is not likely to change. If this assumption proves to be false, the substitution could be reintroduced on an ad-hoc basis. 
If this patch is accepted, I will change the guidelines in the files HoTTBook{Exercises}.v accordingly.

No substitution of "Book_X_Y" at all

---

theories/Classes/interfaces/canonical_names.v
theories/Classes/interfaces/integers.v
theories/Classes/interfaces/naturals.v
theories/Classes/theory/dec_fields.v
theories/Classes/theory/fields.v

The Classes libray declares the notation (in `theories/Classes/interfaces/canonical_names.v`):
```coq
Notation "x ↾ p" := (exist _ x p) (at level 20) : mc_scope.
```
However, the HoTT library itself already has (in `theories/Basics/Overture.v`):
```coq
Notation "( x ; y )" := (existT _ x y) : fibration_scope.
```
(Note that we have `Notation existT := exist (only parsing).` in `coq/theories/Init/Specif.v`.)
This PR removes the declaration from Classes and replaces its usages with the one from the overture.

Deduplicate notation for defining dependent pairs

---

theories/TruncType.v
theories/Types/Sigma.v
theories/Types/Universe.v

We've used these properties in another development, but they seemed general enough to me.
I don't think those are mentioned in the HoTT book necessarily, though.
I tried to implement it without rewrites, but failed to do so in a number of cases, don't know if that's important.

Show that `path_sigma_hprop` and `path_trunctype` are functorial.

---

Makefile.am

This should allow them to be picked up by the timing to html script in
Coq's benchmark.

Timing files should be "foo.v.timing" to match coq_makefile

---

_CoqProject
contrib/HoTTBook.v
contrib/HoTTBookExercises.v
theories/Basics.v
theories/Basics/Contractible.v
theories/Basics/Equivalences.v
theories/FunextVarieties.v
theories/HIT/IntervalImpliesFunext.v
theories/HIT/TruncImpliesFunext.v
theories/HoTT.v
theories/Idempotents.v
theories/UnivalenceImpliesFunext.v

Martin Escardo pointed out that this fact is in Foundations.  But somehow it never made it into this library, and I wasn't even aware that it was known.
I had to move `FunextVarieties` out of `Basics` so that it can import `EquivalenceVarieties`, but this had no ill effects, just requires importing it explicitly in a few places.

Non-dependent funext implies dependent funext

---

.travis.yml
INSTALL.md

Note that the V8.7 tag is the version of the library that supports Coq
8.7.
Also update the submodules.
Closes #943
Closes #927

Drop support for Coq 8.7, have travis test 8.8

---

_CoqProject
contrib/HoTTBookExercises.v
theories/BoundedSearch.v
theories/HoTT.v
theories/Spaces/Nat.v

If we know that there exists a natural number for which a decidable predicate `P` holds, then we can find a natural number for which `P` holds, by a bounded search.
This theorem was also implemented by [Matthieu](https://mattam82.github.io/HoTT_Markov/) (using the HoTT library) and [myself](https://github.com/UniMath/UniMath/pull/787) (using the UniMath library) (although I have previously erroneously referred to this as an instance of Markov's principle, which it is not: MP converts negative information into positive information, whereas this theorem converts mere existence into witnesses.).

Implement Escardo's bounded search

---

.gitmodules
.travis.yml
INSTALL.md
etc/ci/before_script.sh

This commit is intended to be the last commit that we guarantee builds
with Coq v8.8.  This commit (or the merge commit of this PR) will be the
target of the V8.8 tag, and after this commit is merged, we will drop
support for Coq 8.8 in preparation to merge the PR that allows
compatibility with numeral notations.

Set Coq version to 8.8.1

---

.gitmodules
.travis.yml
INSTALL.md
etc/ci/before_script.sh

We bump the versions of the dpdgraph and coq submodules, and tell travis
to stop checking 8.8 in preparation for numeral notations landing in
Coq.  This will allow us to merge #945
quickly once numeral notations lands.
On top of #952.  It'd be nice to get #952 and this PR merged quickly, so I can tag V8.8, and then get the necessary approving reviews on #945 so that it can be merged in sync with https://github.com/coq/coq/pull/8064 (which is basically ready to be merged).

Drop support for Coq 8.8 in preparation for 8.9

---

Makefile.am
coq/theories/Init/Datatypes.v
coq/theories/Init/Decimal.v
coq/theories/Init/Nat.v
coq/theories/Init/Peano.v
coq/theories/Init/Prelude.v
coq/theories/Program/Tactics.v
theories/Basics/Overture.v

This PR is required for compatibility with https://github.com/coq/coq/pull/8064.  Since it is not backwards compatible (and there's no easy way to make it backwards compatible), it should not be merged until https://github.com/coq/coq/pull/8064 is merged (and it should be merged immediately afterwards).
I still need to update .travis on this PR to test only with the master branch.
Before this PR is merged, we should make a tag for v8.8, and update travis (since we're no longer compatible with 8.7).

Fix for numeral notations

---

.travis.yml

Now that the validate target actually works, we don't want to allow it to fail.

Don't allow validate to fail

---

theories/BoundedSearch.v

Added by mistake in 949cdcc. Spotted by @co-dan.

Delete erroneously committed SearchAbout command

---

theories/Categories/InitialTerminalCategory/Functors.v
theories/Categories/InitialTerminalCategory/NaturalTransformations.v
theories/Tactics/EquivalenceInduction.v

Adds compatibility with coq/coq#8820.
`EquivalenceInduction.v` had two premises named `HP`.
The changes in `InitialTerminalCategory/` are to avoid coq/coq#8819.

Adapt to coq/coq#8820

---

theories/Categories/NaturalTransformation/Isomorphisms.v

The default choice of implicit arguments for Instances combined with the `Implicit Arguments` option is currently inconsistent with other commands like `Definition`. coq/coq#9314 changes this behavior, but https://github.com/HoTT/HoTT/blob/31c31c5c7673141979e274bc0afcc21417af9698/theories/Categories/Pseudofunctor/RewriteLaws.v#L44 is incompatible with the new default choice of implicit arguments for `iso_whisker_l`
Here we explicitly specify the implicit arguments for nearby instances as well to maintain compatibility.

Fix implicit arguments to be compatible with coq/coq#9314

---

STYLE.md

Code formatting was inverted because there was an single quote instead of a backtick.

Fix formatting in STYLE.md

---

theories/Categories/ExponentialLaws/Law0.v
theories/Categories/ExponentialLaws/Law1/Functors.v
theories/Categories/InitialTerminalCategory/Core.v

This is in preparation for coq/coq#9274.
Should be backward compatible but that remains to be tested.

Make trivial instances explicit

---

.gitmodules
.travis.yml
INSTALL.md
Makefile.am

Now that 8.9.0 has been released, we can bump the versions of things to 8.9.
Once this is merged, I will tag V8.9, and I will make a PR to bump the version of Coq to current master, and then we can merge #964, #971, and maybe #961.

Bump versions to 8.9.0

---

Makefile.am

`coqtop` is more geared towards interactive use; use `coqc` instead in
prevision of changes upstream.

[build] Use coqc for batch compilation instead of coqtop.

---

theories/HIT/Coeq.v
theories/HIT/Spheres.v
theories/HIT/Suspension.v

Changed the definition of suspension to be defined in terms a pushout. It should lose none of it's functionality. This will also make it possible to use flattening lemma on pushouts.
I have also added universe parameters to coequalizers as they were omitted before.

Changed definition of suspension to be in terms of pushout

---

theories/Functorish.v
theories/Spaces/No/Core.v

This was a noop and will soon be an error (until `Inductive` properly
supports locality attributes). See https://github.com/coq/coq/pull/9410

Remove locality attributes for `Inductive` and related commands

---

contrib/Freudenthal.v
theories/Basics/Notations.v
theories/Basics/Trunc.v
theories/HIT/Connectedness.v

As discussed at #1002, it seems that this notation is misleading.

change -2+ to +2+

---

_CoqProject
theories/Homotopy/HomotopyGroup.v
theories/Pointed.v

Defined the homotopy group of a pointed type. It uses the Groups structures found in mathclasses. I also modified `iterated_loops` in `Pointed.v` so that I can have loops on the outside, allowing path lemmas to be used.
The constructors for mathclasses are very slow, I am not really sure why? Perhaps it is my use of `serapply`?
I have also started a `Homotopy` foldeer in `theories`, later on we can move more synthetic homotopy theory relevent things here. At least it is a start.

Added definition of homotopy group

---

INSTALL.md

add `opam init` step in the OS X instructions

adding missing install steps

---

theories/Basics/Overture.v
theories/Classes/implementations/natpair_integers.v
theories/Modalities/ReflectiveSubuniverse.v
theories/PropResizing/Nat.v
theories/TruncType.v

Make the paths type cumulative, so that it can be used with Equations
Making paths cumulative means that the universe parameter is now treated as irrelevant:`@paths@{i} A x y <= @paths@{j} A x y` for any i and j (which must by typing be greater or equal to A's universe). See the [section on cumulative inductives](https://coq.inria.fr/refman/addendum/universe-polymorphism.html?highlight=irrelevant#cumulative-noncumulative) for more information.
This allows, e.g. to inject `@paths@{Set} nat x y` equalities in higher universes, and deconstruct equalities in the homogeneous cumulative sigma type used by Equations (where both components live in the same universe, and the sigma as well) into equalities for the components, e.g: `@paths{i} (Sigma@{i} x : nat, P x) p q` can be turned into …

Cumulative paths

---

theories/Basics/Overture.v
theories/Categories/Category/Sigma/OnObjects.v
theories/Fibrations.v
theories/HIT/Colimits/Flattening.v
theories/HIT/Colimits/Pushout.v
theories/Modalities/Topological.v
theories/Types/Sum.v

I don't know if anyone is listening, but I think this is an argument against relying on fancy tactic stuff like this.  Not only does it make the code harder to step through and understand, but it renders it fragile to changes to the details of tactics, and when that happens it is hard to figure out how to fix it because it's hard to step through and understand.

Remove Bracketing Last Introduction Pattern, close #993

---

Makefile.am
coq/theories/.dir-locals.el

`-boot` is currently a noop and will be removed in 8.11.

[coq] Remove use of deprecated -boot option.

---

theories/Categories/Adjoint/UnitCounit.v

HoTT was relying on a Coq bug which made some bound scopes visible even
if they were not imported in some scenarios. We avoid this by declaring explicitly some argument scopes.
This is in preparation for https://github.com/coq/coq/pull/10181, but
should be backward compatible (remains to be tested).

Declare argument scopes explicitly for `AdjunctionUnitCounit`

---

contrib/HoTTBookExercises.v
coq/theories/Init/Datatypes.v
coq/theories/Init/Notations.v
coq/theories/Init/Specif.v
theories/Basics/Overture.v
theories/Categories/Adjoint/HomCoercions.v
theories/Categories/Adjoint/UnitCounitCoercions.v
theories/Categories/Adjoint/UniversalMorphisms/Core.v
theories/Categories/Category/Morphisms.v
theories/Categories/Grothendieck/ToCat.v
theories/Categories/NatCategory.v
theories/Categories/Pseudofunctor/FromFunctor.v
theories/Categories/SetCategory/Functors/SetProp.v
theories/Classes/tactics/ring_quote.v

This patch fixes all the compilation warnings.
**EDIT:** except from the warnings from coqdep `declared ML module ... has not been found!`

Remove compilation warnings

---

theories/Utf8.v

Using the ordinary pipe symbol here breaks some instances of `match`, which uses that same symbol.

Change |a| syntax to a unicode, to avoid confusion with matches

---

Makefile.am
configure.ac
hoq-config.in

in Install.md the option --datadir to configure is described. But it does not work. The variable datadir is set but not used. This PR fixes this.

Fix handling of --datadir in autoconf and configure

---

theories/Basics/Overture.v
theories/Types/Bool.v

These patches add declarations to help Coq tactics know about the identity type used in HoTT and allow calling "induction" on booleans (useful for generic tactics), along with a minor fix for "autoapply"

Minor coq fixes

---

_CoqProject

The contrib files were incorrectly commented out in #1062, preventing hoqc from functioning from an installed HoTT.
See also https://github.com/HoTT/HoTT/pull/1062#issuecomment-520593918

Uncomment contrib in _CoqProject

---

_CoqProject
theories/HIT/Pushout.v
theories/HIT/SetCone.v
theories/HIT/epi.v
theories/HoTT.v
theories/Modalities/ReflectiveSubuniverse.v

Pushouts of equivalences are equivalence, pushouts are associative, pushouts have a universal property, and a reflective subuniverse reflects pushouts (into pushouts in the subuniverse, as with other colimits).  I had to break the bit about "set cones" out of Pushout.v to avoid cyclic dependencies with ReflectiveSubuniverse.

A bunch of lemmas about pushouts

---

_CoqProject
theories/Basics/Equivalences.v
theories/HIT/Join.v
theories/HIT/Pushout.v
theories/HIT/SpanPushout.v
theories/HIT/Truncations.v
theories/HoTT.v
theories/Homotopy/BlakersMassey.v
theories/Homotopy/Freudenthal.v
theories/Modalities/ReflectiveSubuniverse.v

This proof of (G)BM is a bit different from the existing one: by using a pushout to define the left side of the codes fibration, it doesn't need to assume surjectivity of one map until the point of proving contractibility.  I suspect it should be possible to do away with surjectivity there too, but haven't managed to work it out yet.  Anyway, assuming surjectivity is enough for classical BM and hence Freudenthal, which are also included here.  ABFJ use a different trick to discharge the assumption of surjectivity that works for arbitrary modalities (though only for code-right), but I haven't tried to implement that yet.

Generalized Blakers-Massey and Freudenthal

---

theories/HIT/Truncations.v
theories/Homotopy/HomotopyGroup.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Pointed/pMap.v

While reviewing #1086 I noticed that a fair number of funext and univalence assumptions in the Pointed library could be eliminated -- some completely, others by rephrasing theorems in terms of pointed equivalences rather than equalities of pointed types (which are generally more useful to have defined directly anyway -- it produces fewer univalence redexes).
Whichever of this or #1086 is merged second will probably require rebasing onto the other.

Remove some unnecessary funext and univalence, esp. in Pointed

---

theories/Basics/Overture.v

Back in #904 we wanted sigma notations defined recursively but they weren't available. Now that we have coq/coq#834  and coq/coq#6032 has been closed we can add this.
I want to also think about defining issig for any number of arguments.
@JasonGross Do you have any idea how to do this?

added recursive notation for sigma

---

_CoqProject
theories/Extensions.v
theories/Factorization.v
theories/HoTT.v
theories/Idempotents.v
theories/PathAny.v
theories/Pointed/Core.v
theories/Pointed/pMap.v
theories/Types/Paths.v

Wow!  I just learned this from Egbert.  Those gigantic transport calculations using obscure lemmas in `Factorization` and `Idempotent`?  Gone!  Also solves #1111 .

New, much easier algorithm for characterizing path types

---

_CoqProject
contrib/HoTTBook.v
contrib/HoTTBookExercises.v
theories/Algebra/Aut.v
theories/Algebra/ooGroup.v
theories/Basics/PathGroupoids.v
theories/Categories/Structure/Core.v
theories/Classes/interfaces/ua_algebra.v
theories/Classes/theory/premetric.v
theories/Classes/theory/rationals.v
theories/Colimits/Pushout.v
theories/Colimits/Quotient.v
theories/HIT/Circle.v
theories/HIT/Coeq.v
theories/HIT/V.v
theories/HIT/iso.v
theories/HIT/quotient.v
theories/HSet.v
theories/Homotopy/Join.v
theories/Spaces/Finite.v
theories/Spaces/No/Core.v

Here is a start at cleaning up quotient.v. I have added a new file Colimits/Quotient.v for the new quotient.
I have left two quotients for now for reasons discussed in #1103.
I haven't managed to change the uses of quotient in hottclasses to the new one but @SkySkimmer said he could do that.
I also couldn't change the use of quotient in V.v due to universes getting too complicated.
This closes #1103, closes #1088.
This can be merged for now but we will need to change the use of quotient.v in hottclasses and V.v, after which we can remove the old quotient.v.
Please let me know how you like the new names, I am happy to change any with discussion.
Edit: I should also add that I had an attempt at adding universe annotation to Coeq.v, Pushout.v and Quotient.v. Not 100% convinced that these are …

Cleaned up quotient

---

theories/Cubical/DPath.v
theories/Cubical/DSquare.v

Added a few changes to the cubical library:
* Added a degenerate dependent square ds_G1
* Added a truncation instance for dependent paths
* Added an alternative version of dp_apD_const and showed dp_const preserves path concatenation turning it into dependent path concatenation.

Added some lemmas to the cubical library

---

theories/Basics/Notations.v
theories/Basics/Trunc.v
theories/Homotopy/Suspension.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/pSusp.v
theories/Pointed/pTrunc.v
theories/TruncType.v
theories/Truncations/Connectedness.v
theories/Truncations/Core.v

Here are various truncation lemmas, they mostly come from my EM spaces development. Instead of shoving them all in that PR I will give them their own PR.
I will start with the small changes:
1. Connectedness of suspension added into Homotopy/Suspension.v. Peter Lumsdaine gave a proof of this in the old Freudenthal.v file. I included the proof here, which uses the wedge connectivity lemma.
2. Added `psusp_2functor`, `pequiv_psusp_functor` to Pointed/pSusp.v. Also added two corollaries of the Freudenthal suspension theorem:
- The map `loop_susp_unit` is 2n-connected.
- We have that Tr 2n X <~> Tr 2n (loops susp X)
3. Added a more general connected predecessor lemma to Truncation/Connectedness.v stating that if a type is (n+2+m)-connected then it is m-connected.
4. Added the equivalence …

Various truncation lemmas

---

theories/Algebra/AbelianGroup.v
theories/Algebra/Group.v
theories/Cubical/DPath.v

Here we prove that under univalence, the type of group isomorphisms between two groups G and H are equivalent to the path type between groups G and H.
I have also characterized "DPaths of sigma types as sigma types of DPaths".
The proof is long because it requires unpacking various parts of a largely nested sigma type and rearranging data to strip down the equivalence. No doubt there is a slicker method to do this.

Group iso is equivalent to path of groups

---

INSTALL.md
etc/install_coq_deps.sh

Since no one who actually uses OSX seems interested in updating the INSTALL file, I attempted to do it myself based on others comments.  Maybe someone who uses OSX can at least test the instructions as I've written them and see whether they work?
I wasn't sure where camlp5 should be installed; does it also come from opam or from brew?  And for the Linux instructions, should we alter `etc/install_coq_deps.sh` to not deal with ocaml/camlp5 and leave them to the user to do with opam, or should we make it call opam itself?  In fact, could we also create a version of `install_coq_deps.sh` for OSX?
I also got fed up with trying to maintain two separate "simplified" and "detailed" sets of instructions, which were highly redundant and at times conflicting, and merged them into one set of …

update INSTALL.md, close #929 and #1021

---

STYLE.md

Since we are changing the rules for approval of pull requests, I think *this* pull request should be approved under the old system of two pairs of eyes (or more).

Reduce approval requirements in STYLE.md, close #1166

---

theories/Homotopy/Join.v

This relies on #1149, check the last two commits to review.
In this PR we have the join bifunctor defined in the obvious way. We also have some "diamond lemmas". These are lemmas about squares whose edges comprise of jglues. These lemmas will be used in the Cayley-Dickson construction to come.

Diamond lemmas for join and join bifunctor

---

theories/Limits/Pullback.v

Working towards 3x3 for pullbacks, we need the following lemmas.
The first is a way to construct equivalences of pullbacks out of equivalences on the types in the cospan together with 2 commutative squares. i.e. sticking equivalences into functor_pullback gives you an equivalence.
The second is similar to a lemma Mike formalized for pushouts, though this one is more general since it allows us to characterize the pullback of functor_pullback completely.

Equivalences of pullbacks and sigma types of pullbacks

---

_CoqProject
theories/Algebra/AbelianGroup.v
theories/Algebra/Group.v
theories/Classes/interfaces/canonical_names.v
theories/HoTT.v
theories/Homotopy/ClassifyingSpace.v

This relies on #1147, therefore only check the last commit for review.
Changes:
* Added (1-truncated) classifying space of type with operation HIT using private inductive types.
* Defined classifying space of a group.
* Showed that loop space of BG is equivalent to G.
* Some extra properties of abelianizations
Eventually we should replace this private inductive type and construct BG out of coequalizers.

Classifying spaces

---

Makefile.am
configure.ac
hoq-config.in
hoqidetop

The [vscoq](https://github.com/coq-community/vscoq) extension uses coqidetop.opt, so let's create a shim for this.

[hoqidetop] Create a shim for coqidetop

---

_CoqProject
theories/Cubical/DPath.v
theories/Cubical/Square.v
theories/HIT/Spheres.v
theories/Homotopy/HSpaceS1.v

This relies on #1150 and #1147. See the last 5 commits to review.
Here's what I've done:
* Show that `Sphere 1` is 1-truncated
* Show that `Sphere n.+1` is n-connected
* Stop spheres from unfolding, closes #1018 
* Corrected istrunc for DPath's, and added the default dpath between any families of hprops connected by a path in the base space.
* Shown that a square type in a n.+2 truncated type is n-truncated.
* Shown that S1 has a H-space structure which is associative and commutative.

Various facts about spheres and H-space on S1

---

_CoqProject
theories/Basics/Notations.v
theories/Basics/Overture.v
theories/Categories.v
theories/HoTT.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Pointed/pFiber.v
theories/Pointed/pType.v
theories/WildCat.v
theories/WildCat/Core.v
theories/WildCat/EmptyCat.v
theories/WildCat/Equiv.v
theories/WildCat/FunctorCat.v
theories/WildCat/Induced.v
theories/WildCat/Opposite.v
theories/WildCat/Prod.v
theories/WildCat/Sum.v
theories/WildCat/Type.v
theories/WildCat/UnitCat.v
theories/WildCat/Yoneda.v

This is joint work with @alizter, @emilyriehl, @mpopie, and @tslilc who visited last week.  It's building on the basic approach of #1163, but reorganized and renamed a bit.  In particular:
- We realized that wild categories allow reusing the basic definitions at different dimensions in an enriched style.  This is quite satisfying!
- The terminology is now more coherent, roughly matching the standard higher-categorical notion of (n,r)-category (made wild).
- We got rid of the duplicate data for opposites again; we can consider putting it back, but the issue is that we also want to use this as the basis for a definition of bicategory, potentially even tricategory, etc., and if extra data is hanging around then it would need extra coherence laws.  It also becomes a problem when trying to …

Basics of wild 1-categories

---

theories/Algebra/Group.v
theories/Classes/theory/groups.v
theories/Homotopy/HomotopyGroup.v

For work in progress, I need to reason about these proofs, so avoid rewrites.
Also, some of these results were reproved elsewhere, so make them into Global Instances.  This sometimes causes `serapply BuildGroupHomomorphism` to spin, so you need to either add `notypeclasses` or provide the map.

Avoid rewrites in *_morphism proofs; make into Global Instances

---

theories/Algebra/Group.v
theories/Factorization.v
theories/Idempotents.v
theories/PathAny.v
theories/Pointed/pMap.v

The `eqp_issig_contr` tactic for characterizing identity types can be replaced by a lemma.  The advantages of this are that the type of the lemma provides clear documentation for what it can do, and the lemma only needs to be proved once, instead of each time the tactic is used.  I also split out part of the functionality into another lemma which might be of independent use.  All the uses of the old tactic have been converted to the new lemma, just by adding a `revert` and an `apply`.

Replace eqp_issig_contr tactic with a lemma

---

theories/Types/Universe.v

For some reason, with the current proofs of `contr_basedequiv` and `contr_basedequiv'`, the following cause Coq to spin:
```
Compute (center {Y : Type & nat <~> Y}).
Compute (center {Y : Type & Y <~> nat}).
Compute (@center {Y : Type & nat <~> Y} (@contr_basedequiv nat)).
Compute (@center {Y : Type & Y <~> nat} (@contr_basedequiv' nat)).
```
So I replaced their proofs with proofs that give explicit centers.

Make center of contr_basedequiv compute

---

theories/Basics/Overture.v
theories/Types/Forall.v

I needed `equiv_path_forall2`, and it seemed slightly easier to define this directly and then define `path_forall2` using it compared to showing that the existing definition of `path_forall2` is an equivalence.  As a result, `path_forall2` moves from Overture to Forall.
If this is a problem, I can do it the other way.  `path_forall2` isn't used anywhere in the library, but others might use it.
Another question:  I had to remove `{_}` and `_` from the `Global Arguments path_forall2` line.  Not sure why they were there.  The `{_}` was probably for `Funext` which is now in the context.  Not sure about the trailing `_`.  `_ _` would make more sense.

Add equiv_path_forall2 and define path_forall2 using it

---

theories/Algebra/Group.v
theories/Classes/theory/groups.v
theories/Homotopy/HomotopyGroup.v

These cause typeclass loops in many other places in the spectral sequences development where there is more algebra, so I think it's better not to have them as instances.  In `grp_homo_compose` it was enough to pose `compose_sg_morphism` as a hint.  (I don't understand why `grp_iso_inverse` still works without any such hint.)

remove global compose and invers for semigrop and monoid morphisms

---

README.md

A HoTT library was present in Lean2, but there is none for Lean3 in
active development. While at it, also point to the experimental Cubical
Agda, which started with Mortberg's cubicaltt work.

[README] Update link to HoTT in Lean

---

_CoqProject
theories/Classes/interfaces/canonical_names.v
theories/Homotopy/CayleyDickson.v
theories/Homotopy/Suspension.v

This relies on #1150, check the last 2 commits to review.
Here is the Cayley-Dickson construction as described in Rijke-Buchholtz. This gives a H-space on `Join (Sphere 1) (Sphere 1)` when combined with #1151, but we need join associativity to prove that this is `S3`. We could probably prove join associativity directly, there is an "easier" proof with the 3x3 lemma but we don't have this yet.
I'll come back and add some stuff to this later, such as moving some type classes to canonical_names.v and adding the S3 H-space exercise solution to HoTTBookExcersises.

Cayley-Dickson (from Rijke-Buchholtz)

---

contrib/HoTTBook.v
theories/Basics/Equivalences.v
theories/Basics/PathGroupoids.v
theories/Classes/interfaces/ua_algebra.v
theories/Classes/theory/groups.v
theories/Types/Paths.v

The first commit only moves code around, with _no changes_, except that I needed to remove the "Paths." prefix in a few other places to make the library compile.  The purpose of the move is to have `isequiv_ap` available when proving `other_adj`.
The second commit replaces the long proof of `other_adj` with a short proof that has no rewrites.
It's better to focus on the second commit to see what changed.
If I change the `Qed` at the end of `other_adj` to a `Defined`, then coq spins while checking Card.v.  The problem is in the call to `strip_truncations` in the `reduce` tactic during the proof of `exp_zero_card`.  It would be nice to make `other_adj` transparent, but if it's tricky to fix Card.v, then I'm happy with having this merged as is for now.

Simplify proof of other_adj in Equivalences.v

---

theories/Limits/Pullback.v
theories/Modalities/Modality.v
theories/Modalities/ReflectiveSubuniverse.v

The proof that a sigma-closed reflective subuniverse is a modality:
1. is now actually accepted by Coq, due to a more careful management of universe parameters;
2. goes by way of a "local" version pertaining to eliminating into a particular type family whose sigma-type belongs to the subuniverse, as in CORS Proposition 2.8; and
3. the latter is enhanced to an equivalence, as in CORS, but stated without funext in terms of `ooExtendableAlong` as in the rest of the modalities library.

From sigma-closure to modalities, improved

---

theories/Basics/Equivalences.v

Using revgoals had a nice side-effect:  by using "1: " instead of bullets, throughout the proof you can see the next goal you'll work on at the top and the final goal at the bottom, and it's a single step to flip between each state.  I also added some comments which help explain what's going on, since the type of the paths isn't obvious.

Use revgoals in eisadj_other, and add more comments

---

contrib/HoTTBook.v
theories/Extensions.v
theories/PathAny.v

Update Extensions.v to work with this, which simplifies the proof there.
Also note that this is part of Theorem 5.8.2 in HoTTBook.v
The based version specializes to the previous unbased version, but there are situations where the based version can be used directly and the unbased version can't.

Change equiv_path_from_contr to work with based path types

---

contrib/HoTTBook.v
theories/Fibrations.v

Is it worth having this iff statement explicitly when the two halves are already in the library?  I got confused and had trouble finding the pieces, which is why I'm proposing adding it.  An alternative would be to change HoTTBook.v to refer to both implications.  (Before this commit, it only pointed to one of the two implications.)

Add Theorem 4.7.7 explicitly

---

theories/Cubical/DPath.v
theories/Cubical/DPathCube.v
theories/Cubical/DPathSquare.v
theories/Cubical/PathCube.v
theories/Cubical/PathSquare.v

In addition to some fairly simple stuff and cosmetic changes, this:
- Defines the dependent Kan operations for `DPathSquare` and `DPathCube`
- Changes the proof of `sq_path` to one that was easier for me to reason about, enabling me to prove a dependent version `equiv_ds_dpath`
- Reverses the direction of `dp_compose` to match other lemmas like `ap_compose` in which the composition is in the domain.

Some more cubical stuff

---

_CoqProject
theories/Algebra/Group.v
theories/Pointed/pType.v
theories/WildCat.v
theories/WildCat/Core.v
theories/WildCat/EmptyCat.v
theories/WildCat/Equiv.v
theories/WildCat/Forall.v
theories/WildCat/FunctorCat.v
theories/WildCat/Induced.v
theories/WildCat/NatTrans.v
theories/WildCat/Opposite.v
theories/WildCat/Prod.v
theories/WildCat/Sum.v
theories/WildCat/TwoOneCat.v
theories/WildCat/Type.v
theories/WildCat/UnitCat.v
theories/WildCat/Yoneda.v

Some more stuff from the wildcat branch that I think we can merge into master:
- Switch to whiskering as a basic operation
- Groups form a category
- Initial and terminal objects
- indexed product of categories (`forall` of categories over types)
- Separate `NatTrans` and `TwoOneCat` into their own files
I did not merge `WildCat/Square` for now, which required changing the natural transformation proofs back to using ordinary 2-cells.

More wild category stuff

---

_CoqProject
theories/WildCat.v
theories/WildCat/EquivGpd.v
theories/WildCat/Paths.v
theories/WildCat/Sigma.v

Eventually we'll probably want equivalences of more general kinds of wild categories, which will use HasEquivs.  But 0-groupoids are a start (and already useful).
(This isn't on the wildcat branch yet.)

Equivalences and split-eso functors of 0-groupoids

---

_CoqProject
theories/WildCat.v
theories/WildCat/Paths.v
theories/WildCat/Sigma.v

I thought we had path-groupoids already, but I couldn't find them.  Maybe we just talked about it but didn't do it?
I know @mpopie worked on sigma-types during the wild categories week, but I think maybe it never got committed?  (And perhaps was discarded as eventually becoming an instance of displayed categories.)  I needed just the basic facts about them for an upcoming PR, and I think the definitions have changed, so I figured it was easier to reprove them.

Path-groupoids and sigma-types as wild categories

---

theories/Basics/Equivalences.v
theories/Colimits/Pushout.v
theories/Cubical/DPath.v
theories/Cubical/DPathSquare.v
theories/Extensions.v
theories/Homotopy/Suspension.v
theories/Pointed/pSusp.v
theories/Spaces/Torus/TorusEquivCircles.v
theories/Types/Forall.v
theories/Types/Prod.v
theories/WildCat/Forall.v

On top of #1205; see last 3 commits only (or wait to review until that's merged).
It's perhaps a bit of a stretch to say that this is an application of wild categories, when it's only using wild 0-groupoids that are just setoids, but I think the wild-category-theoretic perspective is helpful.
I need this right now just for separated localizations, but I expect it may be useful in Pointed too, e.g. using the `pForall` in the wildcat branch.

The universal property of suspension, without funext

---

theories/Modalities/Closed.v
theories/Modalities/Identity.v
theories/Modalities/Localization.v
theories/Modalities/Modality.v
theories/Modalities/Nullification.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Truncations/Core.v

On top of #1207, see last commit only.  This defines RSUs of separated types and proves some results from section 2 of CORS.  For universe reasons I had to define "being the separated subuniverse" as a relation between two RSUs rather than an operation on them, and include it in the definition of a family of RSUs, which in turn meant that in order to prove anything about them I had to characterize them for all our examples, including localization; hence #1207.  The most interesting stuff here is the proofs from CORS in `ReflectiveSubuniverse.v`; thanks to @jdchristensen for helping me correct and simplify the proof of 2.26 in particular.

Separated subuniverses

---

theories/Basics/Contractible.v
theories/DProp.v
theories/EquivalenceVarieties.v
theories/Fibrations.v
theories/FunextVarieties.v
theories/Homotopy/BlakersMassey.v
theories/Idempotents.v
theories/Limits/Pullback.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/pFiber.v
theories/Pointed/pSusp.v
theories/Types/Sigma.v
theories/UnivalenceVarieties.v

I finally realized that the reason Coq is often unable to guess the type family `Q` in `equiv_sigma_assoc` is that its domain is a sigma-type.  Defining a variant `equiv_sigma_assoc'` in which `Q` is instead a curried function of two (dependent) variables seems to remove the need to ever give it explicit arguments.  (Indeed, I'm tempted to make `P` and `Q` globally implicit arguments to both of them, but I didn't go that far yet.)
I also realized that the reason Coq is sometimes unable to find `contr_basedpaths` by typeclass inference is that it's looking at an eta-short form `sig (@paths A x)` which it's unable to unify with `{y:A & x = y}` since the latter is a notation for the eta-long form `sig (fun y => @paths A x y)`.  (I believe that when Coq displays `{y:_ & x = y}` it means it …

Make equiv_sigma_assoc and contr_basedpaths easier to use

---

theories/Algebra/Aut.v
theories/Categories/Category/Sigma/Univalent.v
theories/Constant.v
theories/EquivalenceVarieties.v
theories/Extensions.v
theories/Fibrations.v
theories/HIT/FreeIntQuotient.v
theories/Homotopy/BlakersMassey.v
theories/Idempotents.v
theories/Limits/Pullback.v
theories/Modalities/Lex.v
theories/Modalities/Modality.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Pointed/pMap.v
theories/Pointed/pSusp.v
theories/PropResizing/Nat.v
theories/Spaces/BAut.v
theories/Spaces/BAut/Bool/IncoherentIdempotent.v
theories/Spaces/Finite.v
theories/Types/Equiv.v
theories/Types/Forall.v
theories/Types/Sigma.v
theories/Types/Sum.v

`equiv_functor_sigma_id` and its friends, used appropriately, can eliminate a lot more explicit type family arguments.

More systematic use of equiv_functor variants with identity equivalences

---

theories/Basics/Overture.v
theories/Basics/Trunc.v
theories/Categories/GroupoidCategory/Dual.v
theories/Pointed/Loops.v
theories/Pointed/pTrunc.v
theories/Spectra/Spectrum.v

1st commit:
Trunc.v: rewrite trunc_index_inc so `trunc_index_inc minus_two.+2 n` definitionally agrees with `nat_to_trunc_index n`.
Trunc.v: add `trunc_index_inc'` which inserts the successors in a different order.
Loops.v: Replace only use of `nat_to_trunc_index_2` with `trunc_index_inc`.
pTrunc.v: Use `trunc_index_inc'` instead of `+2+` to eliminate rewrites in `ptr_iterated_loops`.
Spectrum.v: use new argument order for `trunc_index_inc`.
2nd commit:
Loops.v: Add `isconnected_iterated_loops_functor`, using `trunc_index_inc'`.

Trunc index inc

---

.gitignore

When using VSCoq, there are certain project-specific settings that are
nice to have.

[.gitignore] Ignore .vscode/

---

theories/HIT/Coeq.v
theories/Homotopy/BlakersMassey.v
theories/Modalities/ReflectiveSubuniverse.v

This allows us to prove `isequiv_O_coeq_cmp` without rewrites.
But the proof of `equiv_O_pushout_to_O_pushl` gets stuck.  See the comments there.  Any ideas what's going on?
This PR includes the universal property of coequalizers, from #1245 .

Add O_inverts_functor_coeq

---

theories/Pointed/pTrunc.v

I thought I needed this for something, but didn't in the end.  Still, it seems useful to record it, as it says that `loops_functor ptr` is equivalent to a different truncation map `ptr`.

Add ptr_loops_commutes

---

theories/Extensions.v
theories/Modalities/ReflectiveSubuniverse.v

In this case, the direct approach with funext-free yoneda is quite easy.

Prove O_inverts_sum without funext

---

theories/Algebra/Group.v
theories/Basics/Notations.v
theories/Homotopy/Suspension.v
theories/Pointed.v
theories/Pointed/pType.v
theories/WildCat/Core.v
theories/WildCat/EmptyCat.v
theories/WildCat/Equiv.v
theories/WildCat/EquivGpd.v
theories/WildCat/Forall.v
theories/WildCat/FunctorCat.v
theories/WildCat/Induced.v
theories/WildCat/NatTrans.v
theories/WildCat/Opposite.v
theories/WildCat/Paths.v
theories/WildCat/Prod.v
theories/WildCat/Sigma.v
theories/WildCat/Sum.v
theories/WildCat/Type.v
theories/WildCat/UnitCat.v
theories/WildCat/Yoneda.v

The original definition of wild categories had the underlying directed graph as a field of the typeclass rather than a parameter.  This was kind of a kludge -- I was pretty sure even at the time that it ought to be a parameter, but the graph typeclass was introduced while other people were working on various stuff downstream and we didn't want to change the foundations too much.  Recently @Alizter went back and made IsGraph into a parameter the way it should be in the wildcat branch; this PR imports that change back into master.

Import IsGraph-as-a-parameter from wildcat branch

---

autogen.sh
etc/install_coq.sh

The `git worktree` command allows to have several working trees for a
single repository.  The additional working trees then get a _file_
`.git` containing the gitdir, rather than a full `.git` directory.  In
order to support this, the build files should additionally allow
`.git` to be a file rather than a directory.

Allow compilation in a multiple git working trees

---

_CoqProject
theories/Colimits/MappingCylinder.v
theories/Cubical/DPath.v
theories/Cubical/DPathSquare.v
theories/Cubical/PathSquare.v
theories/Extensions.v
theories/HIT/Coeq.v
theories/HoTT.v
theories/Homotopy/BlakersMassey.v
theories/Modalities/ReflectiveSubuniverse.v

This is on top of #1246; review the last two commits.
I found a way to do it directly with extendability, analogously to the proof for sums, without using wild categories at all.  It's a neat trick that I'm surprised never occurred to me before: just as we can make _sections_ commute definitionally by using dependent types, i.e. fibrations, we can make _extensions_ commute definitionally by using cofibrations.  Book HoTT doesn't have a way to talk internally about cofibrations the way it can about fibrations, but we can still replace any map by one that is a cofibration, namely its mapping cylinder, and make use of the definitional behavior of the latter.  This gives a way to make a bunch of squares commute strictly, and with a bit of cubical technology added the path algebra becomes …

O_inverts_functor_coeq without funext, closes #1259

---

theories/Colimits/Pushout.v
theories/Extensions.v
theories/Homotopy/BlakersMassey.v
theories/Modalities/Descent.v
theories/Modalities/ReflectiveSubuniverse.v

One commit on top of #1264.  Using extendability more systematically simplifies the proofs that reflectors preserve products and pushouts and invert connected maps, and implies that colimits preserve connected maps (with enhancements for separated pairs of subuniverses).
It would also simplify the proof of `equiv_O_sigma_O`, but unfortunately the simpler proof of that has worse computational behavior, and we rely on its computational behavior in several places.  We could change those places to reason differently, but it's probably better to keep the good computational behavior and just note that the inverse is definitionally the same as what the simple proof would give.  To emphasize this, I changed the inverse to be syntactically the same as well, which required some trivial changes in a …

Applications of extensions to connected maps and preservation of colimits

---

contrib/HoTTBookExercises.v
theories/Basics/Equivalences.v
theories/Constant.v
theories/Extensions.v
theories/Factorization.v
theories/FunextVarieties.v
theories/HoTT.v
theories/Idempotents.v
theories/Modalities/Topological.v
theories/PathAny.v
theories/Pointed/pMap.v
theories/Types/Equiv.v

On top of #1271.  The only remaining imports of `FunextVarieties` are in the other metatheory files `TruncImpliesFunext` and `IntervalImpliesFunext`, which need `Funext_type`.

Move contr_basedhomotopy out of FunextVarieties, reducing the need to import it

---

theories/Spaces/Finite.v

Given a finite sequence of bits, if the first bit is 1 and the last bit is 0, then there is a point where the sequence swaps from 1 to 0. This proves that.

Implement a 1-dimensional Sperner's lemma

---

theories/Basics/Overture.v
theories/EquivalenceVarieties.v
theories/Extensions.v
theories/Factorization.v
theories/Modalities/Accessible.v
theories/Modalities/Fracture.v
theories/Modalities/Lex.v
theories/Modalities/Modality.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Spectra/Spectrum.v
theories/Tactics/BinderApply.v

While I was at it, I removed a bunch of unnecessary imports of `HoTT.Tactics`.  Currently the tactics therein are only used in `Categories`, three places in `Classes`, and one place in `Diagrams/Diagram.v`.

Add some tactics from the stdlib to Overture

---

contrib/HoTTBookExercises.v
theories/Algebra/Group.v
theories/Basics/Contractible.v
theories/Basics/Equivalences.v
theories/Basics/Trunc.v
theories/Classes/theory/rationals.v
theories/Extensions.v
theories/HIT/surjective_factor.v
theories/Homotopy/Join.v
theories/Pointed/pMap.v
theories/Pointed/pType.v
theories/Spaces/BAut/Rigid.v
theories/Spaces/Card.v
theories/Truncations/Core.v
theories/Types/Equiv.v
theories/Types/Sigma.v

I still don't entirely understand everything that's going on, but it seems to work for now.
Making `contr_equiv` transparent caused a blowup on a `cbn` in `Spaces/Universe`, which I tracked down to Coq spending a long time looking for the center of `contr_baut_rigid`.  Using `contr_change_center`, as Dan suggested in #1271, to give the obvious center explicitly fixed that.
Making `trunc_equiv` also transparent caused, as Ali noted in #1091, a blowup in `Spaces/Card` -- not on `strip_truncations`, but on another `cbn`.  I'm not sure exactly why, but looking at the proof term I saw that Coq was unnecessarily passing back and forth between `IsTrunc n` and `In (Tr n)` (e.g. deducing truncatedness of `Unit` from `inO_unit`), so I tried to increase the cost of the hint `istrunc_inO_tr` to …

Make contr_equiv and trunc_equiv transparent; close #1091

---

theories/Algebra/AbelianGroup.v

Replace the last five lines of `Abel_ind_beta_ab_comm` with `apply concat_V_pp`.
Get rid of `Section Abelianization`, since closing it was a bit slow.
Speed up use of `Abel_ind_hprop` with a tactic of the same name.  Adds up to a big savings.

Speed improvements to AbelianGroup.v:

---

theories/Basics/Equivalences.v
theories/Basics/Overture.v
theories/Basics/PathGroupoids.v
theories/Fibrations.v
theories/Homotopy/BlakersMassey.v
theories/Idempotents.v
theories/Limits/Pullback.v
theories/Modalities/Lex.v
theories/Modalities/Modality.v
theories/Pointed/pEquiv.v
theories/Pointed/pFiber.v
theories/Pointed/pSusp.v
theories/Types/Prod.v
theories/Types/Sigma.v

I'm making this a draft PR for now because I think we need to discuss how widely this tactic should be used.  For now, I tried using it almost everywhere I could find where it might conceivably be helpful, so we can see what it _could_ be used for.  I think some of those are clear wins, like `issig_pequiv'` and the lemmas in `Types/Prod` and `Types/Sigma`, but others are less clear.
Generally it seems that this tactic has to be prefixed with a `transitivity` stating exactly what you want the new sigma-type to look like, which is sometimes quite verbose.  Also, often what we want isn't exactly just a rearrangement of sigma-types, but also includes applying some other equivalence in the middle or at the top, often something like `equiv_path_sigma`, so this tactic is less helpful there than …

Tactic make_equiv for rearranging sigma and record types, close #1194

---

theories/Basics/Notations.v
theories/Cubical/DPath.v
theories/Cubical/PathCube.v
theories/Cubical/PathSquare.v

This closes #1265 and closes #1173. I have gotten rid of the notations `@h` and @v` for horizontal and vertical square concatenation. The notation `@lr` is kept since it is a rare string to type.

Reorganised Notations.v and moved cubical notations

---

theories/Pointed/Core.v
theories/Pointed/pEquiv.v
theories/Pointed/pHomotopy.v
theories/Pointed/pMap.v
theories/Pointed/pTrunc.v

Make a version of pointed_reduce without the rewrites, and use it in a bunch of places.  Also make a version that just handles a single map, to keep the context clean.  Give shorter default names for some of the destructed things, to make things more readable.
Unrelated, but also define the pointed type of pointed maps.

Make some proofs about pointed maps transparent.  Note X ->* Y is ptd.

---

theories/Algebra/ooGroup.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Pointed/pFiber.v
theories/Pointed/pHomotopy.v
theories/Pointed/pMap.v
theories/Pointed/pSusp.v
theories/Pointed/pTrunc.v

The pointed_reduce' tactic avoids rewrites, and in many cases works in place of pointed_reduce with little or no change.  Also, several results had unnecessary Funext hypotheses.

Use pointed_reduce' and remove Funext hyp where possible

---

theories/Homotopy/EMSpace.v
theories/Modalities/ReflectiveSubuniverse.v
theories/PropResizing/Nat.v
theories/Spaces/Finite.v

The Coq PR fixes #12571 which was observed in HoTT, according to some puzzled comments in the code. This PR should be backwards compatible.

Adapt w.r.t. coq/coq#12572.

---

theories/HoTT.v

Cf. #1345. This reverts fdedfe6, but was missed when restoring `EquivGroupoids` in #1344 .

Reinstate EquivGroupoids in export list HoTT.v

---

theories/Basics/Equivalences.v
theories/Basics/Overture.v
theories/Tests.v

There was a typo in the `reflexivity` tactic which caused universes to increase when proving an `Equiv` goal. Now `reflexivity` applies the reduced term just like `symmetry` and `transitivity` do.
closes #1356

fixed typo in reflexivity tactic causing universe increase

---

coq/theories/Arith/README.txt
coq/theories/Bool/README.txt
coq/theories/Classes/README.txt
coq/theories/FSets/README.txt
coq/theories/Lists/README.txt
coq/theories/Logic/README.txt
coq/theories/MSets/README.txt
coq/theories/NArith/README.txt
coq/theories/Numbers/README.txt
coq/theories/PArith/README.txt
coq/theories/QArith/README.txt
coq/theories/Reals/README.txt
coq/theories/Relations/README.txt
coq/theories/Setoids/README.txt
coq/theories/Sets/README.txt
coq/theories/Sorting/README.txt
coq/theories/Strings/README.txt
coq/theories/Structures/README.txt
coq/theories/Vectors/README.txt
coq/theories/Wellfounded/README.txt
coq/theories/ZArith/README.txt

These folders were kept since historically coq complained without them. This doesn't seem to be the case anymore.

removed unused folders in coq

---

_CoqProject
theories/Algebra/AbGroups.v
theories/Algebra/AbGroups/AbPullback.v
theories/Algebra/Groups.v
theories/Algebra/Groups/GrpPullback.v

Implements pullbacks of groups in [Groups/GrpPullback.v](https://github.com/jarlg/HoTT/blob/GrpPullback/theories/Algebra/Groups/GrpPullback.v) by equipping `Pullback f g` (from Limits/Pullback.v) with a group structure whenever `f`, `g` are group homomorphisms. If the groups involved are abelian, so is the pullback -- this is what [AbGroups/AbPullback.v](https://github.com/jarlg/HoTT/blob/GrpPullback/theories/Algebra/AbGroups/AbPullback.v) amounts to.
I'm unsure about which instances should be Global vs Local. Currently only the [Group instance for `Pullback f g`](https://github.com/jarlg/HoTT/blob/3eeee0b774f59343a14cd970ca7865f9d590e25f/theories/Algebra/Groups/GrpPullback.v#L91) is Global and the [two instances in AbPullback.v](https://github.com/jarlg/HoTT/blob/3eeee0b774f59343a14cd970c …

Define GrpPullback, AbPullback and prove corecursion principle

---

_CoqProject
theories/Algebra/AbGroups.v
theories/Algebra/AbGroups/AbPushout.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/QuotientGroup.v

Implements pushouts of abelian groups as quotients of the (bi)product in AbGroups/AbPushout.v. In order to do this, biproducts of abelian groups were added to AbGroups/AbelianGroup.v along with their recursion principle. The corecursion principle for `ab_biprod` is that of coproducts of groups (`grp_prod`), so this was added to Groups/Group.v.
Other minor things:
- Add the constant group homomorphism as `grp_homo_const` in Groups/Group.v.
- Add the negation automorphism of an abelian group as `ab_homo_negation` in AbGroups/AbelianGroup.v.
- The computation rule `grp_quotient_rec_beta` proved useful, so it was factored out of `equiv_grp_quotient_ump`.

Define ab_biprod, ab_pushout and prove recursion principles

---

theories/Diagrams/CommutativeSquares.v
theories/HFiber.v
theories/Limits/Pullback.v

In this PR we prove the pasting lemma for pullbacks in both directions. We also show that a commutative square is a pullback if and only if `functor_hfiber` is an equivalence.
closes #1012

Pasting for pullbacks

---

_CoqProject
theories/Basics/Notations.v
theories/WildCat.v
theories/WildCat/Square.v

Here is a small library of squares in a wildcat that was written by @fpvandoorn. Having a library like this quickly becomes essential, especially when you start composing commutative squares.
I've marked this PR as a draft since there are some things I would like to discuss first.
Firstly, I am not completely convinced with the naming conventions here. In Cubical/PathSquare I stuck to the convention `Square l r t b`. But here squares are instead `Square t b l r`. Since the former is a special case of the latter, we would eventually want some interaction between the structures. I believe having different conventions will be very confusing.
Which convention should we stick with?
Secondly, there are various definitions in this file that need better names.

Squares in wildcats

---

_CoqProject
theories/Homotopy/ExactSequence.v
theories/Pointed/pFiber.v

Here is a formalization of exact sequences written by @mikeshulman.
* We start off by defining when two (composable) pointed maps are a (very short) complex.
* We then construct the canonical map from the domain of the first map to the fiber of the second.
* Then various properties are shown to be preserved when various functors are applied to complexes.
* A definition of "n-exact" for any modality n (not just truncation index). A complex is considered n-exact when the canonical map from the domain of the first map to the fiber of the second is n-connected.
* Fiber sequences correspond to "oo-exact" sequences where oo is just the identity modality.
Importantly by the end of the file, LES of loops and homotopy groups are constructed. These are however exact as pointed sets rather than …

Exact sequences

---

_CoqProject
theories/Algebra/Groups.v
theories/Algebra/Groups/FreeGroup.v
theories/Algebra/Groups/FreeGroup/KrausAltenkirch.v
theories/Algebra/Groups/FreeGroup/ListQuotient.v
theories/Algebra/Groups/FreeGroup/LoopSusp.v
theories/Algebra/Groups/Group.v
theories/Algebra/ooGroup.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/EMSpace.v
theories/Homotopy/HomotopyGroup.v
theories/Pointed/pEquiv.v
theories/WildCat/Equiv.v

Here is a beginning on free groups. We add a new folder to Algebra/Groups called `FreeGroup`. This includes two files `KrausAltenkirch.v` and `LoopSusp.v`. These are two separate constructions of free groups which are defined in Group.v. The file Algebra/Groups/FreeGroup.v contains properties of free groups and exports KrausAltenkirch.v as the main implementation.
Here is a quick summary of the main file changes:
* `theories/Algebra/FreeGroup.v` contains properties of free groups (UP). Anybody wanting material on free groups would import this file or just Group.v which imports all group theory.
* `theories/Algebra/FreeGroup/KrausAltenkirch.v` contains a clever HIT for the free group on a type X. It is basically a quotient of the usual list construction, but with minimal constructors. This …

Free groups

---

theories/Homotopy/ExactSequence.v
theories/Truncations/Core.v

Hopefully it still makes sense. I've also replaced the terminology "oo-exact" with "purely-exact" but there is probably something better to say.
closes #1373

removed "oo" notation for purely

---

_CoqProject
contrib/HoTTBookExercises.v
theories/Basics/Trunc.v
theories/HSet.v
theories/HoTT.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Modalities/Separated.v
theories/Projective.v
theories/Spaces/Finite.v
theories/Spaces/Projective.v
theories/Truncations/Core.v

Co-authored-by: Dan Christensen <jdc@uwo.ca>
Defines projective types and characterizes them as types for which the axiom of choice holds, or alternatively types into which every epi (merely) splits. Under `AC_oo,-1` (in the sense of the HoTT Book, Exercise 7.8) projective types correspond to sets.
Questions:
- Is `Spaces/Projective.v` a good placement? `Types/Projective.v` didn't work out due to circular imports.
- Should the `AC_oo,neg1` section at the end of `Projectivity.v` be placed elsewhere? An alternative placement would be in `HSet.v`, in which case the definition of `choice` in `Projectivity.v` would need to be factored out into it's own file to avoid circular imports. (In this case, `Spaces/Finite.v` could also import this definition of choice, and `finite_choice` would …

Define and characterize projective types

---

theories/PropResizing/Nat.v

As a consequence, a clear on a residual dependent argument of an inductive type becomes useless. We leave a try so as to be backwards-compatible. You may prefer a clean non-compatible script though.
cf coq/coq#13513

With Coq PR #13513, "intros []" uses "destruct" rather than "case" and becomes "smarter".

---

_CoqProject
theories/Algebra/Groups.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/Kernel.v
theories/Algebra/Groups/ShortExactSequence.v
theories/Algebra/Groups/Subgroup.v
theories/Basics/Equivalences.v
theories/Classes/interfaces/abstract_algebra.v
theories/Homotopy/ExactSequence.v
theories/Modalities/Identity.v
theories/Pointed/pHomotopy.v
theories/Truncations/Core.v

The first commit characterises paths of subgroups as isomorphisms respecting the inclusions, and proves that the kernel of a group homomorphism is trivial if and only if it's an embedding. There was some related discussion at #1387, and I've opted to stick with the existing formalization of subgroups instead of developing a version using predicates. If there's an argument for switching, I'd like to know.
The second commit relates the above to (pure) exactness of a complex `0 -> A -> B` of groups in `equiv_grp_isexact_isembedding`.

Characterise paths of subgroups, relate to trivial kernels and exactness

---

theories/Modalities/Descent.v
theories/Modalities/Lex.v
theories/Modalities/ReflectiveSubuniverse.v

Now that the ABFJ paper [Higher Sheaves and Left-Exact Localizations of ∞-Topoi](https://arxiv.org/abs/2101.02791) is on the arXiv, we may as well include the synthetic version of their result in the library.  This isn't exactly their proof (although it was suggested to me by Eric), as it uses the universe whereas they avoided that by messing around with a bunch of ∞-colimits.  It's impressive how much shorter the proof is with a universe (and, of course, with all the other facts about modalities that we already have formalized).

Lex localizations (ABFJ)

---

Makefile.am
coq/theories/Init/Nat.v
coq/theories/Init/Number.v
coq/theories/Init/Prelude.v
theories/Basics/Trunc.v
theories/Spaces/Int/Core.v
theories/Spaces/Pos/Core.v

This should be backward compatible.

Adapt to coq/coq#13842

---

.gitignore

The `_build` directory is where dune puts built things, this can generate many files so it's good to ignore it

added _build/ to .gitignore

---

_CoqProject

This let's us build the library by doing the following:
```
coq_makefile -f _CoqProject -o CoqMakefile
make -f CoqMakefile
```
I've allowed for this since there are people in the coq platform who are interested in getting this to work this way.
Eventually we should replace our current makefile set up with this way, but our current makefile targets are super intertwined and the makefile does a lot more than build the library.
---
This also means that `coqide` should just work without needing any `./hoqide` etc.

modified _CoqProject so that it works with coq_makefile

---

_CoqProject

We are currently trying to make a coq platform release. In order to do this, we need to give a logical path to the contrib folder or else it gets installed weirdly.

Added logical path for contrib

---

theories/Basics/Notations.v
theories/Cubical/DPath.v
theories/Cubical/DPathSquare.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/Smash.v

changed '@D' notation to '@Dp'

---

theories/Basics/Tactics.v

These tactics used the old coq data structures which we no longer have.
Noticed when working on #1440

removed unnecessary clauses in tactics

---

theories/Algebra/AbGroups/AbPushout.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/Image.v
theories/Algebra/Groups/Kernel.v
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Groups/ShortExactSequence.v
theories/Algebra/Groups/Subgroup.v
theories/Algebra/Rings/Ideal.v
theories/Algebra/Rings/QuotientRing.v
theories/TruncType.v

This is a WIP attempt at switching to predicates for subgroups as discussed in #1387.
This should have a few advantages when it comes to formalization.
I've also implemented a basic hint database for groups, which can automate a lot of routine arguments that we had. With some more careful design we can make this a powerful and useful tool.
This should also resolve issues we were having with #1369 though I haven't been able to confirm this yet.
When it comes to actually constructing subgroups, the predicate approach is far more efficient. There is no need to construct another group and check that the inclusion map is a homomorphism, etc.

Predicate subgroups

---

contrib/HoTTBook.v
theories/Basics/Equivalences.v
theories/Basics/Overture.v
theories/Homotopy/ClassifyingSpace.v
theories/Spaces/Card.v

I've inlined the proof of `eisadj_other` as requested in #1282.
I've also gone ahead and made `eisadj` opaque. This will tell coq to delay unfolding it as long as possible when simplifying. This will stop equivalences from turning into super large terms. Note that marking a term as Opaque is different from being Qed, as Qed will never be unfolded.
Doing this unfortunately caused ClassifiyngSpace.v to blow up. I have therefore replaced a large simplification with a manual one which has saved quite bit of time.
```
After |  Peak Mem | File Name                                                    |   Before |  Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
------------------------------------------------------------------------------------------------------------------------ …
```

Removed eisadj_other + some optimizations

---

theories/Types/Forall.v

`equiv_apD10` had a redundant Funext argument, since Funext is also assumed in the Section.
`equiv_flip` doesn't need Funext at all, so end the section earlier.

Use less Funext in Types/Forall.v

---

Makefile.am

Discovered at https://github.com/coq/coq/pull/13952/checks?check_run_id=2370784127 / https://github.com/coq/coq/pull/13952.

Fix for the Makefile when the submodule is not present

---

theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/WhiteheadsPrinciple.v

It's probably best to review the two commits separately.
The first commit greatly improves the proof of pequiv_pclassifyingspace_pi1.
The new proof is broken into conceptual steps.  It's shorter overall, and much faster.
The second commit does some other minor cleanups and also speeds up a few things.
The hspace part of the file is untouched, and is still slow, but overall the file typechecks
in less than half the time.

Clean up and speed up ClassifyingSpace.v

---

theories/Homotopy/ClassifyingSpace.v

- Reverse the direction of the equivalence between ΩBG and G, so it
goes in the natural direction bloop : G -> ΩBG.  This makes several
things cleaner and allows us to drop encode_pp.
- Make IsEquiv bloop a Global Instance.
- Prove that it is natural.
- Remove many rewrites, especially in the H-space part.
Replace one entire proof by reflexivity.
- Use nrapply instead of rapply in some places.
The entire file now takes 2s to typecheck on my system.

More cleanups and speedups to ClassifyingSpace.v.

---

INSTALL.md

On my system, it needs a trailing slash.

Fix COQBIN in Install.md

---

theories/Basics/Equivalences.v

In #1475, @JasonGross noticed a `Let ... Qed`.  `Qed` leaves things transparent with `Let`, so this changes `Let` to `Definition` so that the `Qed` does what was intended.  The build time of the library is reduced by 3% (and BlakersMassey.v is twice as fast).
```
After |  Peak Mem | File Name                                                    |   Before |  Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
3m39.85s | 613024 ko | Total Time / Peak Mem                                        | 3m46.88s | 613240 ko || -0m07.02s ||      -216 ko |   -3.09% |         -0.03% …
```

Change Let to Definition in is_adjoint' so that Qed works.

---

Makefile.coq.local

Since we are not passing all .v files, we cannot use `-f _CoqProject` to
invoke coqdep.  Since we are not using `-f _CoqProject`, we must pass
all of the `COQLIBS` arguments, not just the ones that got passed on the
command line.

Fix generation of library dep graphs

---

theories/Pointed/Core.v

The old version would give an error if there was a `p` in the context.

Use a fresh variable in pointed_reduce_pmap

---

theories/Algebra/Groups/Group.v
theories/Basics/Equivalences.v
theories/Homotopy/BlakersMassey.v
theories/Homotopy/Suspension.v
theories/Limits/Pullback.v
theories/Modalities/Descent.v
theories/Modalities/Lex.v
theories/Spaces/Finite/Finite.v
theories/Truncations/Connectedness.v
theories/Truncations/Core.v
theories/Types/Universe.v

This makes them match `transport`.  Those args were only needed in one spot in the library, so I had to use the `@` notation there.  But many other places are simpler now.

Make x and y implicit args in (is)equiv_transport

---

theories/Types/Universe.v

This slight tweak to the proof reduces the number of universe levels required, for some reason.  In a downstream application, the old proof forced another universe strictly larger than the others.
The changes to `contr_basedequiv` and `contr_basedequiv'` are just "documentation" to the reader, since nothing in the statement forces those universes to be equal.  It only happens in the proof, implicitly.

Reduce universe levels in equiv_induction_inv and dependencies.

---

.github/workflows/ci.yml

I've updated the CI to use docker images (basically precompiled versions of coq). I've gotten rid of the old build jobs that use the submodule. We only leave the quickdoc, html, dpdgraph and validate together with alyectron.
Note that we are building the library on the following versions:
* Our current supported version 8.13
* The latest stable version of coq
* The dev version of coq
<s> I don't think it makes sense to try the dev version as that can be unstable.</s>
The advantage of doing things like this is that we can build the library in around 4min!
In the future, we want the build jobs to upload their image as an artifact so that the documentation jobs can work directly with that. Something similar was suggested by Jason in …

Update CI to use docker images

---

theories/Algebra/Aut.v
theories/Spaces/BAut.v
theories/Truncations/Connectedness.v

As noted by @Alizter [here](https://github.com/HoTT/HoTT/issues/1452#issuecomment-820810626), `BAut` has 19 universe variables. By proving connectedness more directly it is reduced to 3. This makes reasoning about the universe level of `BAut` easier, and resolved some unification errors I ran into when experimenting.

Reduce universes in BAut from 19 to 3.

---

theories/Factorization.v

Broken into two commits, as the second one moves code.  So it's best to view the two commits separately.
The first commit reduces the number of universes for Factorization and PathFactorization, reduces the use of Univalence, and simplifies the proofs of `cancelR_class1` and `cancelL_class2`.  It also makes the proofs of those dual to each other.
The second commit moves `contr_factor` outside of the Section, mainly so that the Univalence hypothesis comes first, but also because it doesn't benefit much from being in the Section.

Cleanups to Factorization.v

---

theories/Algebra/Universal/Operation.v
theories/Basics/Datatypes.v
theories/Basics/Nat.v
theories/Basics/Overture.v
theories/Basics/Tactics.v
theories/BoundedSearch.v
theories/Categories/ChainCategory.v
theories/Classes/implementations/ne_list.v
theories/Classes/implementations/peano_naturals.v
theories/Classes/interfaces/cauchy.v
theories/Colimits/Sequential.v
theories/Spaces/Finite/Fin.v
theories/Spaces/Finite/FinInduction.v
theories/Spaces/Finite/FinNat.v
theories/Spaces/Finite/FinSeq.v
theories/Spaces/Finite/Finite.v
theories/Spaces/Nat.v

<s>This PR is a WIP attempt at cleaning up the natural numbers library.
This PR isn't currently ready for review but was opened so I can get some help.
@andreaslyn a lot of my changes are breaking the FinNat and FinInduction library. Could you take a look? The last commit should contain the changes I tried, but I am unable to get some of the proofs to go through. Especially in FinInduction.v
When I finish this PR I will force push better commits then currently exist.</s>
---
OK, this is ready for review. Here is what has been done.
The organization has changed a bit:
* `nat` is now defined in `Overture.v`.
* There is a file `Basics/Nat.v` that contains very basic functions about `nat`. These are necessery to have since numeral notations (conversion between decimal, hexadecimal, TruncIndex …

Clean up natural number library

---

_CoqProject
theories/Algebra/Groups.v
theories/Algebra/Groups/Lagrange.v
theories/Algebra/Groups/QuotientGroup.v

It's a bit annoying that subgroups of finite groups cannot be shown to be finite in general. As I understand, if we could show them to be, then the subgroups would end up being decidable.
Of course, under LEM every subgroup becomes decidable, but I think this is an even more unreasonable assumption to carry around then just asking for a subgroup to be finite.

Lagrange's theorem

---

theories/Algebra/Groups/Lagrange.v

The changes in #1469 clashed with #1463. This should fix that.

Fixed Lagrange.v

---

theories/Limits/Pullback.v
theories/Modalities/Lex.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Modalities/Separated.v

In particular, a map is fiberwise in `Sep O` precisely when its diagonal is in `O`.  Also, `equiv_O_pullback` can be stated more simply since modal types are closed under pullbacks.

Some lemmas about subuniverses and diagonals

---

theories/Modalities/Lex.v

For a lex modality O and a type A, the following are equivalent:
- All (n+2)-fold iterated identity types of A are O-modal.
- The O-reflector A -> OA is an n-truncated map.

n-fold separation

---

contrib/HoTTBook.v
theories/Basics/Overture.v
theories/Homotopy/ExactSequence.v
theories/ObjectClassifier.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Spaces/BAut.v
theories/Truncations/Connectedness.v
theories/Types/Sigma.v
theories/Types/Universe.v

In the 1st commit, we expand `ObjectClassifier.v` to speak about pointed maps into the universe pointed at some type, and into `Type_ O` pointed at some `O`-local type. In particular, the former corresponds to the type of fiber sequences, which we may consider to be pointed (`equiv_sigma_pfibration`) or not (`equiv_sigma_fibration_p`).
In the 2nd commit, we view `X => merely (X <~> F)` as a subuniverse to deduce facts about maps into `BAut F` from the statements about `Type_ O` in `ObjectClassifier.v`. Both `pType` and `pForall` are made cumulative in order for `equiv_pequiv_postcompose` to work at the end of `BAut.v`.
_Question_: in `Truncations/Connectedness.v` we added `conn_to_trunc_ind`, with the naming indicating that this is an induction principle for (n+1)-connected types into …

Update ObjectClassifier.v and classify maps into BAut.

---

theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/GroupCoeq.v
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Groups/Subgroup.v
theories/Algebra/Rings/CRing.v
theories/Algebra/Rings/QuotientRing.v
theories/Algebra/Rings/Z.v
theories/Homotopy/Pi1S1.v
theories/WildCat/Equiv.v

This builds on top of #1495 so for the time being, I've marked it as draft.
Here is a summary of the changes:
* Add more ring laws
* Add `≅` notation for `CRingIsomorphism` as that was quickly getting tiresome to write. This notation lives in `ring_scope`. 
* Add another constructor for Rings that takes in the underlying abelian group.
* Image of a ring homomorphism as a ring together with inclusion maps
* Product ring
* Define powers of ring elements together with some basic laws
* Add in ring movement lemmas (for now only for addition) e.g. `rng_moveR_Mr : y = - x + z <~> x + y = z `

More ring theory, movement lemmas and cleanup

---

contrib/HoTTBookExercises.v
theories/Algebra/Universal/Congruence.v
theories/Algebra/Universal/TermAlgebra.v
theories/Colimits/Quotient/Choice.v
theories/HIT/quotient/choice.v
theories/Projective.v
theories/Spaces/Finite/Finite.v

I have parametrised `IsProjective` by a modality, which was suggested by @Alizter as a way to generalise over all truncation levels including infinity.
I have changed name of `IsProjective'` to `IsChoosable`, to avoid confusion with `IsProjective`.
I have moreover defined `IsQuotientChoosable`, equivalent to `(0,-1)-projective`, which I will need later on. Although I do not use it, I have included `choose_quotient_ind`, which generalises `quotient_rec2`. I think it is a nice recursion principle for `quotient`.

Parametrise IsProjective and IsQuotientChoosable

---

hott.opam

This lets us use `opam` to build and install the library from the source directory. This will be useful for the CI.

Added .opam file to library

---

theories/Algebra/AbGroups/AbPullback.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/AbGroups/Z.v
theories/Algebra/Rings/CRing.v
theories/Algebra/Rings/QuotientRing.v
theories/Algebra/Rings/Z.v

To prove things in #1534, we had to port lemmas from `Group` for working with equations in `AbGroup`. This can be resolved by coercing elements in `AbGroup` via the underlying `Group` instead of a direct coercion `AbGroup >-> Sortclass` (to the underlying type). However then it seems cleanest to simply define `AbGroup` as commutative groups, and we do this here.
(I definitely recommend split view for the diff!)

Redefine AbGroup to be commutative groups.

---

theories/Algebra/AbGroups/AbExt.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/ShortExactSequence.v
theories/Basics/Equivalences.v
theories/Basics/Overture.v
theories/Classes/interfaces/canonical_names.v
theories/Homotopy/ExactSequence.v
theories/Truncations/Connectedness.v
theories/Types/Sigma.v

The first commit adds facts about functoriality of `ab_biprod` and lemmas for working with equations in abelian groups, basically ported from groups. While this may seem redundant, I did not easily find a way to specialize the results for groups without breaking things (specifically `CRing`), and this solution was discussed with @Alizter.
The main content is the thrid commit, which defines a type `hExt` of abelian group extensions, characterises paths in `hExt` and proves that the trivial extensions are the split ones. Some of these results (e.g. characterisation of paths) could be done for all group extensions and then specialised for a type of abelian group extensions, however in general I don't think there's much commonality so it makes sense to define these types separately. A more …

Define hExt and characterise trivial extensions

---

theories/HoTT.v
theories/Modalities/Meet.v

The "plus-construction" for sheafification can be realized, by a change of ambient presheaf topos, as the successive application of two lex modalities.  I wrote this up categorically at <https://ncatlab.org/nlab/show/plus+construction+on+presheaves>.  This PR is a synthetic proof, inspired by the category-theoretic one of [Anel and Leena Subramaniam](https://arxiv.org/abs/2004.00731), that, assuming that the plus-construction directly sheafifies embeddings (this corresponds to the "local character" condition on a Grothendieck topology), the meet of two lex modalities can be computed on n-types by n+2 applications of the plus construction.

The synthetic plus construction for the meet of two lex modalities

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Idempotents.v
theories/Types/Sigma.v

By avoiding `symmetry` and `transitivity`, we get rid of two larger universes in `hfiber_functor_sigma`.  Only a couple of other places are affected by this.  This is useful for WIP where I'm tracking universe usage.

Reduce universe levels in hfiber_functor_sigma

---

etc/generate_coqproject.sh

In a git worktree, .git is a file, not a directory, so use -e instead of -d to test for it.

Use git ls-files in a worktree as well

---

theories/Modalities/Modality.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Projective.v
theories/Truncations/Core.v

As discussed in #1481
Perhaps it would be better to have a `strip_using` tactic where we provide an induction principle, than all three become special cases of that.
I also wonder why `strip_truncations` is so good at what it does. Replacing it in `Classes/implementations/HProp_lattice.v` for example breaks things. Projective.v also breaks.

strip_reflections, strip_modalities tactics

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Rings/CRing.v
theories/Algebra/Universal/Homomorphism.v
theories/Algebra/ooGroup.v
theories/Homotopy/ExactSequence.v
theories/Pointed/Core.v
theories/Pointed/pEquiv.v
theories/WildCat/Core.v
theories/WildCat/EmptyCat.v
theories/WildCat/Equiv.v
theories/WildCat/Forall.v
theories/WildCat/FunctorCat.v
theories/WildCat/Induced.v
theories/WildCat/NatTrans.v
theories/WildCat/Opposite.v
theories/WildCat/PointedCat.v
theories/WildCat/Prod.v
theories/WildCat/Sum.v
theories/WildCat/TwoOneCat.v
theories/WildCat/Type.v
theories/WildCat/UnitCat.v
theories/WildCat/Yoneda.v

I have gone ahead and split the cells data for wildcats as discussed in #1545. We now have the typeclasses `Is2Graph` and `Is3Graph`.
This also prompted me to go through the wildcat library and do a little cleanup. This included naming things properly etc. Unfortunately, there are example where coq isn't smart enough to guess things anymore. (Especially when mixing `->*` and `$->`). The solution is to probably try to stick to wildcat notation as much as possible.
This was much trickier than anticipated to carry out however. The completely unbundled approach to algebraic hierarchies is not very rigid with respect to changes lower down, and the number of underscores in the code has increased a bit. I can quickly see that this will get out of hand fast, so perhaps we need to bundle some …

Stratify cells in wildcat

---

theories/Classes/implementations/pointwise.v

Closes #1555.
The tactic `try_solve_fun` in Classes/implementations/pointwise.v was using proof search for things that are easy to do by hand.  In the past, this file took ~5s to type check, but this jumped to ~60s with commit 3a2973e, which added
```coq
Global Hint Unfold Commutative : typeclass_instances.
```
to Classes/interfaces/canonical_names.v.  By removing the automation, the compile time is reduced to ~0.5s, with the `Hint Unfold` still in place.

Speed up pointwise.v by removing try_solve_fun

---

theories/Classes/interfaces/canonical_names.v

The issue in #1555 would have been prevented if I'd made `Commutative` a transparent instance, instead of adding the more intrusive `Hint Unfold`. This is how I should have done it from the start, and should prevent similar issues in the future.
Edit: This saves ~4s, as can be seen here: https://gist.github.com/jarlg/5e75f9195ee9379f84fbb38f55d47653

Change Hint Unfold Commutative to Typeclasses Transparent.

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Rings/Z.v
theories/Algebra/ooGroup.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/HomotopyGroup.v
theories/Homotopy/WhiteheadsPrinciple.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pFiber.v
theories/Pointed/pMap.v
theories/Pointed/pSusp.v
theories/Pointed/pTrunc.v
theories/Spaces/Torus/TorusHomotopy.v
theories/Truncations/Core.v
theories/WildCat/Core.v
theories/WildCat/Equiv.v
theories/WildCat/PointedCat.v

Summary of changes:
* Changed many definitions/lemmas about `X_functor` to use the wildcat `fmap` instead. This is by no means comprehensive, but a good look at what can be done.
* Added various lemmas about initial and terminal objects.
* Added some theory of pointed functors (functors between pointed categories)
* Cleaned up a few proofs along the way.
* Finished proof that pType is univalent.
* Probably some others that I missed.
This work is culminating from another project I am working on.

Changing various functors to use fmap + misc wildcat additions

---

theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Groups/Subgroup.v
theories/Algebra/Rings.v
theories/Algebra/Rings/ChineseRemainder.v
theories/Algebra/Rings/Ideal.v
theories/Algebra/Rings/QuotientRing.v
theories/Basics/Utf8.v

This PR builds on top of #1496 and #1495.
Here is a summary of the PR:
The biggest changes are in Ideal.v which looks like it has been written from scratch:
* We begin with various lemmas about ring elements being in an ideal
* We define intersection ideals, sums of ideals, products of ideals
* We define the ideal generated by a family on a ring (different but analagous to the subgroup generated in #1495)
* We can define principal ideals (but not what it means to be principal yet)
* We define equality of ideals, which is just a family of "if and only if"'s
* We define subsets of ideals, i.e. a family of implications (this is our notion of "divded by" for ideals)
* Define the colon ideal
* Define the annihilator of an ideal
* We define some ideal (unicode) notations. These are convenient …

Ideal arithmetic and Chinese remainder theorem

---

theories/Colimits/Colimit.v
theories/Colimits/Colimit_Flattening.v

This gets rid of the axiomitized HIT definition of `Colimit` and replaces it with an implementation using coequalizers. Generally related to #1067. There is a slight performance hit in `Colimit_Flattening.v` but this is because the proof there isn't so great. Ideally, one would write a proof with not so many reduction tactics, but this will require some effort. I've done some minimal changes to the proof to get it to go through.

implement colimit as coequalizer

---

theories/Basics/Trunc.v
theories/Homotopy/EMSpace.v
theories/Pointed/pSusp.v
theories/Truncations/Connectedness.v
theories/Truncations/Core.v

Several places that deal with iterated truncations can be simplified.  In addition, the equivalence defined by `pequiv_loops_em_em` in EMSpace.v is now more direct, using one edge of a square instead of the composite of the other three.

Simplify various proofs involving iterated truncations

---

theories/Pointed/Core.v
theories/Pointed/Loops.v

Later there will be more typeclass instances floating around which makes these areas slower, therefore we optimize it slightly.

Small optimization for typeclass search.

---

theories/WildCat/FunctorCat.v
theories/WildCat/NatTrans.v
theories/WildCat/Opposite.v
theories/WildCat/Yoneda.v

There are various usability changes such as naming/order of arguments in this patch. Importantly the definition of `Transformation` was changed to be a dependent function, which would allow it to be used in a future definition of modification etc. Unfortunately this comes with a diamond in the coercion tree which isn't a problem on paper, but coq is not permissive enough. We disable to warning anyway to avoid spam every time the module is imported. It might be worth moving the disabling of the warning earlier in the library.

Various wildcat usability changes and changes to transformations

---

.github/workflows/ci.yml

`docutils` is a package that `sphinx` depends on. It was recently updated to 0.18 which broke `sphinx`. `sphinx` is the program that does the documentation for `alectryon`.
We manually pin the package version until sphinx gets updated.

pin docutils to 0.17.1

---

theories/Algebra/Rings/Z.v

HoTT was exploiting a weird multigoal behaviour of the exact tactic that was interleaving global evar resolution with goal filling. It is not clear that this can be qualified as a bug, but the net result is quite surprising and it's better for HoTT not to depend on it, especially if we merge coq/coq#15171.
This should be backwards compatible.

Adapt w.r.t. coq/coq#15171.

---

.gitmodules

The library has worked with Coq out-of-the-box for a while now. We can finally get rid of this.
If anybody is still using the submodule, please consult INSTALL.md on using opam for Coq.

Remove coq submodule

---

theories/Algebra/Groups/FreeGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/Presentation.v

Here is something fun that I have been working on. I've created a notation for group presentations allowing us to quickly write one down without having to do a lot of leg work. The new notation allows us to do things like:
```coq
Definition presentation_q16 : GroupPresentation :=
⟨ a , b | grp_pow a 8 , (grp_pow a 4) * -(grp_pow b 2) , a * b * a * -b ⟩.
```
Currently there is only support up to 3 generators, we can add more as needed. I haven't worked out how to get an arbitrary number of binders just yet.

Presentation notation

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/Groups/FreeGroup.v
theories/Algebra/Groups/FreeProduct.v
theories/Algebra/Groups/GroupCoeq.v
theories/Algebra/Groups/Presentation.v
theories/Colimits/Coeq.v
theories/Colimits/Colimit.v
theories/Colimits/Colimit_Coequalizer.v
theories/Colimits/GraphQuotient.v
theories/Colimits/MappingCylinder.v
theories/Colimits/Pushout.v
theories/Colimits/Quotient.v
theories/Extensions.v
theories/HIT/Flattening.v
theories/HIT/FreeIntQuotient.v
theories/HoTT.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Spaces/Circle.v

Here is a simpler definition of a coequalizer as a HIT. We then redefine Quotient and Coeq in terms of this. Working with the "untypetheoretic coequalizer" can be a bit awkward sometimes since you might have to pass a sigma type here and there. This mostly removes this requirement.
This is a step towards cleaning up the HIT folder.

Relation coequalizer

---

theories/Basics/Overture.v
theories/Basics/UniverseLevel.v
theories/Categories/Category/Morphisms.v
theories/Categories/NatCategory.v
theories/Classes/interfaces/canonical_names.v
theories/WildCat/Core.v
theories/WildCat/Opposite.v

The `Typeclasses Opaque`/`Transparent` commands now need locality attributes. I've defaulted to `#[global]` pretty much everywhere and that seems to work.

fix warnings

---

theories/Basics/Overture.v

This is a consequence of fixing a naming bug in coq/coq#15537. It now requires an explicit `rename` flag in the subsequent calls to `Arguments` for `paths` induction schemes.
A priori, I don't see other consequences of the naming fix (except on printing, where sometimes, especially in `return` clauses, `y` will be displayed `a`).
If ok with the change, this is backward-compatible and can be merged as soon as now.

Adapt to Coq PR #15537: schemes paths_rec & paths_ind have different automatically generated names

---

theories/Colimits/Sequential.v
theories/Diagrams/Cocone.v
theories/Homotopy/Join.v
theories/Metatheory/PropTrunc.v

While working on the full join construction, I thought that this would be a good addition to our metatheory folder. We define truncations as a private inductive type at the moment, but this shows that having coequalizers is enough.

propositional truncation via join construction

---

theories/Homotopy/Syllepsis.v

- The main speedup comes from factoring out a subterm of the goal of eh_V_p_pp_gen using a let binding.  The subterm appears four times in the goal.  The statement of this goal was the slowest step in the file.  This change speeds it up, and also speeds up the proof.
- The other let bindings in the goal were removed, since they only appeared once in the goal and slowed things down slightly.
- The induction steps in the proof were reordered, giving some more minor speedups.
- The proof of the corollary eh_V_p_pp was adjusted to speed it up a bit.
Altogether these take about 15% off the build time for the entire file, mostly due to the first change.

More speedups to Syllepsis.v

---

.github/workflows/ci.yml

We have dependency graphs for each file. A typo in the CI file caused these not to be uploaded to the ghpages website.

fix typo in ci causing file-dep-graphs to not be deployed

---

theories/Categories/Adjoint/Composition/Core.v
theories/Categories/Category/Morphisms.v

It has been deprecated in 8.16 (alpha) and has the behaviour of idtac. Therefore it can be safely removed.

Remove uses of instantiate (to fix some warnings)

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Basics/Overture.v
theories/Classes/interfaces/abstract_algebra.v

The main change here is to specify that `Contr_internal` is a `Cumulative Record`.  With this done, the following things work:
```
Definition test@{u v | u < v} (A : Type@{u}) (C : Contr_internal@{u} A)
: Contr_internal@{v} A := C.
Definition test2@{u v | u < v} (A : Type@{u}) (C : IsHSet A)
: IsHSet A := C.
Cumulative Record Test@{+u} := { T : Type@{u}; H : IsHSet T }.
```
However, for general `n`, you don't get definitional cumulativity of `IsTrunc_internal n A`:
```
Fail Definition test3@{u v | u < v} (n : trunc_index) (A : Type@{u}) (C : IsTrunc_internal@{u u} n A)
: IsTrunc_internal@{v v} n A := C.
```
(Is it possible to make that work?  It would be nice to have.)
The reason Jarl and I are interested in making this change is that it allows `Group` to be cumulative as well.  (The …

Make Contr_internal and some algebra Classes Cumulative

---

theories/Algebra/Groups/FreeProduct.v
theories/Modalities/ReflectiveSubuniverse.v

We currently have `O_rec` marked as `simpl never` to avoid having it unfold with `cbn`.  This PR changes it to
```
Arguments O_rec {O} {P Q}%type_scope {Q_inO H H0} f%function_scope !x.
```
which means that `cbn` will unfold it if `x` appears with a constructor.  This means that `cbn` changes `O_rec (O:=Tr n) f (tr x)` to `f x` and `Trunc_functor n f (tr x)` to `tr (f x)`, both of which are convenient.  If the argument is `x` instead of `tr x`, then these are left alone.
No other changes were required in the library.
Five `cbn`s in FreeProduct.v got about 0.1s slower each, but both before and after they produced an unwieldy term, and it worked to just remove them.  After this, the overall build time is about 0.1s faster than before, and no file increased by more than 0.06s.
In #1475, …

Allow O_rec to unfold when passed (tr x)

---

.github/workflows/ci.yml
hott.opam

The HoTT release for 8.16 was already done. If we merge this then we can start using the new 8.16 features such as:
- Reversible coercions, see #1641
- Better cumulative universes
- `Print Notation` command detailing parsing information about a particular notation.
- Generalized rewriting (formerly setoid_rewrite) now supports relations polymorphic in Type.
See the full Coq changelog: https://coq.inria.fr/refman/changes.html

bump supported Coq version to 8.16

---

theories/HIT/V.v

Closes: #620 
See issue #620 for a discussion of this.  In the past, some definitions in the file HIT/V.v used tens of thousands of universe variables.  It seems like Coq has to a large degree fixed this:  with Coq 8.16, I randomly checked a number of definitions, and the worst I found were:  `V_func` (219 universe variables), `V_union` (219 universe variables) and `infinity` (64).  (Did I miss any that are worse?)
I found that annotating the definition of just one function, `V_ind`, greatly improved things.  Now those three definitions use 3, 3 and 6 universe variables, respectively.  Also, the build time goes from 1.35s to 0.96s on my system.
I also annotated the definition of `V` a bit more, but there is no change to the meaning.  This just documents and enforces the existing universe …

Reduce universe variables in V.v

---

theories/Classes/implementations/natpair_integers.v
theories/Classes/tactics/ring_tac.v

The change from using `try apply _` on all goals in Z_ring to using `exact _` on just the two goals that are solved speeds up building natpair_integers.v by around 5%.  The removal of `compute` in the tactics saves another 10%.  Overall, the build time of the part of the library that depends on these files is reduced by 7%.

Speed up natpair_integers.v

---

theories/Analysis/Locator.v
theories/BoundedSearch.v
theories/Truncations/Core.v

By inserting a propositional truncation, can avoid needing Funext.

Avoid Funext in BoundedSearch.v

---

theories/Basics/Decidable.v
theories/BoundedSearch.v
theories/Truncations/Core.v

If P is double-negation stable (as, for example, any negated proposition ~P is), then merely P -> P.
We could retain the original theorem under its name, or we could leave it up to typeclass resolution to fill the gap. Not clear which is better.

Weaken "Decidable" to "Stable" in hypotheses

---

theories/Spaces/Finite/FinNat.v

I think that the finite ordinals should be defined in the ground universe to avoid excessive proliferation of universes.

Remove polymorphism from def of ordinals.

---

theories/Basics/Datatypes.v
theories/Classes/orders/rings.v
theories/PropResizing/Nat.v

Based on some discussion on the zulip and my own need, sums and products have been made cumulative, with the associated necessary changes.

Make products and sums cumulative.

---

theories/Classes/interfaces/canonical_names.v

This commit fixes the following bug with the notation `(.* x)`, intended to be short for `fun y => sg_op y x`. Previously, the relevant scopes hadn't been opened, causing the notation to use the function `prod` instead of `sg_op`. This caused issues when used in combination with type_scope, in which `prod` refers to the product of types. One can verify the issue by running `Locate "(.* x )".` right after the notation has been defined on the master branch.
Opening the relevant scopes remedies the issue. (Another solution would be to write `sg_op` explicitly, but this solution is a bit more modular, and is probably the original intention.)

fix the notation "(.* x )"

---

theories/Algebra/AbSES/Core.v
theories/Algebra/AbSES/Pullback.v
theories/Algebra/AbSES/PullbackFiberSequence.v
theories/Algebra/AbSES/Pushout.v
theories/Algebra/Aut.v
theories/Algebra/Groups/Group.v
theories/Algebra/ooGroup.v
theories/Homotopy/Bouquet.v
theories/Homotopy/CayleyDickson.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/EMSpace.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/Join.v
theories/Homotopy/Pi1S1.v
theories/Homotopy/Smash.v
theories/Homotopy/Wedge.v
theories/ObjectClassifier.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pFiber.v
theories/Pointed/pMap.v
theories/Pointed/pSusp.v
theories/Pointed/pTrunc.v
theories/Spaces/BAut.v
theories/Spaces/BAut/Bool.v
theories/Spaces/Spheres.v
theories/Spaces/Torus/TorusHomotopy.v

Mainly replaces `(point _)` with `pt` and `Build_pType (foo) (bar)` with `[foo, bar]`, but also makes use of `psusp`, the coercion of a group to a pointed type, and a new `pjoin`.
Note that `[X, x]` was chosen as the notation for a pointed type rather than `(X, x)` because the latter conflicts with ordered pairs.  The former conflicts with functor categories, but those are used less often than ordered pairs, and generally in different contexts.  Another nice thing is that there are often many nested parentheses, and the square brackets make it easier to see the matching pairs.  Also, this notation often has fewer parentheses than when using`Build_pType`.

Use pt and [X, x] notations, psusp, pjoin, G, etc.

---

theories/Homotopy/Cover.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/pModality.v
theories/Pointed/pTrunc.v
theories/Truncations/Core.v
theories/Types/Sigma.v

We add basic theory about O-connected covers for a reflective subuniverse O. Specifically, (pointed) functoriality of taking covers, and that covers commute with products. By proving a pointed version of `to_O_natural`, we get pointed functoriality from `functor_pfiber`. For truncation modalities we give a more direct proof (`ptr_natural`). To show that covers commute with products we needed `equiv_path_O_prod`, which relates paths in `O (X * Y)` to paths in `O X * O Y`.
These results will let us simplify some things in `Algebra/ooGroups` (see #1700).

O-connected covers

---

theories/Colimits/Sequential.v
theories/Types/Universe.v

`equiv_path` is just a special case of `equiv_transport`, and `isequiv_path` is therefore not needed.  (It's a special case of `isequiv_transport`.)  Also, `equiv_path_V` and a few other things have simpler proofs.  I'm sure more could be done, but these are just things I noticed in passing.

Universe: simplify some things; adapt Sequential

---

theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/AbGroups/Biproduct.v
theories/Algebra/AbSES/Core.v
theories/Algebra/AbSES/Ext.v
theories/Algebra/AbSES/Pullback.v
theories/Algebra/AbSES/PullbackFiberSequence.v
theories/Algebra/AbSES/Pushout.v
theories/Algebra/Groups/FreeGroup.v
theories/Algebra/Groups/FreeProduct.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Rings/CRing.v
theories/Algebra/Rings/ChineseRemainder.v
theories/Algebra/ooGroup.v
theories/Classes/interfaces/abstract_algebra.v
theories/Classes/interfaces/canonical_names.v
theories/Classes/theory/rationals.v
theories/Homotopy/Bouquet.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/EMSpace.v
theories/Homotopy/HSpace/Core.v
theories/Homotopy/HomotopyGroup.v
theories/Homotopy/WhiteheadsPrinciple.v
theories/Sets/Hartogs.v
theories/Sets/Ordinals.v
theories/Spaces/Torus/TorusHomotopy.v

The Classes library doesn't use anything in Truncations/Connectedness.v or Truncations/SeparatedTrunc.v, so don't import or export any of those.  Other files that were getting some of those via Classes now need to explicitly require them.
`-j1` build time improves slightly.  `-j8` build time doesn't change significantly, but looser dependencies will help if we get a smarter build system or when using more than 8 cores.
(Also, a redundant hypothesis removed from `Qpos_enumerable`.)

Only Require Truncations.Core in Classes library

---

theories/Pointed/Core.v
theories/Pointed/pEquiv.v

See the discussion and examples in #1703.

make pEquiv Cumulative and pequiv_compose more polymorphic

---

theories/Homotopy/Cover.v
theories/Homotopy/EncodeDecode.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Pointed/pMap.v
theories/Pointed/pTrunc.v

I finally figured out how to make `pEquiv` have irrelevant universe variables (the best kind):  I had to make `pFam` into a Record.  This has the added benefit of getting rid of the third universe variable.  So now `pEquiv` has just two universe variables, for the two types.
This allows me to revert part of #1706.  `pequiv_compose` can be defined using the WildCat composition, and ends up with fully flexible universe variables:
```
pequiv_compose@{u u0 u1 u2 u3} = 
fun (A : pType@{u}) (B : pType@{u0}) (C : pType@{u1}) (f : pEquiv@{u2 u2} A B)
(g : pEquiv@{u2 u2} B C) => compose_cate@{u2 u2 u2 u2 u3} g f
: forall (A : pType@{u}) (B : pType@{u0}) (C : pType@{u1})
(_ : pEquiv@{u2 u2} A B) (_ : pEquiv@{u2 u2} B C), 
pEquiv@{u2 u2} A C
(* u u0 u1 u2 u3 |= u2 < u3
u <= u2
u0 <= u2
u1 <= u2 *) …
```

Make pFam into a Record to improve polymorphism of pEquiv

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Basics/Overture.v
theories/Metatheory/UnivalenceVarieties.v
theories/ObjectClassifier.v
theories/PropResizing/Nat.v

The first commit changes `sig` to be a Cumulative Record.  This loosens universe constraints. This means that sometimes Coq isn't forced to equate universe variables, which means that the user needs to supply them if they want to keep the number small.  This happens in two places, in ObjectClassifier.v and PropResizing/Nat.v.   The other effect is that if the user doesn't manage universe variables, there are sometimes more of them.  For example, `equiv_path_group` goes from having 10 universe variables to 16.  Luckily, in the places where they were listed explicitly, it worked to just delete them.  In addition, one minor change was needed for some reason in `Metatheory/UnivalenceVarieties.v`.  In total, only four files besides Overture.v needed adjustments.
The second commit makes …

Make sig and everything else in Overture cumulative

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Modalities/Descent.v
theories/ObjectClassifier.v
theories/Truncations/SeparatedTrunc.v

We reduce the number of universes in `equiv_path_Tr` from 10 to 2. This has various positive downstream effects, such as reducing the number of universes in `conn_point_elim` from 9 to 2.
We also create an alternative version of `equiv_path_group` with only 2 universes, as opposed to 16. This has a positive effect on `equiv_path_abgroup`, etc. I also did a pass through the current proof of `equiv_path_group'` and cleaned up some universes.

Reduce universes in [equiv_path_Tr] and [equiv_path_group]

---

theories/Pointed/Core.v
theories/Pointed/pEquiv.v

Replaces the definition of `equiv_path_ptype` by one whose inverse computes on reflexivity, and whose inverse can be defined without univalence.  This is for work in progress, but also simplifies the proof that pType forms a univalent 1-category.  Also add `equiv_path_pequiv'` which is analogous to `equiv_path_equiv` and also helps simplify that proof.  (It would be even simpler if `id_cate` didn't have to adjointify the identity map, but I don't see a way around that with the current set-up.)

Better proof of equiv_path_ptype; add equiv_path_pequiv'

---

Makefile.coq.local

I've been wondering for a while why my TAGS file has no matches in it, and today I figured out that my version of `etags` (shipped with emacs) doesn't support character classes (like `[:alnum:]` and `[:space:]`).  So I replaced those with naive things, and it works for me now.

Makefile.coq.local: avoid character classes in etags regexes

---

theories/Algebra/AbSES/Ext.v
theories/Algebra/AbSES/SixTerm.v
theories/WildCat/Adjoint.v
theories/WildCat/Core.v
theories/WildCat/FunctorCat.v
theories/WildCat/Opposite.v
theories/WildCat/Universe.v

By breaking up two sections and supplying precise arguments, the number of universes in `isgraph_op` and `is0functor_compose` are reduced. Previously these would generate free universes when inferred, e.g. by typeclass search. This caused issues for work in progress, and these changes make things manageable. (We also add universe annotations to `isgraph_type`, otherwise it had 3 universes with the constraint that two of them were equal.)

Reduce universes in [isgraph_op] and [is0functor_compose]

---

theories/Algebra/AbGroups/Biproduct.v
theories/Algebra/AbSES/BaerSum.v
theories/Algebra/AbSES/Core.v
theories/Algebra/AbSES/Ext.v
theories/Algebra/AbSES/Pushout.v
theories/Algebra/AbSES/SixTerm.v

We show a couple of things:
1. `ab_ext : AbGroup^op -> AbGroup -> AbGroup` is a bifunctor
2. functoriality of `AbSES B : AbGroup -> pType`, with careful proofs as in the pullback case
3. exactness at the second spot (`_ii`) of the six-term exact sequence

Bifunctoriality of ab_ext

---

Makefile.coq.local

Handle things like `Global` and `Cumulative` before things like `Definition`, `Instance`, etc.

Makefile.coq.local: improve etags support

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Cyclic.v
theories/Algebra/AbSES/Core.v
theories/Algebra/AbSES/SixTerm.v
theories/Basics/Overture.v
theories/Classes/implementations/family_prod.v
theories/Classes/interfaces/abstract_algebra.v
theories/Colimits/SpanPushout.v
theories/Extensions.v
theories/HIT/SetCone.v
theories/HIT/epi.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/Freudenthal.v
theories/Homotopy/Suspension.v
theories/Limits/Pullback.v
theories/Metatheory/Core.v
theories/Modalities/Accessible.v
theories/Modalities/Descent.v
theories/Modalities/Lex.v
theories/Modalities/Nullification.v
theories/Modalities/Open.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Modalities/Separated.v
theories/Truncations/Connectedness.v
theories/Types/Unit.v
theories/Types/Universe.v

This PR improves things that were getting in the way in practice with certain formalizations.  Lots more could be done, but these were things I was noticing.  Each commit can be read independently.
Some highlights: `conn_point_incl` goes from 17 universe variables to 2 and `Susp` goes from 6 to 1.  `OO_inverts_ap'` goes from 6 to 1, with no changes, just inheriting improvements from elsewhere.  This allows us to avoid defining it in two steps.
Another nice thing sometimes happens:  when you reduce `foo` from 8 to 4 variables, you often go from having to specify 8 variables to having to specify none, since the ones that remain are often determined by the context.  So this PR is able to remove a number of annotations in high-level code (in exchange to adding some to more fundamental …

Reduce universe variables in a number of places

---

theories/Truncations/Connectedness.v

This just fixes a regression in the last commit I made in #1721.

Connectedness.v: remove a universe variable from conn_point_incl

---

etc/generate_coqproject.sh

I made a few cleanups to etc/generate_coqproject.sh.  It now detects when dune is being
used, and doesn't spit out a warning, since it is expected that we are in a subdirectory.

generate_coqproject.sh: get rid of warning when building with dune

---

.github/workflows/ci.yml
etc/ci/generate_and_push_quick_doc.sh

There was a leftover for prviola here. The links in the dep graph would link to the non-existant proviola doc. We switch this out for the alectryon doc.
Signed-off-by: Ali Caglayan <alizter@gmail.com>

fix: dep graph links

---

.github/workflows/ci.yml

This will auto-cancel the last run of the CI on the same PR. This is helpful when there is a lot of traffic on a PR and you don't want all the workers busy.
Signed-off-by: Ali Caglayan <alizter@gmail.com>

ci: auto-cancel last run

---

.github/workflows/ci.yml
flake.lock
flake.nix

If you have Nix, you can do `nix develop` to quickly get the dependencies for building the library. You can also build the library directly with `nix build`.
- Add Nix jobs to CI. Uses cachix so should be fast.
- Update checkout@v2 to checkout@v3
Nix is a package manager that allows for completely reproducible builds. It hashes things like Dune but at the level of packages and executables. As an alternative to Opam, it allows you to quickly drop into a development environment, or build the library without having to worry about dependencies since they are always fully specified.
We have a cache associated to our CI actions, so if it has been built before it won't be rebuilt. You can even setup your own nix installation to use the cache (named "coq-hott") on cachix.
With a bit more work, we …

Add nix flake

---

flake.nix

This lets you use coq-lsp when you do `nix develop`. More information about coq-lsp can be found here: https://github.com/ejgallego/coq-lsp
Signed-off-by: Ali Caglayan <alizter@gmail.com>

nix: add coq-lsp to dev shell

---

theories/Algebra/AbGroups/AbHom.v
theories/Algebra/AbSES/SixTerm.v
theories/Algebra/Groups/ShortExactSequence.v

We prove `isexact_abses_sixterm_i`, which is exactness at the first spot of the six-term exact sequence of Ext groups associated to a short exact sequence. It's an incarnation of precomposition by a surjection is an injection, so we state and prove that first.
The statement was included without a proof (using `Abort.`) in a previous PR.

Exactness of six-term exact sequence of Ext at first spot

---

theories/Basics/Decimal.v
theories/Basics/Hexadecimal.v
theories/Basics/Numeral.v
theories/Basics/Tactics.v
theories/Categories/InitialTerminalCategory/Core.v
theories/Classes/implementations/binary_naturals.v
theories/Classes/tactics/ring_quote.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/Nat/Core.v
theories/Tactics/EquivalenceInduction.v
theories/Tests.v

Currently "Unset Universe Minimization ToSet" is somewhat buggy and these inductives still get minimized to Set automatically, but if that's fixed we need this patch to avoid putting them in floating universes.
Alternatively we could enable minimization to set in these files.

Explicitly use : Type0 more

---

theories/Categories/FunctorCategory/Morphisms.v

Hi, there is ongoing investigations in the implementation of Coq aiming at providing all generalizations of a declaration of a section at the time of declaration, see PR coq/coq#17888. The generalized constants would use qualified names: for a constant `C` in section `S` in file `F`, the generalization would have name `F.C`.
While testing the Coq PR, I realize that Coq-HoTT has one example of a qualified name which would then clash. This PR anticipates the need for qualifying it one step further.
It is not clear yet how the Coq PR will evolve, but if ever the present PR is in any case ok for Coq-HoTT, it can also be merged as soon as now, without waiting about what coq/coq#17888 will eventually give.

Qualifying idtoiso into Category.Morphisms.idtoiso

---

theories/Homotopy/HSpace/Core.v

I'd previously (inadvertently) created an instance cycle in `Homotopy.HSpace.Core` by making both `ishomogeneous_hspace` and `ishspace_homogeneous` instances. By making one of these a definition we avoid the cycle. I opted to make the passage from a left-invertible H-space to a homogeneous structure an instance because it forgets data. We could make the other direction a `Hint Immediate` (or something similar), but there's currently nothing that would benefit from it.

Fix instance cycle in Homotopy.HSpace.Core

---

contrib/HoTTBook.v
contrib/HoTTBookExercises.v
theories/Equiv/BiInv.v
theories/Sets/GCHtoAC.v
theories/TruncType.v

I just wanted to make sure that `IsEquiv` and `BiInv` are logically equivalent without `Funext`, so I factored that part out.  Then I did a few cleanups in other files.

Minor changes to Equiv/Biinv and files that use it

---

INSTALL.md
Makefile.coq.local
dune
etc/emacs/etags-args

@jdchristensen Both `make` and `dune` will share the arguments to `etags` which now live in `etc/emacs/etags-args`. In both systems, the file is inlined to pass the arguments to `etags`.
We add a dune rule that builds (and promotes) the TAGS file. Simply do:
```
dune build TAGS
```
to get up to date tags. This is not included in the `@default` alias, so it won't be built by `dune build`.
I've tested it and both `make` and `dune` are able to produce the `TAGS` file now.

add emacs TAGS support to dune

---

Makefile.coq.local

I believe this find command is meant to handle renamed or removed files or directories, since in normal situations `.vo` and `.glob` files are correctly deleted by `make clean`.  But the implicit `and` between `-name \*.timing`  and `-delete` binds more tightly that the `or`s marked with `-o`, so only timing files are deleted by this command.  The parentheses fix this.
Also, now that we build things in the `test` folder, I added that as well.

Makefile.coq.local: find: add missing parentheses and add test folder

---

theories/Algebra/AbGroups/Abelianization.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/Suspension.v
theories/WildCat.v
theories/WildCat/Equiv.v
theories/WildCat/EquivGpd.v
theories/WildCat/Yoneda.v
theories/WildCat/ZeroGroupoid.v

This PR adds a covariant Yoneda lemma using the representable functor `Hom a -` that lands in the 1-category of 0-groupoids.  This is based on discussion in #1744.
I've marked this as WIP for now, as I'd like feedback, e.g. on naming, but also on anything else.  I will likely also add the dual version if this looks good.

Yoneda lemma using 0-groupoids

---

dune

I noticed _CoqProject was not getting built by dune.  Is this the right way to fix that?

dune: build _CoqProject by default

---

test/bugs/github1758.v
theories/Colimits/GraphQuotient.v
theories/HIT/Flattening.v
theories/HIT/Interval.v
theories/HIT/README.txt
theories/Spaces/Torus/Torus.v

I noticed that Coq was considering some functions defined using `Join_rec` to be definitionally equal when they weren't.  I traced this back to `GraphQuotient_ind` not using the idiom that makes Coq believe the supporting arguments are actually required.  I looked around and found other cases where this was a problem, and fixed all but one.
The one case I didn't fix was Spaces/No/Core.v.  There are a bunch of suspicious `destruct`s in there that probably need similar guarding, but it was too complicated for me to quickly fix things here.  I'll open an issue about this.  Edit: It's #1759.

HITs: fix inconsistencies from several HITs

---

flake.lock
flake.nix

We bump the Coq version on nix to 8.18. Support for coq-lsp included.

chore: update flake to coq 8.18

---

theories/Basics/Equivalences.v
theories/Categories/LaxComma/Core.v
theories/Classes/implementations/binary_naturals.v
theories/Classes/implementations/peano_naturals.v
theories/Colimits/Pushout.v
theories/Modalities/ReflectiveSubuniverse.v

Allow `Pushout_ind` (and therefore various other things) to compute; loosen some universe variables; change `Let ... Qed` to `Local Definition ... Qed` to truly hide the contents (and make some proof terms much smaller); silence two warnings about minimization to Set.
Each commit can be read independently.
Everything builds fine with Coq 8.17 as well.

Adjustments to support Coq 8.18.0

---

Makefile.coq.local
dune
etc/emacs/etags-args
etc/emacs/run-etags.sh

@Alizter Let me know what you think about this approach.  I think it's very easy to understand what is going on if it needs to be updated in the future.

create etc/emacs/run-etags.sh to make argument processing clear

---

theories/Algebra/AbGroups/Abelianization.v
theories/Basics/Notations.v
theories/Pointed/Core.v
theories/Types/Equiv.v
theories/WildCat/Core.v
theories/WildCat/Equiv.v
theories/WildCat/NatTrans.v
theories/WildCat/Prod.v
theories/WildCat/Universe.v
theories/WildCat/Yoneda.v
theories/WildCat/ZeroGroupoid.v

A bunch of additions to the WildCat library, as well as various simplifications to existing proofs.  Many of these are for WIP that I hope to PR soon.

Wildcat improvements

---

theories/Basics/Equivalences.v
theories/Colimits/Pushout.v
theories/Homotopy/Join.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Homotopy/Join/JoinSusp.v
theories/Homotopy/Suspension.v
theories/Spaces/Spheres.v
theories/Types/Unit.v

The first commit proves that `Susp` is a 1-functor (and does a couple of other cleanups to Suspension.v).
The second commit proves that `Join Bool A` is equivalent to `Susp A`, using @Alizter 's direct argument, with some reorganization.  It also shows that iterated joins of `Bool` give spheres.
The third commit contains misc cleanups and isn't really related.

Susp is a 1-functor; Join Bool A <~> Susp A; etc.

---

theories/Algebra/Groups/Group.v
theories/Algebra/Rings/CRing.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Homotopy/Join/JoinSusp.v
theories/Metatheory/PropTrunc.v
theories/Pointed/Loops.v
theories/Sets/Powers.v
theories/Spaces/Nat/Core.v

I realized that we had many places that were repeating the idiom of iterating a function, such as `iterated_loops`, `Join_power`, `grp_pow`, etc.  So I replaced them with `nat_iter`.  This has the benefit that there are general lemmas proved about `nat_iter` that we can apply in those situations.  I also made various clean-ups while I was touching some files.

Use nat_iter for iteration

---

theories/Spaces/No/Addition.v
theories/Spaces/No/Core.v
theories/Spaces/No/Negation.v

While looking at Spaces.No.Core recentlly, I realized that the lines
```coq
Context {S : OptionSort@{i}}.
```
and
```coq
Private Inductive Game : Type := | opt : forall (L R : Type@{i}) ...
```
were inadvertently introducing *independent* universe variables denoted `i`, when the intention was that they be the same variable.   As a result, `Game` had two universe variables, which were constrained to be equal.  The fix is simply to add `Universe i.` before the first line above, to declare `i` as a universe variable throughout the section.  This is the content of the first commit, which therefore must also change `Game@{i}` to `Game` throughout (since `Game@{i}` is actually referring to two universe variables, since one is in the context).  This reduces by one the number of universe …

Reduce universes in Spaces.No

---

theories/Factorization.v
theories/Modalities/Modality.v

I searched the library and only found one more place where a universe variable was used in a Context command without being declared.  I also found an out-of-date comment, which only was relevant if the universe variable in question was not declared.

Declare universe variables in Context commands

---

contrib/SetoidRewrite.v
theories/Basics/PathGroupoids.v
theories/Homotopy/Bouquet.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Homotopy/Join/TriJoin.v
theories/WildCat/Adjoint.v
theories/WildCat/NatTrans.v
theories/WildCat/Yoneda.v
theories/WildCat/ZeroGroupoid.v

This proves that `trijoin_twist` is natural.  Combined with the naturality of `join_sym`, this gives the naturality of `join_assoc`.  Direct proofs seemed hard, but by phrasing things using a new `functor_trijoin` defined using `trijoin_rec` it was possible to make this fairly clean, using naturality of `trijoin_rec` and `trijoinrecdata_fun_twist`.  Along the way, I removed rarely used arguments to `is1natural_natequiv` and `is1natural_nattrans`, and added `isnat_natequiv`, which is needed because another ambiguous coercion doesn't work.

Naturality of join_assoc and trijoin_twist

---

theories/WildCat/Universe.v

Here is the 2-category structure on Type. It will be used for when we talk about 3-cells in Type.

wildcat: show Universe is a 2-cat

---

theories/Spaces/No/Core.v

The fix was just merged into Coq.

No/Core: add todo saying to remove workaround when Coq 8.19 is required

---

theories/Basics/Equivalences.v

The first commit just moves `equiv_inj` a bit earlier in the file, with no changes.  Deselecting it makes the diff clearer.
The second commit cleans up a few things.  The proof of `isequiv_isequiv_precompose` is much shorter, and the dual is now proved.  The `ev_equiv` tactic is extended to do more tidying of goals involving `equiv_fun ...`.  Plus a few other minor things.

Equivalences clean up

---

theories/Colimits/Colimit_Flattening.v

On my machine, the time goes from 3.6s to 1.3s.  There are only two slow lines, both marked with TODO, but they are the tricky kind:  a Defined (0.4s), and the closing of the Section (0.2s).  Normally I would just remove the section, but if I simply remove it and leave the Context command, then the file becomes slower overall.  It might work to copy the Context to every definition, but I didn't think that was worth it for 0.2s.

Speed up Colimit_Flattening

---

test/bugs/github1791.v
theories/Basics/Overture.v
theories/Basics/Tactics.v
theories/Homotopy/Join/Core.v
theories/WildCat/Core.v
theories/WildCat/Square.v

Because of [Coq issue 10513 ](https://github.com/coq/coq/issues/10513), unused `Context` variables introduce floating universe variables.  Floating universe variables are particularly annoying because they accumulate, as they are never forced to be equal to other variables.  The very small changes in the first commit cause an out-of-tree definition to go from having 623 universe variables to having 5 universe variables.
The second commit adds a tactic `simple_path_induction` which is to path induction as `simple_induction` is to induction over the naturals.  It avoids introducing universe variables in the induction.  I use this in Join/Core, as an example.  It turns out to not have been the cause of the blow up, but I think it's good to have.  I put this in Basics/Tactics, and moved …

Reduce universe variables, mainly in WildCat

---

test/bugs/github1794.v
theories/Basics/Overture.v
theories/Tactics.v

The first commit:
- Explains more clearly why `paths_rew` and `paths_rew_r` are defined, even though they are never used.  It also renames them and makes them `Local`.
- It makes some arguments to `internal_paths_rew` (and `rew_r`) implicit.  Now these look just like `transport`, except for the argument order.
- I also added a remark that `internal_paths_rew` is in fact definitionally equal to `transport`.  It's too bad that it's `internal_paths_rew_r` that arises from the default direction of `rewrite`...
- I removed `paths_rect_r`, which is never used.  The comment suggests that in the past it was needed for `rewrite <-`?
The second commit just moves the `internal_paths_rew` stuff to be right near `transport`, and fixes some other whitespace issues.  So it's best to look at the first …

Basics/Overture: clarify things related to internal_paths_rew

---

theories/Algebra/AbSES/SixTerm.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/Join/Core.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pFiber.v
theories/Pointed/pHomotopy.v

We show the (2,1)-category structure for pointed types. In order to do this easily, we introduce a new tactic called pelim which allows easy path induction on the pointed equation of various pointed structures. This is particularly useful in removing funext from various pType coherences.
Various places seemed to break from these changes, but could easily be fixed by replacing pointed notations with wildcat notations. This perhaps hints at a larger refactoring that should be done.
My motivation for showing these coherences is the need for 1-functoriality of pre/postcomposition for some unrelated work. Therefore it made sense to quickly generalize to the full 2-category while I was at it.

2-cat of pointed types

---

test/Pointed/Core.v
theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/AbSES/Pullback.v
theories/Algebra/AbSES/SixTerm.v
theories/Basics/Tactics.v
theories/Basics/Trunc.v
theories/Homotopy/CayleyDickson.v
theories/Homotopy/EMSpace.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/Freudenthal.v
theories/Homotopy/HSpace/Coherent.v
theories/Homotopy/HSpace/Core.v
theories/Homotopy/HSpace/Moduli.v
theories/Homotopy/HSpace/Pointwise.v
theories/Homotopy/Join/Core.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/Core.v
theories/Truncations/Connectedness.v

Various things related to H-spaces, Eilenberg-Mac Lane spaces and loop spaces which helps WIP on bands, central types, Euler classes, etc.  The commit titles give a reasonable summary.  Many commits are independent, and the library builds after each commit.  I also improved the just-added `pelim` tactic and added tests.  I used `pelim` in a couple of places; there were other possible places too, but I left the explicit proofs in place.

Updates to EMSpace, Join/Core, HSpaces/* and other things

---

theories/Homotopy/SuccessorStructure.v

One of the nice things about pType is the potential to define the wildcat structure "all the way up". We don't actually do this, but because pHomotopy is defined as pForall we get all the higher morphisms "for free".
I was interested in working out what exactly makes a "forall" in a category tick. From what I could find, its not really a commonly studied phenomenon. Typically in category theory, such "forall" looking sets of dependent functions carry an extra structure of being internal. This is a strong requirement that makes it impossible to replicate in various categories (keep Spectra in mind). However the lesson to learn from pType is that we almost never care about ppForall but only pForall which has nothing to do with the internal (dependent) hom.
Therefore I was interested in …

1-category of successor structures

---

theories/Homotopy/CayleyDickson.v

I've being playing around with the proofs in Cayley-Dickson and here are some speedups and cleanups.
Notably funext is removed by using the old intro-revert trick when eliminating multiple hyps of a HIT.

CayleyDickson: some cleanups, remove funext

---

theories/Homotopy/HSpace/Moduli.v
theories/Pointed/pEquiv.v
theories/Pointed/pSect.v
theories/Pointed/pSusp.v
theories/Spaces/BAut.v
theories/Spaces/Circle.v
theories/Spaces/Spheres.v
theories/Types/Bool.v

Prove that `(psphere n ->** X) <~>* iterated_loops n X` using various minor lemmas spread in a bunch of files.

Add pmap_from_psphere_iterated_loops, and needed lemmas

---

theories/Algebra/Groups/FreeProduct.v
theories/Algebra/Groups/Group.v
theories/Homotopy/Wedge.v
theories/Pointed/Core.v
theories/WildCat.v
theories/WildCat/Coproducts.v
theories/WildCat/Products.v
theories/WildCat/Universe.v
theories/WildCat/ZeroGroupoid.v

We define what it means for a wild cat to have binary products and then show Type, pType and Group to have binary products. This notion of product is only 1-coherent as it will not be the correct notion of a product in a bicategory. But this doesn't matter for now as we haven't even defined a full bicategory yet.
AbGroup will be left out for now as a notion of biproduct will follow soon.
I've also defined binary coproducts as products in the opposite category and shown Type, pType and Group as examples of categories with binary coproducts.

wildcat: binary products

---

theories/Classes/theory/ua_first_isomorphism.v
theories/Classes/theory/ua_quotient_algebra.v
theories/Classes/theory/ua_second_isomorphism.v
theories/Classes/theory/ua_third_isomorphism.v

The use of quotient here was easy to replace. In a few places, cbn is replaced with simpl as Quotient interacts poorly with cbn, probably because of simpl never.

use Quotient in ua library

---

theories/Sets/Ordinals.v

use Quotient in Ordinals.v

---

theories/WildCat/Products.v

We prove symmetry and associativity of binary products.
I had a look at extending the result for colimits, but I couldn't get some things to hold definitionally so I will need to take a deeper look at some later point.
I also don't quite see how this will help with the left/right functoriality of the product. @jdchristensen if you have some more comments on this that would be useful. Although, I will probably do it in a follow up PR.

symmetry and associativity of products

---

theories/Basics/Trunc.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/HomotopyGroup.v
theories/Homotopy/Hopf.v
theories/Modalities/Modality.v
theories/Pointed/Loops.v
theories/Spaces/Nat/Core.v

We prove Proposition 2.19 of [BCFR](https://arxiv.org/abs/2301.02636v2) and use it to strengthen Freudenthal's theorem for H-spaces. To do this, we define the Hopf construction (but don't prove much about it) and add some minor things that we needed.

A strengthening of Freudenthal's theorem for H-spaces

---

theories/Algebra/AbGroups/Z.v
theories/Algebra/Groups/Group.v
theories/Basics/Tactics.v
theories/Classes/implementations/natpair_integers.v
theories/Classes/implementations/peano_naturals.v
theories/Homotopy/SuccessorStructure.v
theories/Spaces/Finite/Fin.v
theories/Spaces/Int/Core.v
theories/Spaces/Int/LoopExp.v
theories/Spaces/Int/Spec.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/Nat/Core.v
theories/Spaces/Pos/Core.v
theories/Spaces/Pos/Spec.v
theories/Truncations/Connectedness.v
theories/Types/Empty.v

When dealing with types defined to land in `Set` (aka `Type0`), such as `abgroup_Z`, `Pos`, `Int` and `Fin n`, it makes sense to use `Local Set Universe Minimization ToSet.` as otherwise free universe variables are created that are not matched when using the results.  By doing this and being careful to use `simple_induction`, many universe variables are eliminated.  For example, `abgroup_Z` goes from 25 to 0, `fsucc_mod` goes from 9 to 0, and `stratified_succ` goes from 17 to 1.
There are other improvements mixed in, such as making use of `nat_iter`.   I also cleaned up various comments and fixed indentation.

Reduce universe variables and other clean-ups

---

theories/Sets/Hartogs.v
theories/Sets/Ordinals.v

There are two commits and they need to be read independently because the second one moves many things around.
The first one reduces the build time of Hartogs.v by 47%.
The second one moves things from inside the Hartogs Section to outside of it when they don't depend on the fixed type `A` and the universe variable `A` that are in the context.  Some are moved earlier in the file, and some are moved to Ordinals.v.  While editing, I changed lots of whitespace to match our conventions and made other minor fixes.

Hartogs: improve speed, reorganize

---

theories/HIT/V.v
theories/Homotopy/EMSpace.v
theories/Modalities/Descent.v
theories/Modalities/Lex.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Types/Unit.v

I was noticing some slow typeclass search, and saw that a few things were being tried that were either futile (because Coq would have to guess something) or caused a loop (which Coq seemed to at least notice and cut short).  This PR removes them from the global database, without needing to change any proofs.  I was hoping the build would be faster, but there is no noticeable change.  Still, this might let us use `rapply` in places where we were forced to use `nrapply` combined with some specific `exact _` lines.
I also have a question.  Consider the following:
```coq
Require Import HoTT.
Definition lem (k : trunc_index) (X : pType) `{IsConnected k X} (Y : Type) : Contr (X -> Y).
Admitted.  (* Not a true statement.  Just an example. *)
Definition test (m : nat) (X : pType) `{Univalence} (Y …
```

Remove some Global Instances

---

theories/Homotopy/ClassifyingSpace.v
theories/Modalities/Modality.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/Core.v
theories/Pointed/pModality.v
theories/Pointed/pTrunc.v
theories/Spectra/Spectrum.v
theories/Truncations/Connectedness.v
theories/Truncations/Core.v
theories/Truncations/SeparatedTrunc.v
theories/Types/Arrow.v

This proves Buchholtz-van Doorn-Rijke, Theorem 4.2 and related things.  The first commit has the meat, and can be reviewed on its own.  The second commit just contains minor cleanups that I noticed while reading things.

Truncatedness of pointed maps and pForall

---

theories/Basics/Trunc.v
theories/Homotopy/EMSpace.v
theories/Homotopy/Hopf.v
theories/Homotopy/PinSn.v
theories/Pointed/pModality.v
theories/Truncations/Connectedness.v

With #1814 done, we knew we could give a new proof of the Licata-Finster theorem, while also generalizing it to any truncation level.  One way to do this would be to use homotopy groups and the truncated Whitehead theorem, but I noticed that one could use Prop 2.31 from CORS to prove the analogous result for any reflective subuniverse.  When I went to formalize it, I found that @mikeshulman had beat me to it almost four years ago with `OO_inverts_conn_map_factor_conn_map`!  So the additional work to prove Licata-Finster is just a few lines.
The first commit contains this, and removes the old encode-decode proof.  I'm happy to keep that proof around if people want.
The second commit cleans up EMSpace a bit by reversing some of the equivalences to be in the direction of the natural map, …

New proof and generalization of Licata-Finster theorem

---

theories/Colimits/Colimit_Pushout.v

The `hott_simpl` line took 1.5s on my laptop, making it the slowest in the library.  Now every line in that proof is very fast (< 0.03s).  The slowest line is the `Defined.` which takes about 0.12s.  The proof is also much more readable.

Colimit_Pushout: speed up slowest line in library

---

theories/Modalities/ReflectiveSubuniverse.v

This contains very minor changes.  The main reason I'm making this an independent PR is that I have another question about typeclass resolution.  I'll add a comment beside the relevant spot in the code, and will attach the verbose typeclasses debug log here.
[debug.log](https://github.com/HoTT/Coq-HoTT/files/13996119/debug.log)

ReflectiveSubuniverse: add a couple of things and simplify one proof

---

theories/Homotopy/Wedge.v
theories/Pointed/Core.v

We define wedges of families of pTypes.
Interestingly, we have to make some decidability assumptions on the indexing type in order to get the inclusion from wedge to product. This is also true for such colimits in a general pointed category.
I'm not sure if these assumptions are necessary, and in practice most index sets we will choose are decidable.
Once we have free products of abelian groups defined, we should be able to extend the PinSn result to wedges of spheres.

Wedge of a family of pType

---

theories/Modalities/ReflectiveSubuniverse.v
theories/Pointed/Core.v
theories/Pointed/pEquiv.v
theories/Pointed/pSusp.v
theories/Pointed/pTrunc.v
theories/Truncations/Connectedness.v

The only non-trivial thing is an improvement to the universes in the result `istrunc_pmap` that I added recently.  When I went to use it in other code, I found that Coq had made some sub-optimal choices that meant I couldn't use it.

Minor updates to Pointed/*, ReflectiveSubuniverse

---

theories/Basics/Notations.v
theories/WildCat.v
theories/WildCat/Displayed.v

This is a refresh of work by @emilyriehl and others that can be found [here](https://github.com/mikeshulman/Coq-HoTT/blob/1f2bff43ccfe4a392cadfcca8104e58f30ca0d75/theories/WildCat/Displayed.v). The ultimate direction is still unclear, so any thoughts to that effect are appreciated. 
A few arbitrary conventions that are up for debate:
- Where possible, anything that exists in [WildCat/Core](https://github.com/HoTT/Coq-HoTT/blob/master/theories/WildCat/Core.v) retains the same name prefixed appropriately by d (or D). For example, `Is1DCat` and `dcat_comp`.
- A single tick indicates that an object or structure lives in a displayed category over the underlying object or structure. For example, if `a : A` then `a' : D a`, and composition in displayed categories is denoted `g' $o' f'` over `g …

Displayed Wild Categories

---

theories/Modalities/ReflectiveSubuniverse.v

Tiny fix to get rid of a floating universe variable.

ReflectiveSubuniverse: simplify universe vars in conn_map_homotopic

---

theories/WildCat/Induced.v

E.g. don't eta-expand function calls; don't do unneeded "cbn in *"; use notypeclasses when possible.

WildCat/Induced: various minor simplifications

---

theories/WildCat/Induced.v

I shouldn't have merged that last PR so quickly, as I realized a one-line tactic will make the idiom very uniform.  We `intro` all variables of type `A`, and then we apply the wildcat structure from `B`.  `is1cat_induced` sees the most benefit from this.

WildCat/Induced: add and use intros_of_type tactic

---

theories/Classes/implementations/family_prod.v
theories/Classes/implementations/ne_list.v
theories/Classes/interfaces/ua_algebra.v
theories/Colimits/Pushout.v
theories/HIT/FreeIntQuotient.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Projective.v
theories/Utf8.v
theories/Utf8Minimal.v

It turns out that the Classes library was depending on WildCat, Cubical, Modalities, Homotopy.Suspension, etc, all because it uses some unicode symbols defined in Utf8.v.  I separated that small subset into a new file Utf8Minimal.v, which greatly reduces the dependencies and speeds up a parallel build by about 2%.  I also reduced a few other dependencies.  I noticed these because so much of the library was getting rebuilt when WildCat/Induced.v was changed.
The commits are independent, except that the fourth one depends on the third one.

Reduce dependencies, especially for Classes

---

contrib/HoTTBook.v
theories/Colimits/Colimit_Pushout.v
theories/Colimits/Colimit_Pushout_Flattening.v
theories/Colimits/PushoutFlattening.v
theories/HoTT.v
theories/Homotopy/Hopf.v
theories/Types/Unit.v

We use the colimits library to prove flattening for pushouts. The proof is a bit annoying as it doesn't compute well.
We use this to show that the Hopf construction has total space equivalent to a join. Because of the uncomputable nature of the flattening lemma we are unable to show that it preserves the base point.
This should be enough for something else I am working on. Corollaries like the Hopf fibrations for the spheres would ideally come once we sort out the computability.
I tried proving the flattening lemma directly for GraphQuotient and Pushout but I was not able to get around the difficult path algebra easily. The fact that this is done in the Colimits library is good and we should use it, however it is not as easy as I thought to transfer across equivalences in this case. Maybe …

flattening for pushouts + total space of Hopf construction

---

theories/Colimits/Colimit_Pushout.v
theories/Homotopy/Hopf.v

Colimit_Pushout.v: The proof of `PO_ind` contained large subterms which needed to be reproduced in other proofs.  I factored those out, which makes many proof terms much smaller.  Also I avoided unnecessary uses of `destruct` (using the `[]` notation), which also made some proof terms larger than needed.  And I cleaned things up a bit.
Hopf.v: Just some minor things to avoid some fruitless typeclass search.

Colimits and Hopf: clean up and speed up

---

theories/Homotopy/Wedge.v
theories/Pointed/Core.v
theories/Types/Prod.v

This PR does the following:
- We redefine the wedge-product inclusion using `wedge_rec`.
- We define the projection or collapse maps from the wedge to the summands.
- We extract various lemmas about pointed products out of the HasBinaryProducts instance.
- We add computation rules for products using `path_prod'` as the computation rules for `path_prod` sometimes cannot be used/inferred easily.

wedge projections

---

Makefile.coq.local

It's not that important, but the alectryon builds spew out long line warnings because of our conventions on not having line breaks in comments, and I think this will get rid of them.  Let's see what happens when the CI runs.

Makefile.coq.local: reduce long line warnings in alectryon build

---

theories/Sets/AC.v
theories/Sets/GCH.v
theories/Sets/Ordinals.v
theories/Truncations/Core.v

This notation is a bit too global and conflicts with wedge sum notations we use later. We fix this by putting it behind a module and import it when it is used. (It isn't used enough to justify it being global).
I also don't think it should be in type_scope but I don't really want to spend time thinking about that right now.

put hor \/ notation in module

---

theories/Homotopy/Wedge.v

These are some quality of life improvements for working with wedges. They consist of:
- <s>Adding explicit universe levels for wedges. Not sure if they need to be generalised further. I've opted for 2 levels for the source and target. I can't tell if having 3 will be useful at this point.</s> Universe levels are generalized correctly now.
- Generalising wedge_rec to target any type (in any universe) and naming that wedge_rec'. Then redefining wedge_rec as a special case of wedge_rec'.
- Using wild category notations for various arrows and homotopies so that fmap and friends work better.
- Add a computation rule for the wedge inclusion.

various improvements to wedge

---

theories/Homotopy/Hopf.v
theories/Types/Arrow.v
theories/Types/Equiv.v

We characterize the fiber of the loop-susp counit. We can't make it a pointed equivalence just yet as we are missing pointedness of the Hopf construction. Interestingly we have to twist the first component when we try to show the sigma types are equivalent.
I've also gone ahead and added the lemmas in #1841 as we use one of these.

characterize fiber of loop-susp counit

---

theories/Types/Sigma.v

This is sometimes more easily inferred.

add curried version of equiv_sigma_prod

---

theories/Colimits/GraphQuotient.v
theories/Types/Sigma.v

In this PR we state and prove the flattening lemma for [GraphQuotient] which grants #1833. This is much more direct than other flattening lemmas we have in the library and might lead to better computation.
I'm working on deriving flattening lemmas for coequalizers and pushouts after this. Lot's of exciting stuff after that!
I took the time to explain some of the ideas that go into this proof as it can be quite instructive. Hopefully it reads OK and will be useful to future eyes. I wanted to emphasise how its quite an important consequence of univalence as it makes theory inside a higher topos happen.
@mikeshulman I've also added you as a reviewer so that you can give me feedback about the comments I've written. If you are too busy however that's no problem.

Flattening lemma for GraphQuotient

---

theories/Colimits/GraphQuotient.v

@jdchristensen This is a followup to #1851, it removes all the rewrites in the proof. The reason I used rewrite in the first place was because it was convenient and we seldom have to reason about the computation rules themselves (+ laziness).
I rewrote it using explicit path algebra so it can be reasoned about in the future if we ever have to. Another advantage is that Coq won't be slow when it tries to unfold these terms.

remove rewrite

---

theories/Colimits/GraphQuotient.v

We prove the standard functoriality results for GraphQuotient. These can be used later to help derive the flattening lemmas for Coeq and Pushout.

functoriality of GraphQuotient

---

theories/Basics/Notations.v
theories/WildCat.v
theories/WildCat/Displayed.v
theories/WildCat/DisplayedEquiv.v

Changes to WildCat/Displayed.v include:
- One fix -- `dcat_assoc_opp` and `dcat_assoc_opp_strong` both took the type family `D` as an unnecessary argument.
- Monomorphisms and epimorphisms.
- Changes to arguments. All functor methods now expect both the underlying functor and the displayed functor.
- An unrelated proof that was missing (`is1catstrong_sigma`).
The additions in WildCat/DisplayedEquiv.v closely follow [WildCat/Equiv.v](https://github.com/HoTT/Coq-HoTT/blob/3002e0d82dca445ef3072e12c11f8a36936aa3d8/theories/WildCat/Equiv.v) up through univalence.
There is still more work to do to make this useful (namely proving that univalence of the base category and univalence of the displayed category implies univalence of the total category). I'm happy to wait and PR all at once, but it …

Equivalences for displayed wild categories

---

flake.lock
flake.nix

This bumps the nix flake to use Coq 8.19.

nix: update flake

---

theories/Basics/Overture.v

This suppresses the `argument-scope-delimiter` warning which we cannot fix until Coq 8.19. A PR fixing it is ready in #1862. In the meantime we can safely ignore this warning.

surpress argument-scope-delimiter warning

---

theories/Colimits/GraphQuotient.v
theories/Colimits/Quotient.v
theories/Sets/Ordinals.v

GraphQuotient takes 3 universe levels. The first is the level of the type we are quotienting. The second is the level of the relation we are quotienting by. Finally, the third is the level the quotient type will live in.
Before we didn't enforce that the first and second universe levels are less than or equal to the third. We add those constraints in.
@jdchristensen This mostly compiles, getting stuck on Ordinals.v. I've tried to understand what is going on and I imagine it is because we are defining a small image which is no longer possible with the new universe restrictions on the quotient type. If this cannot be resolved, it will probably mean that we need to pull in the join construction, or do something clever with prop resizing which we do have.
Therefore I have marked it as draft …

add universe constraints in GraphQuotient

---

theories/Algebra/Groups/Group.v
theories/Basics/Equivalences.v
theories/Homotopy/HSpace/Coherent.v
theories/ObjectClassifier.v
theories/Pointed/pFiber.v
theories/Pointed/pSusp.v

The first commit changes `cbn` to `hnf` in the `make_equiv` tactic, so that the lazymatch can correctly detect path types.  If the path type was hidden in record or class, like `IsUnitPreserving`, then `make_equiv` would inadvertently destruct it with `elim`.  With the change, one proof in Group.v becomes much simpler.  `make_equiv` failed there before this change.
The second commit is independent and just gives some improvements coming from looking at places where `make_equiv` was used.  The `cbn` inserted in one spot speeds up the `make_equiv` there.

Improvements to make_equiv

---

theories/Spaces/Int/LoopExp.v
theories/Spaces/Int/Spec.v
theories/Spaces/Pos/Core.v
theories/Spaces/Pos/Spec.v

The first commit changes `pos_peano_ind` to `pos_peano_rec`, moves `pos_iter_op` to a more sensible spot in the file, and fills in `nat_of_pos`, which had a comment describing it, but no implementation.
The second commit makes everything in Spaces/Int/Spec.v transparent, and cleans up a couple of things.  (I needed one result transparent for WIP, so I just made them all transparent.)

Clean-ups to Spaces/Int/ and Spaces/Pos/

---

theories/Classes/theory/groups.v
theories/Pointed/Core.v

Two unrelated commits.
The first commit gets rid of a universe variable that is constrained to be equal to another one.  (I'm not sure why Coq doesn't automatically get rid of the redundant one.)
The second commit makes `group_cancelL` transparent, which is needed for WIP.  I didn't adjust the other results in this file.

Pointed/Core and Classes/theory/groups

---

theories/Classes/implementations/field_of_fractions.v
theories/Classes/implementations/natpair_integers.v
theories/Colimits/Quotient.v
theories/HIT/quotient.v

Just like for Colimits.GraphQuotient, enforce that the quotient in HIT.quotient lands in a universe at least as big as the universe the relation takes values in.

HIT/quotient: fix universe variables, and uses in Classes

---

theories/Colimits/Quotient.v
theories/HIT/V.v
theories/Sets/Ordinals.v

It turns out that the image factorization for a function `f` to an h-set was already done in `quotient_kernel_factor`, and was even done in a way that let `f x = f y` be replaced by an equivalent relation `R x y`.  Thus it was set-up to be used with propositional resizing, where `R` could be taken to have small values.  I cleaned it up and provided this small version (as well as a version where `R` is definitionally `f x = f y`), and adapted Ordinal.v to use this instead of reproving it.
I left the factorization result in its bundled style.  I don't love that, but it did make it easy to state variations quickly.

Generalize quotient_kernel_factor, and use it in Ordinals.v

---

theories/WildCat/Core.v

Tiny fix: `is0functor_compose` has an `Arguments ... : rename` command that previously made the wrong arguments implicit.
`Print is0functor_compose` before:
```coq
Arguments is0functor_compose {A B C}%type_scope
{isgraph_A isgraph_B isgraph_C} F%function_scope
{is0functor_F}%function_scope G {is0functor_G}
(where some original arguments have been renamed)
```
after:
```coq
Arguments is0functor_compose {A B C}%type_scope
{isgraph_A isgraph_B isgraph_C} F%function_scope 
{is0functor_F} G%function_scope {is0functor_G}
(where some original arguments have been renamed)
```

Fix: is0functor_compose arguments

---

theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/Groups/FreeProduct.v
theories/Colimits/Coeq.v
theories/Colimits/GraphQuotient.v
theories/Colimits/MappingCylinder.v
theories/Cubical/DPath.v
theories/Cubical/DPathSquare.v
theories/Cubical/PathCube.v
theories/Cubical/PathSquare.v
theories/Extensions.v
theories/Homotopy/CayleyDickson.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/HSpaceS1.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Smash.v
theories/Homotopy/Suspension.v
theories/Spaces/Circle.v
theories/Spaces/Torus/Torus.v
theories/Spaces/Torus/TorusEquivCircles.v

We redefine DPath as transport. This simplifies many things in the library. We go through and remove many superfluous lemmas and proof steps. I've also simplified various proofs as I've seen fit especially in Smash.v.

redefine DPath as transport and cleanup proofs

---

theories/Algebra/Groups/Group.v
theories/Algebra/Rings/CRing.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/TriJoin.v
theories/WildCat/Universe.v

This instance is far too general and should be restricted to Universe.v where it is actually used. A few places in the library were picking this up. This can be fixed by changeing a -> to a $-> so that the correct instance is inferred.

get rid of isgraph_arrow

---

theories/Pointed/Core.v
theories/WildCat/Equiv.v
theories/WildCat/Universe.v

It would be nice if we can work out a way to generalise paths of `CatEquiv`s with morphism extensionality, but I wasn't able to work one out.

refactor: hasmorext_core

---

theories/Homotopy/Wedge.v

When proving the eta law for wedge sums we did some lazy path algebra. This PR makes the path algebra explicit together with a few minor improvements in the file.

remove rewrites in path algebra for Wedge

---

contrib/HoTTBook.v
theories/Classes/implementations/binary_naturals.v
theories/Classes/implementations/ne_list.v
theories/Spaces/Finite/Fin.v
theories/Spaces/Nat.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/Nat/Core.v
theories/Spaces/Nat/Paths.v

It turns out to be very easy to prove that nat has decidable equality without using DProp.v, and that is done in this PR.  I moved the characterization of the path types as `DHProp`s to Nat/Paths.v, but I'm not sure if we should keep this.  It is a result from the HoTT book, which is mentioned in HoTTBook.v, so for now I have left it here.
This addresses the main point of #1882.
Nat/Core.v and Nat/Arithmetic.v use almost all of the files in Basics, as well as Types.Sigma for one use of `path_sigma_hprop`.  So this prevents us from moving the whole thing into Basics.  We could:
- Leave it all in Spaces/Nat/
- Move Nat/Core.v to Types/Nat.v, since it plays a similar role to other files there.  The other two files could move or stay.
- Move Nat/Core.v, except for the leq material that uses …

Nat: direct proof of Dec Paths; move equiv_path_nat to Nat/Paths.v

---

theories/Classes/implementations/list.v
theories/Spaces/List.v

We show that the pentagon identity holds for lists. I haven't shown the triangle identity, but presumably it is easier. This is in preparation for #1896.

pentagon identity for lists

---

theories/Pointed/Core.v
theories/WildCat/TwoOneCat.v
theories/WildCat/Universe.v

We were missing the bifunctor coherence for composition. This lets us prove the exchange law in a (2,1)-category.

add missing coherence for TwoOneCat

---

theories/Basics/PathGroupoids.v
theories/Homotopy/Smash.v

Here is a new attempt at the functoriality of smash. I've done it directly without using the swapping infrastructure in the Hurewicz formalization. It was quite straightforward and allowed me to define some useful lemmas about `ap011`. (Actually from what I could tell, this wasn't proven to the full extent in the Hurewicz formalization anyway).
I'll wait till after #1886 which will mean some proofs will need to be shifted around.

functoriality of smash

---

theories/Colimits/Coeq.v
theories/Colimits/CoeqUnivProp.v
theories/WildCat/Displayed.v
theories/WildCat/DisplayedEquiv.v

Addresses step (3) from #1259. A few notes:
- The graph structure that I put on things "worked", but is there a more correct alternative?
- The naming of the file is a bit awkward. Assuming that we want to add naturality of this universal property w.r.t. `functor_coeq` (step (4) from 1259), my thought was that the combination of the two would make Colimits/Coeq.v untenably long, so I decided to separate this.
- I'm still making sense of the comment [here](https://github.com/gio256/Coq-HoTT/blob/82aece3a1983231dea398550e09031ce3974ec57/theories/Homotopy/Suspension.v#L284), but it seems to imply that we might need a small disclaimer on this, at least until step (4) is added.

Zero-groupoid universal property for coequalizers

---

theories/WildCat/Paths.v

We show that types are themselves (2,1)-categories in the obvious way. This can be useful when building higher morphisms for various structures. It also serves as a guiding principle for what is missing in PathGroupoids. I've added some TODO's so we can eventually add such lemmas in.

(2,1)-cat structure for paths

---

theories/Algebra/AbGroups/AbHom.v
theories/Algebra/AbSES/Ext.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/WildCat/Bifunctor.v
theories/WildCat/Monoidal.v
theories/WildCat/Products.v

We refactor the definition of a monoidal 1-category to be more inline with the rest of the wildcat library. This should also make it easier to actually use in the library. A simple example would be binary products in a pointed category.

better definition of monoidal 1-category

---

theories/Pointed/pTrunc.v

Simple corollary that pointed truncations preserve pointed products.

pointed truncation preserves products

---

theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/EMSpace.v

This scope was introduced for the `B` notation, however it was later converted to an abbreviation IIRC making leaving it unused.

remove bg_scope

---

theories/WildCat/DisplayedEquiv.v
theories/WildCat/Equiv.v

We add the rest of the movement lemmas for equivalences; weaken some assumptions (more maps were assumed to be equivalences than were needed); and rename some arguments to make more sense.

more movement lemmas for WildCat/Equiv.v

---

theories/Algebra/Groups/Group.v

I've gone ahead and fixed the documentation in Group.v:
- The header styles have been fixed to be the correct ones.
- Spelling mistakes have been corrected, although I still may have missed or introduced a few.
- I've added some descriptions of the ideas that go into group theory, although nothing too deep just some introductory comments.
- I've reordered and tweaked a few things in the file.
I've been running a live server in vscode and viewing the html file built by dune in watch mode. This has been helpful in quickly updated the document and seeing how it looks.

cleanup and document Group.v

---

theories/Homotopy/Wedge.v

We show that pType has all coproducts.
- closes #1890

I-indexed coproducts in pType

---

theories/Spaces/List.v

We add <s>some more list functions and</s> a proof that `n.+2` truncated types give `n.+2` truncated lists.

truncation level of lists

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Rings/Module.v

In this PR we:
- Define left R-modules over a ring R.
- Define submodules and their module structure.
- Define left module homomorphisms.
- Define the category of left modules and homomorphsims.
- Define kernels and images of module homomorphisms.
- Define quotients of modules by submodules.
- Show the first isomorphism theorem for modules.
- Define the direct product of modules and show that the category of modules has products. (This could be generalised to a treatment of biproducts in categories).

left R-module basics

---

theories/Homotopy/Wedge.v
theories/Pointed/Core.v
theories/WildCat/Coproducts.v

This generalises the wedge inclusion to other categories. I don't see anyway of removing the decidable paths requirement. In general I would assume this is equivalent to AC.

coproduct-product inclusion map

---

theories/Colimits/Coeq.v

Something I noticed in Coeq is that the double recursor doesn't need to assume funext by doing the "swap trick". I also cleaned up the proof a little.
A similar thing could probably be done for Coeq_ind2 but I don't really want to touch that for the time being.

remove fuenxt from Coeq_rec2

---

theories/WildCat/Bifunctor.v

Here are the bifunctor improvements we introduced in #1915.

bifunctor improvements

---

theories/WildCat/Bifunctor.v
theories/WildCat/Coproducts.v
theories/WildCat/Monoidal.v
theories/WildCat/Products.v

@jdchristensen here is a definition of symmetric monoidal category together with a partially finished twist construction. By this I mean using a `swap` and `twist` map we get associativity, triangle and hexagon with appropriate assumptions. <s>Only the pentagon is left.</s> Pentagon is done.
Note that this cannot be applied to `JoinAssoc` as is as there is a difference between `fmap11` and `functor_join`. This might be a good reason to redefined bifunctor like I suggested in #1883. It's not too difficult to wrangle it to fit however.

Symmetric Monoidal Categories

---

test/WildCat/Opposite.v
theories/Algebra/AbSES/Core.v
theories/Algebra/Rings/Module.v
theories/Algebra/Universal/Homomorphism.v
theories/Homotopy/SuccessorStructure.v
theories/Pointed/Core.v
theories/WildCat/Core.v
theories/WildCat/Displayed.v
theories/WildCat/DisplayedEquiv.v
theories/WildCat/Equiv.v
theories/WildCat/Forall.v
theories/WildCat/FunctorCat.v
theories/WildCat/Induced.v
theories/WildCat/Opposite.v
theories/WildCat/Paths.v
theories/WildCat/Prod.v
theories/WildCat/Sum.v
theories/WildCat/Universe.v
theories/WildCat/ZeroGroupoid.v

I was curious how close `is1cat_op` is to being definitionally involutive, and it turns out that the only thing that fails is associativity, because it requires using `gpd_rev` on the hom types.
We could consider making a variant of `Is1Cat` without associativity and using that where possible, to avoid duplicating dual proofs.  But it would add one more layer in the WildCat hierarchy, so I don't think it's a great idea.
Instead, the second commit shows a trick that makes this work.  It changes `Is1Cat` to have *two* associativity proofs, one for each direction, with `is1cat_op'` just switching the two.  We could define `Build_Is1Cat` to only take one, and prove the other using `gpd_rev`, so almost no code would need to change.  (And we already define `cat_assoc_opp`, so this is really no …

Trick to make Is1Cat definitionally involutive

---

.gitignore
dune

We add some dune rules to benchmark the compilation of single .v files. It works by writing `(theories/file/to/bench.v)` in a file called `file_to_bench` and running `dune build @bench`. This uses a program called `hyperfine` which must be available for this to work. After the bench is run it outputs a bench report.
Typical output:
```
$ dune build @bench
Starting bench. This may take a while.
Bench finished, report at bench_report:
Benchmark 1: /nix/store/v97xkrdzqhwrz8305w05vfix32y5qifa-coq-8.19.1/bin/coqc -R ./theories HoTT -noinit -indices-matter benched_file.v
Time (mean ± σ):      6.421 s ±  0.024 s    [User: 6.202 s, System: 0.195 s]
Range (min … max):    6.364 s …  6.461 s    10 runs
```

single file benchmarks

---

theories/WildCat/Products.v

This switches `apply` to `nrapply` where applicable and a few miscellaneous inlines.
See #1937 for the script that times.
```                                                                                   
Time (mean ± σ):      6.421 s ±  0.024 s    [User: 6.202 s, System: 0.195 s]
Range (min … max):    6.364 s …  6.461 s    10 runs
```
```                                                                                                                                                                                                                                      
Time (mean ± σ):      2.588 s ±  0.028 s    [User: 2.402 s, System: 0.176 s]
Range (min … max):    2.559 s …  2.651 s    10 runs
```

optimize Products.v

---

contrib/dune
coq-hott.opam
dune
dune-project
test/dune
theories/dune

We have some better support for sharing flags in Dune 3.13 allowing us to reduce the size of the coq.theory stanzas.

bump to dune 3.13

---

test/WildCat/Opposite.v
theories/WildCat/DisplayedEquiv.v
theories/WildCat/Equiv.v
theories/WildCat/FunctorCat.v
theories/WildCat/NatTrans.v
theories/WildCat/Opposite.v
theories/WildCat/PointedCat.v

Fixes #1936 
Currently, Opposite.v requires several other files, such as Equiv.v, and includes results such as `hasequivs_op`.  The first commit reverses such dependencies, so, for example, `hasequivs_op` is now in Equiv.v, and Equiv.v requires Opposite.v.  The same happens for FunctorCat.v and NatTrans.v, so Opposite.v now only depends on Core.v.
This means that opposite categories can be used to remove duplicate code in Equiv.v.  There are many dual results, and the second commit just gives some examples of how we can use opposites to remove proof duplication.
A great side effect of this is that it solves the slowdown in #1936 with test/WildCat/Opposite.v, with the test now taking 0.25s.  However, using opposites to prove `compose_cate_assoc_opp` was important for this, and for some …

Use Opposite.v in Equiv.v to remove duplication

---

theories/WildCat/Products.v

By not going through the twist construction for the pentagon and hexagon in Products.v we can make the proof shorter. This is because we can efficiently compute the projections of an associator.
This was needed in #1929 so that we could more easily work with the associator.

shorter proofs of monoidal structure in Products.v

---

theories/WildCat/Monoidal.v

The curried naturality we ask for is compact, however it makes it difficult to use in practice. These lemmas show that it is a fair bit of work to actual get the more streamlined versions out.
Split from #1929

Monoidal: convenient naturality lemmas

---

theories/Homotopy/Wedge.v
theories/WildCat/Coproducts.v

As discussed in #1929, this is generally not an inclusion, take for example `Group`.

rename cat_coprod_prod_incl -> cat_coprod_prod

---

theories/Algebra/AbGroups/AbPushout.v
theories/Algebra/AbGroups/Biproduct.v
theories/Algebra/AbSES/Core.v

Here is some cleanup in AbGroups that was done in #1929. They consist of renaming lemmas and pushing funext requirements further up.

cleanup in AbGroups

---

theories/Types/Bool.v

This is more useful in proof when you want to apply it to a hypothesis and then destruct.

Bool: add convenient variant of negb_ne

---

theories/Algebra/AbGroups/AbHom.v
theories/Algebra/AbSES/BaerSum.v
theories/Algebra/AbSES/Ext.v
theories/Algebra/AbSES/SixTerm.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Homotopy/Smash.v
theories/WildCat/Bifunctor.v
theories/WildCat/Monoidal.v
theories/WildCat/Prod.v
theories/WildCat/Products.v
theories/WildCat/Yoneda.v

In this PR, we redefine `Is0Bifunctor` and `Is1Bifunctor` as discussed in #1933.
This has simplified things in lots of places however I got stuck with a universe issue in AbExt. @jdchristensen would you be able to take a look at that?
The reason I am doing this PR now is that I need some definitionally involutive opposite behaviour for bifunctors in #1929 and this isn't possible with the bifunctor coherence defintion.

redefine Bifunctor

---

theories/Algebra/Universal/TermAlgebra.v

Elimination is documented as nonrecursive although incorrectly behaves like Induction until coq/coq#19017

Use correct scheme kind for CarriersTermAlgebra_ind

---

theories/Algebra/Categorical/MonoidObject.v
theories/WildCat/Adjoint.v
theories/WildCat/Bifunctor.v
theories/WildCat/Equiv.v
theories/WildCat/Monoidal.v
theories/WildCat/NatTrans.v
theories/WildCat/Products.v

Here is a definition of monoid and comonoid object in a monoidal category.
They live in a new file called `Algebra/Categorical/MonoidObject.v`. This should be a place for "categorical algebra" that is theory about algebraic objects defined using category theory.
In order to define a comonoid as a monoid in the opposite monoidal category we need to be able to take take the opposite monoidal category. This requires restructuring how we define things in `Monoidal.v` using natural transformations and equivalences where we can. The work in #1952 helped some properties hold more easily. The result is that the monoidal structure is inherited in the opposite category in a fairly straightforward way, modulo moving some inverted morphisms around.
As an "application" we show that `x $-> y` is a …

monoids and comonoids in a monoidal category

---

test/WildCat/Opposite.v

We add more tests showing functors and now bifunctors are definitionally involutive. We also show that opposite natural transformations do not have this behaviour since the proof of naturality is inverted. I think it might be time to consider adding redundant information to `Is1Natural` so that we also keep the inverted naturality around like we did for `cat_assoc_opp`.

more opposite tests

---

theories/Basics/Notations.v
theories/Basics/Overture.v
theories/Classes/implementations/ne_list.v
theories/Spaces/List/Core.v
theories/Spaces/List/Theory.v
theories/Spaces/Option.v
theories/Types/Option.v

This PR develops the theory of lists some more. Here is a summary of the changes:
- We change the `[ a0; ...; an ]` notation to `[ a0, ..., an ]` in a way that doesn't disrupt the pointed type notation.
- We add a new `theories/Spaces/Option.v` file for some basics about option types.
- In `Option.v` I needed to use the `injection` tactic which lets Coq prove that constructors of inductive types are injective. In order to do that, I had to register some constants in `Overture.v`. It appears to be working fine. See the proof of `option_path`.
- The `head`, `nth` and `last` functions now return an `option A` rather than requiring a default value.
- We add new functions:
- `drop` which drops the first n elements of a list.
- `take` which takes the first n elements of a list and returns it.
- …

more theory about lists

---

contrib/HoTTBookExercises.v
theories/Limits/Pullback.v

I couldn't find this proof anywhere in the library, although this result maybe of interest somewhere else.

Prove that the universal property of pullback is an equivalence

---

theories/Basics/Decidable.v
theories/Spaces/Int.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/Nat/Core.v

We define the unary integers as discussed in #1913. We show that we have addition and multiplication and that these operations are associative.
This should be enough for the ring structure on `Int`. We can think about replacing `BinInt` after this PR.
The proofs here might need some cleanup, but they work.
The (initial) design is based on mathcomps integers but the proofs are only similar. These appear to be more pleasant to work with than the binary integers so far.
Edit: We now define the integer operations by integer induction, essentially 6.10.12 in the HoTT book.

Unary integers

---

theories/PropResizing/Nat.v
theories/Spaces/Finite/Finite.v

We had some `try` statements left over from a change in 8.11 about typeclass resolution and `refine`. Since we are well past that version we can remove these.
I also sped up the proof in Finite.v slightly.

chore: cleanup 8.11 compat

---

test/Algebra/Rings/Matrix.v
theories/Algebra/Rings/Matrix.v
theories/Algebra/Rings/Module.v
theories/Algebra/Rings/Vector.v
theories/Spaces/List/Theory.v

This PR is a draft until the following dependencies are merged:
- #1956 
- #1957 
- #1959 
In this PR we define matrices together with:
- The abelian group structure of matrices over a ring (could be an abelian group but no need for now).
- The ring structure of matrices given by matrix multiplication
- Transposed matrices and some basic properties
- Matrix minors and some basic properties
- Trace of a matrix and some basic properties
There is also a test file demonstrating how matrices can be built and used in practice. We also test some examples there too.
I have some more work on the determinant, however this requires some more work on finite types such as sums over an arbitrary finite type and permutations. We can define the determinant using the rule with minors however it is not …

Matrix Rings

---

contrib/SetoidRewrite.v
theories/Homotopy/Bouquet.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pSusp.v
theories/WildCat/Adjoint.v
theories/WildCat/Bifunctor.v
theories/WildCat/FunctorCat.v
theories/WildCat/Monoidal.v
theories/WildCat/NatTrans.v
theories/WildCat/Paths.v
theories/WildCat/Products.v
theories/WildCat/Universe.v
theories/WildCat/Yoneda.v

We cleanup NatTrans.v by doing the following:
- Transformations, natuarlity lemmas, and natural transformations each appear separately in their own sections making it easier to see what lemmas are available for each.
- There are now more comments explaining what is happening.
- Is1Natural is no longer a definitional typeclass in preperation for adding the transposed naturality condition to the data of a natural transformation.
- Whitespace style has been homogenized.

cleanup NatTrans.v

---

test/WildCat/Opposite.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pSusp.v
theories/WildCat/Adjoint.v
theories/WildCat/Bifunctor.v
theories/WildCat/Monoidal.v
theories/WildCat/NatTrans.v
theories/WildCat/Paths.v
theories/WildCat/Products.v
theories/WildCat/Universe.v
theories/WildCat/Yoneda.v

Carry out the suggestion in #1961. This will allow for more of the data of a monoidal category or (2,1)-category to be definitionally involutive.

make opposite Is1Natural definitionally involutive

---

theories/Basics/Notations.v
theories/Basics/Utf8.v
theories/Modalities/Fracture.v

Newer versions of Coq warn when a postfix or a closed notation doesn't have level 1 or 0 respectively. We fix all such occurences here. We also remove a few redundant reservations.

fix notation warnings in 8.20

---

theories/Algebra/Rings/Matrix.v

We prove that:
- matrix transposes preserve negation
- matrix transposes preserve zero
- matrix transposes preserve the identity matrix

more lemmas about matrix transpose

---

theories/Algebra/Rings/Matrix.v

We show that scalar multiplication distributes over the first factor of matrix multiplication. We also clarify that something similar should hold for right multiplication and the right factor.
We also clarify an earlier comment about an R-algebra over a noncommutative ring R. It's not a priori clear what the definition should be in this case. R-matrices form an R-bimodule with a product that interacts with the left and right actions nicely. This might be a good candidate for a definition, but it is not clear if it is standard.
When the ring R is commutative then it is clear that this becomes the usual definition of an associative algebra. Equivalently, a map `R -> Z(A)` where A is the algebra and Z is the center.

interaction of scalar and matrix multiplication

---

theories/Algebra/Rings/Matrix.v
theories/Algebra/Rings/Vector.v

This was creating too many universe variables before. We also make sure that `Matrix` only takes the universe of the type of elements.

fix universes in Vector.v

---

theories/Algebra/Rings/Matrix.v
theories/Algebra/Rings/Vector.v

We write down the property of being a diagonal matrix, show that this is a hprop (how nice), and show that standard opertions on matrices preserve diagonal matrices. This lets us define the subring of diagonal matrices of the ring of matrices.
Depends on:
- #1971
- #1978

theory of diagonal matrices

---

theories/Algebra/Rings/Matrix.v

We prove that:
- The trace of a matrix sum is the sum of traces.
- The trace preserves scalar multiplication (it is a linear map)
- In a commutative ring, a cyclic permutation of a product of matrices has invariant trace.

more theory about matrix traces

---

.github/workflows/ci.yml
coq-hott.opam
dune-project
flake.lock
flake.nix
theories/Colimits/Quotient.v
theories/Spaces/No/Core.v

We bump our minimal Coq version to 8.19.
This version appears to have some better universe inference and will be useful for #1984.
I did a compatibility cleanup in `No/Core.v`.
I noticed that there is an 8.19 compatibility comment in Quotient.v but I couldn't work out what exactly could change. @jdchristensen would you mind taking a look at that file and dropping the 8.18 compat? (Alternatively, we can do that in a later PR it doesn't seem too pressing).
The draft PR #1862 can be undrafted after this.

bump min version to 8.19

---

theories/Algebra/Universal/Algebra.v
theories/Algebra/Universal/Homomorphism.v
theories/Basics/Equivalences.v
theories/Basics/Nat.v
theories/Basics/Overture.v
theories/Basics/Settings.v
theories/Categories/Adjoint/Hom.v
theories/Categories/Adjoint/UnitCounit.v
theories/Categories/Category/Core.v
theories/Categories/Functor/Core.v
theories/Categories/NaturalTransformation/Core.v
theories/Categories/Pseudofunctor/Core.v
theories/Categories/PseudonaturalTransformation/Core.v
theories/Extensions.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/TriJoin.v
theories/Homotopy/Suspension.v
theories/Limits/Pullback.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Spaces/BinInt/Core.v
theories/Types/Forall.v
theories/Types/Universe.v
theories/WildCat/Core.v
theories/WildCat/Equiv.v

This draft PR is for when we bump the minimal version of Coq to 8.19. It fixes a warning where `%` was changed to `%_` and hence `%` in `Arguments` is now deprecated. In the mean time, I will just disable this warning in the CI.
For the record (because I totally forgot this earlier):
- `%` means open scope deeply in the argument (in 8.20).
- `%_` means open scope shallowly in the argument (previous behaviour of `%`).

[8.19] fix % in Arguments warnings

---

test/Spaces/List.v
theories/Spaces/List/Core.v
theories/Spaces/List/Theory.v

We explicitly annotate all the lemmas in the list library in order to make sure there is no universe blow up. The universe blow up stems from poor implementation of various tactics with respect to universe polymorphism.
I will get onto cleaning up universes in the linear algebra library too, but that is also affected by a more critical universe blow up which will have to be considered separately.

fix universes in list library

---

theories/PropResizing/Nat.v
theories/Types/Sigma.v

This was quite difficult to fix, but I worked it out in the end.
The previous proof was using the generated polymorphic induction principle which is actually less general than what we could be. This meant that we required an extra strictly larger universe for the induction hypothesis to work.
Rewriting the proof using a fixpoint allows us to use the most general version of the "induction principle", i.e. the rules of the underlying fixpoint. This allows us to remain in the same universe, simplifying the universe requirements elsewhere too.
The main motivation for this patch was to reduce the universes in `istrunc_vector` and now we don't need a superfluous larger universe.
cc @mikeshulman who participated in the corresponding Zulip discussion: …

drop extra universe in istrunc_sigma

---

theories/Algebra/Rings/Vector.v

With a little bit of help, we can get Coq to minimize the number of universes it uses for Vector.v.

fix universes in vector

---

theories/Algebra/Rings/KroneckerDelta.v
theories/Algebra/Rings/Ring.v

This is just a start at removing some universe variables in Rings/*. 
@Alizter , please feel free to contribute to this PR, as I may not have time to investigate further.  Or we can merge this and look at other things later.

Rings: remove some universe variables

---

theories/WildCat/Paths.v

This allows wildcat structures to be augmented with paths in the higher cells.
cc @ThomatoTomato

More flexible WildCat.Paths instances

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Cyclic.v
theories/Algebra/AbGroups/Z.v
theories/Algebra/AbSES/SixTerm.v
theories/Algebra/Groups/Group.v
theories/Spaces/Int.v

We generalise group powers to integers. The nat based powers become a special case.
@ThomatoTomato I've left two parts incomplete if you would like to finish them. Make sure to remove any axioms or `Admitted`s. You may push directly to this branch. If pushing doesn't work, then you can just create a new PR.

integer group powers

---

theories/Algebra/Rings/Matrix.v
theories/Colimits/CoeqUnivProp.v
theories/Homotopy/Suspension.v
theories/WildCat/Paths.v

We don't want `isgraph_paths`, `is2graph_paths`, or `is3graph_paths` to be global instances, as then Coq could apply them in situations where we prefer a different wild category structure.  But the further instances that require having these ones already applied can safely be global instances, so that's what this PR does. 
This allows us to simplify things in the three files that currently use WildCat.Paths:  Suspension.v, CoeqUnivProp.v and Matrix.v.
I have checked that the build time is unchanged within the noise.

Make some WildCat.Path instances Global, and use them

---

flake.lock
flake.nix

I missed an extra argument here before which meant that the development shell didn't build. I've fixed this and updated the flake.

fix nix flake

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Rings/Matrix.v

In this PR, we reduce the number of universe variables appearing in Matrix.v. I'm not particularly sure why Coq cannot minimize these cases itself, but adding a few annotations helps it come to the correct number of variables.
The number of universes in matrix_ring went from 4 to 1. This will help with the slow down in #1981.

fix universes in Matrix.v

---

theories/Algebra/Categorical/MonoidObject.v

Here we prove that comonoid objects in an opposite category are monoid objects in the original category.
This is for #1929.

comonoid objects in opposite category are monoids

---

theories/WildCat/Bifunctor.v

These are used in #1929. It would be good to understand why we cannot infer the second instance.

composed bifunctor instances

---

test/Algebra/Rings/Matrix.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Cyclic.v
theories/Algebra/AbGroups/Z.v
theories/Algebra/AbSES/SixTerm.v
theories/Algebra/Groups/Group.v
theories/Algebra/Rings/Z.v
theories/HIT/FreeIntQuotient.v
theories/Homotopy/PinSn.v
theories/Spaces/Circle.v
theories/Spaces/Int.v
theories/Spaces/Torus/TorusHomotopy.v

This was a bit more work than I anticipated but I seem to have something workable. It could use some more cleanup as I think some of these proofs could be slicker.
In this PR we port the remaining uses of BinInt to Int and introduce `int_iter` with standard exponentiation results on equivalences and loops.
Feel free to push any commits.
@ThomatoTomato this should help you with #1992.

switch to Int in cring_Z

---

theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/AbGroups/FreeAbelianGroup.v

In this PR we:
- Characterise the universal property of the free abelian group on a type S.
- Show that an abelianization of a free group produces a free abelian group.
- As a special case, construct the free abelian group on a type S as the abelianization of the free group on the set.
This construction will be important in the theory of modules as we will be taking quotients of free abelian groups to produce constructions such as tensor products of abelian groups.
I had a bit of trouble managing funext. I tried to see if it was possible to stay funext free but I didn't see a way.
Classically, the free abelian group is defined as a fucntion from the generating set into Z together with a finite support. This definition is very appealing for us but would also require a lot of funext in …

free abelian groups

---

theories/Algebra/Rings/Module.v
theories/Basics/Notations.v

In this PR we introduce notations `r *L m` for `lact r m` and `m *R r` for `ract m r`. If we don't like them, then we can drop this PR.

notations for left and right module actions

---

theories/Algebra/AbGroups/AbHom.v

In this PR we define the coequalizer of two group homomorphisms in the category of abelian groups. This is defined as the cokernel of the difference of the homomorphisms.

abgroup coequalizers

---

theories/Homotopy/PinSn.v
theories/Homotopy/SuccessorStructure.v

SuccessorStructure.v was still using `BinInt` we switch it over to `Int`.

move SuccessorStructure.v over to using Int

---

theories/Basics.v
theories/Basics/Classes.v
theories/Classes/interfaces/abstract_algebra.v
theories/Classes/theory/rings.v
theories/Classes/theory/ua_first_isomorphism.v
theories/HIT/iso.v
theories/HSet.v
theories/Spaces/Finite/Finite.v
theories/Spaces/Nat/Core.v

In this patch we create a new file Basics/Classes.v which contain some basic classes. In the future we will move some more stuff from canonical_names.v and abstract_algebra.v here that should be more widely available.
For now we introduce the IsInjective predicate more generally for everybody to use and adapt existing proofs to use this.

consolidate injectivity predicate

---

theories/Algebra/Groups/FreeGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Groups/Subgroup.v
theories/Algebra/Rings/Ring.v

This PR removes `IsUnitPreserving` from `GroupHomomorphism` as it can always be inferred. And in practice, that is how we built group homomoprhisms anyway.

remove IsUnitPreserving from GroupHomomorphism

---

test/Algebra/Groups/Presentation.v

Previously these were harder to read. They are still not so easy, but at least a bit clearer.
```coq
Check ⟨ x | x * x * x , -x ⟩.
Build_Finite_GroupPresentation 1 2
(fscons
((fun x : FreeGroup (Fin 1) => x * x * x : FreeGroup (Fin 1))
((freegroup_in o fin_nat) 0%nat))
(fscons
((fun x : FreeGroup (Fin 1) => - x : FreeGroup (Fin 1)) ((freegroup_in o fin_nat) 0%nat))
fsnil))
: GroupPresentation
```
```coq
Check ⟨ x , y | x * y ,  x * y * x , x * (-y) * x * x * x⟩.
Build_Finite_GroupPresentation 2 3
(fscons
((fun x y : FreeGroup (Fin 2) => x * y : FreeGroup (Fin 2))
((freegroup_in o fin_nat) 0%nat) ((freegroup_in o fin_nat) 1%nat))
(fscons
((fun x y : FreeGroup (Fin 2) => x * y * x : FreeGroup (Fin 2))
((freegroup_in o fin_nat) 0%nat) ((freegroup_in o fin_nat) 1%nat))
(fscons
((fun x y : …
```

better looking terms in presentation test

---

.github/workflows/ci.yml

The ubuntu package `python` was obsolete and has now been removed. We switch to the recommended `python3` instead.

ci: python -> python3

---

contrib/HoTTBookExercises.v
theories/Basics/Notations.v
theories/Categories/Category/Prod.v
theories/Categories/Category/Sigma/Univalent.v
theories/Categories/Category/Sum.v
theories/Categories/ExponentialLaws/Tactics.v
theories/Categories/Functor/Sum.v
theories/Categories/NatCategory.v
theories/Spaces/BAut/Cantor.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/No/Addition.v
theories/Tactics.v

We fix the order in which we bind `type_scope` to `Sortclass` allowing targets of function types to automatically be interpreted as types. This allows us to remove `%type` annotations throughout the library.
One obvious benefit from this is that when working with `nat` or mathclasses, Coq will no longer find it ambiguous to have `A -> B + C` as a type.

Fix binding of type_scope to Sortclass

---

theories/Colimits/Sequential.v

The proofs of the lemmas didn't matter, just the direction.  Reversing the direction got rid of some lines dealing with `ap_V`.

Use lemmas from Nat.Core in Colimits/Sequential instead of custom ones

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Rings/KroneckerDelta.v
theories/Algebra/Rings/Matrix.v
theories/Spaces/Finite/FinInduction.v
theories/Spaces/Finite/FinNat.v
theories/Spaces/Finite/FinSeq.v
theories/Spaces/List/Theory.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/Nat/Core.v

We continue the cleanup of `Nat/` started in #2028. This PR focuses on the comparison operators for `nat`. There is still more cleanup that needs to be done, but this gets a good deal out of the way.
This PR consists of moving results from arithmetic, renaming things properly and proving missing results.
There is more to come after this.

Cleanup of Nat.v part 2

---

theories/Spaces/Nat/Core.v

The proof I pushed in #2042 was incorrect. I also merged a bit fast. This fixes the proof in the final commit. I will merge this quickly so that master builds.

Fix: proof of equiv_leq_lt_or_eq

---

theories/Spaces/Nat/Core.v

We add left and right distributivity of multiplication over subtraction.

Nat: distributivity of multiplication over subtraction

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Spaces/Int.v

This allows for nat lemmas to be used in place of integer ones under the right conditions.

Int: conversion lemmas with nat

---

theories/Algebra/Groups/QuotientGroup.v

This doesn't affect the definitions themselves:  since the context variables were not used, they were not made into arguments of the various things defined in the section.

QuotientGroup: remove unused context variables and add comments

---

theories/Spaces/Nat/Division.v

In this PR we show a prime divisor is necessarily a divisor of one of the factors. This is otherwise known as Euclid's lemma.

Primes: division lemma for primes

---

theories/Basics.v
theories/Basics/Decidable.v
theories/Basics/Equivalences.v
theories/Basics/Iff.v
theories/Basics/Overture.v
theories/Basics/Trunc.v
theories/Categories/Structure/IdentityPrinciple.v
theories/PropResizing/Nat.v
theories/Spaces/Finite/Fin.v
theories/Spaces/Int.v
theories/Spaces/List/Core.v
theories/Spaces/List/Theory.v
theories/Spaces/Nat/Core.v
theories/Spaces/Nat/Division.v
theories/Types/Arrow.v
theories/Types/Forall.v
theories/Types/Prod.v
theories/Types/Sum.v
theories/Utf8Minimal.v
theories/WildCat/EquivGpd.v

In this PR we prove the first part of the fundamental theorem of arithmetic outlined in #2059. We show that any natural number has a factorisation into primes.
In order to do this we define `IsComposite` which checks if a natural number has a proper divisor. Now this allows us to partition `nat` into 4 parts, zero, one (unit), primes and composites.
I noticed that in the classical setting, the line between being not prime and composite is blurred due to classical logic. This means texts on elementary number theory rarely distinguish between these two concepts. In the constructive setting, it can be shown that they are equivalent since we can apply classical reasoning to IsComposite and IsPrime precisely because they are decidable.
This allows us to show that any natural has a prime …

prime factorization

---

theories/Spaces/Nat/Division.v

In this PR we add a lemma showing that multiplication is monotone with respect to divisibility as an order.
We also give two lemmas allow us to cancel common factors in quotients, given suitable conditions.

add quotient cancelling and nat_mul divisibility monotonicty

---

.github/workflows/ci.yml

The update in #2076 was incomplete. This fixes it and should make the main `master` CI upload the documentation correctly. We cannot see that in the PR.

ci: fix upload of documentation

---

theories/Algebra/AbGroups/Abelianization.v
theories/Algebra/AbGroups/FreeAbelianGroup.v
theories/Algebra/AbGroups/TensorProduct.v

We show that the tensor product of free abelian groups is the free abelian group on the cartesian product of the generating sets.
The proof could be prettier. It was quite difficult to get right due to the subtle distinction between `Hom (A:=Group)` and `Hom (A:=AbGroup)`.

free abelian groups take products to tensor products

---

theories/Spaces/Nat/Division.v

I'm not sure if the side condition can be improved.

prove nat_div_div_r

---

theories/Spaces/Nat/Factorial.v

This is left over from some work on #2070, as it didn't end up being needed there.

Factorial: except for 0! = 1!, factorial is strictly monotone

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/Groups/Group.v
theories/Algebra/Rings/Z.v
theories/Spaces/Int.v

Fixes https://github.com/HoTT/Coq-HoTT/issues/2015

Work on issue #2015: grp_pow and related things

---

theories/Algebra/AbGroups/Biproduct.v
theories/Algebra/AbGroups/TensorProduct.v
theories/Algebra/AbSES/Core.v
theories/Algebra/AbSES/PullbackFiberSequence.v
theories/Algebra/Groups/Group.v

We show that tensor products distribute over sums.

tensor product distributes over direct sum

---

theories/Algebra/AbGroups/Biproduct.v
theories/Algebra/AbSES/Core.v
theories/Algebra/Groups/Group.v

Since we generalized ab_biprod_corec to grp_prod_corec, we should also generalize ab_biprod_corec_eta to grp_prod.  In the process, I renamed it from _eta to _natural.  It's a definitional equality that isn't used anywhere, but is probably worth keeping as a form of documentation.
I had to switch grp_prod_corec to use wildcat notation, and I switched a couple of nearby things as well.

Replace ab_biprod_corec_eta with grp_prod_corec_natural

---

theories/Spaces/Nat/Core.v

If there are any more places this can be used, feel free to push here.

add lemma turning 0 < n -> n.+1

---

flake.lock
flake.nix

We update the nix flake to use Coq 8.20 and add a 8.19 shell for when we need to use that.
This also has the added bonus of using coq-lsp 0.2.0 which has jump-to-definition support across files!

update nix flake to 8.20

---

STYLE.md

Typos I noticed today, plus a couple of obsolete things.
I pretty sure that the whole last part of the bug minimizer discussion is not needed anymore, since it was about using hoqc, which we no longer use.  @JasonGross , let me know if I'm right about that.  (The third commit below.)

More STYLE.md updates

---

theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/Z.v
theories/Algebra/AbSES/Core.v
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Rings/CRing.v
theories/Algebra/Rings/Localization.v
theories/Algebra/Rings/QuotientRing.v
theories/Algebra/Rings/Ring.v
theories/Algebra/Rings/Z.v
theories/Colimits/Quotient.v
theories/Modalities/Descent.v
theories/Modalities/Lex.v
theories/Modalities/Nullification.v

In this PR we introduce localizations of commutative rings. This is based on a formalization of the Zariski topology I started back in 2020, but I think the localization is of independent interest.
FTR there is no good generalization of localization for noncommutative rings so I've stuck to commutative rings.
We begin by defining the notion of a multiplicative subset of a ring and give a few examples. We then define the underlying type of a ring localized with respect to a multiplicative subset as a quotient type of fractions. This generalises the field of fractions construction.
The rest of the work consists of showing that we have a commutative ring structure and that we have the expected recursion principle.
Along the way, we introduce various ring lemmas of general use.

localizations of commutative rings

---

theories/Basics/Notations.v
theories/Basics/Utf8.v
theories/Spaces/BinInt/Core.v
theories/WildCat/Monoidal.v

I've updated my local Coq version to 8.20 and have finally been able to address the outstanding warnings.
Many warnings were about various notations having the wrong levels. If two notations exist and one can be factored into the other, then they have to be in the same level. Otherwise, Coq just doesn't parse things correctly.
An example of this happening in practice was the infix `^` notation which was being used for powers by `BinInt`. Having this notation around broke `^` as a postfix path inversion operator. The solution was to remove this notation, which wasn't being used anyway.
The notation `{{ _ | _ // _ }}` used for the surreal numbers was causing quite a few problems due to how `//` was being factored. I didn't really know the best way to fix this, so I opted to just add another …

fix notations for 8.20

---

contrib/SetoidRewrite.v

We can't fix this warning until we bump the minimal version to 8.21 so for now the best we can do is silence it.

silence "From Coq" warning

---

.github/workflows/ci.yml

This was giving a warning in the CI since v1 is not compatible with upload-artifact@v4. We fix this by bumping the version to v5.

bump delete-artifact

---

STYLE.md
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Rings/Localization.v
theories/Algebra/Rings/QuotientRing.v
theories/Basics/Overture.v
theories/Basics/Tactics.v
theories/Colimits/Quotient.v
theories/Diagrams/CommutativeSquares.v

Added a remark to STYLE.md.
Moved path_via tactic from Overture to Basics/Tactics, and made other minor fixes.
Removed reflexivity hypothesis from Quotient_rec2, and instead assume exactly what we need.
I also moved Quotient_rec2 earlier in the file, so it's best to view these one commit at a time to see the actual change there.

Misc cleanups to Overture, Colimits/Quotient

---

theories/Basics/Overture.v
theories/Basics/PathGroupoids.v
theories/Basics/Trunc.v
theories/Types/Arrow.v
theories/Types/Sigma.v
theories/Types/Universe.v

This PR cleans up a few files in Basics/ and Types/ that I happened to be looking through.  Many of the changes are simply indentation or other whitespace changes.  Some others move things to a more logical spot.  And a couple actually change things.  I made sure to separate out the non-trivial changes into their own commits, to make it easy to review this.
(There's of course a lot more that could be done, but I'm going over these files with students tomorrow, so I'm just fixing things as I notice them.)

Basics and Types cleanup

---

theories/Metatheory/ImpredicativeTruncation.v
theories/Metatheory/IntervalImpliesFunext.v
theories/Metatheory/TruncImpliesFunext.v

I noticed that this file generated lots of universe variables, and could be made a lot more clear now that Coq supports specifying the constraints between universe variables.  Because of this, some of the examples weren't really needed anymore, so I trimmed it to make the main point more clear.  I also updated the style of comments and other formatting issue.

ImpredicativeTruncation: redo using universe annotations

---

theories/Algebra/Rings/Idempotent.v

Addresses first part of #2009. I can't recall any other identities to do with idempotent ring elements.

Idempotent ring elements

---

theories/Basics/Trunc.v

Added this cute little lemma about truncations that might come in handy. All it says is that a map (A -> istrunc n.+1 A) is sufficient to deduce that A is n+1 truncated.
I wasn't so sure what to name it, so feel free to make it fit into your mold.

istrunc_self_implies_istrunc

---

theories/WildCat/Coproducts.v

The cocartesian monoidal structure for any wild category with coproducts had the same priority with the cartesian monoidal structure for any wild category with products. This meant that in practice, inferring a monoidal structure on say `Type` chose the cocartesian monoidal structure. This is due to the second instance appearing at the same priority but later.
This PR demotes the priority of the cocartesian monoidal structure so that the cartesian monoidal structure is generally preferred. The cocartesian monoidal structure is not used nearly as much in practice anyway.

demote priority of cocartesian monoidal structure

---

theories/Algebra/Rings/CRing.v
theories/Algebra/Rings/Matrix.v
theories/Algebra/Rings/QuotientRing.v
theories/Algebra/Rings/Ring.v

We modify `Build_Ring'` to closer match how it is actually used in practice and remove some repeated workaround in proofs.

Better ring constructors

---

theories/WildCat/Universe.v

The previous version only had instances for `Type0` but now `Empty` and `Unit` are the initial and terminal objects respectively of `Type@{i}` for all universes `i`.

more polymorphic terminal unit and initial empty

---

contrib/SetoidRewrite.v
theories/Algebra/Universal/Algebra.v
theories/Algebra/Universal/Operation.v
theories/Basics/Tactics.v
theories/Classes/theory/dec_fields.v
theories/Classes/theory/ua_first_isomorphism.v
theories/Classes/theory/ua_homomorphism.v
theories/HIT/unique_choice.v
theories/Sets/AC.v
theories/Sets/GCH.v
theories/Sets/GCHtoAC.v
theories/Sets/Hartogs.v
theories/Sets/Ordinals.v
theories/Spaces/Card.v
theories/Spaces/FreeInt.v
theories/Spaces/Nat/Arithmetic.v
theories/Spaces/Nat/Core.v

These tactics have been around and pretty much do the same thing. We therefore define them in terms of the more commonly used variant. We could consider removing them completely, but the diff will be a bit larger.

cleanup: make into aliases: easy -> done, now -> by

---

theories/Algebra/Categorical/MonoidObject.v
theories/WildCat/Monoidal.v

We introduce the notion of a `lax` monoidal functor. This notion of "morphism of monoidal categories" has the nice property of preserving monoid objects in monoidal categories.
The "lax" part is due to requiring a "reverse morphism" `F a ⊗ F b $-> F (a ⊗ b)`. This is probably contrary to the perhaps more natural reverse direction that you might come up with. The important thing here is that monoids are preserved. In most cases, we actually have what is known as a "strong monoidal functor" where this morphism is an isomorphism. The unit preservation also is "lax" and therefore looks backwards.
This sets us up for some future work on showing that `FreeAbGroup`, and perhaps a future `FreeLeftModule`, are monoidal functors from `Type` to `AbGroup` or `LeftModule R`. This lets us define monoid …

lax monoidal functors

---

theories/Equiv/BiInv.v
theories/Types/Equiv.v
theories/Types/Sigma.v

Mainly changes Types/Equiv.v:
- Removed rewrites from one proof.
- Moved most things that don't depend on Funext out of the Funext section.  I think the new order also makes the structure more clear.
- Fix formatting of some comments and indentation.
In Equiv/BiInv.v, I just reduced the imports.

Equivalence cleanups

---

theories/Constant.v
theories/Universes/BAut.v

First commit:
Add variants of `cconst_wconst_hset` and `merely_rec_hset` that don't require `Funext`.
Also clean up some proofs, e.g. the proof of `equiv_merely_rec_hset_if_domain`.  Also factor out `hprop_image_wconst_hset_if_merely_domain`.
Second commit:
Minor fixes, e.g. drop unneeded backticks, fix indentation, and consistently name the `WeaklyConstant` argument `wc`.

Constant.v: variants without Funext; cleanups

---

theories/HFiber.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Truncations/Core.v

The third commit proves that `paths : X -> (X -> Type)` is an embedding.  For this we needed that `functor_forall_id` sends families of O-modal maps to an O-modal map, which is in commit 1.  And that `equiv_fun` is an embedding, which is in commit 2.

Prove Yoneda-like result for paths, and required lemmas

---

theories/Algebra/Rings/Matrix.v

This makes the library build when https://github.com/coq/coq/pull/19611 is applied to Coq, and can replace #2127.
(It also builds with 8.19 and other versions.  And I added universe annotations to make sure the problem doesn't crop up again.)

Matrix: use strip_reflections to avoid extra universe variables

---

flake.lock
flake.nix

Update the nix flake to a newer version of `nixpkgs` giving us `coq-lsp` `0.2.2`. Also fix the dev shell and format the flake.

chore: update nix flake

---

theories/Algebra/AbGroups/TensorProduct.v
theories/WildCat.v
theories/WildCat/Monoidal.v
theories/WildCat/MonoidalTwistConstruction.v
theories/WildCat/Products.v

In this PR we isolate the "twist construction" in Monoidal.v and put it in its own file. This is in preparation for alternative ways of constructing symmetric monoidal categories. While we are at it, we remove various `Local` modifiers, since they end up making some proofs more verbose.

move twist construction into its own file

---

theories/Spaces/Nat/Division.v

We show that for k < n, k mod n = k.
I didn't end up needing it in the end, but it is something good to know.

generalise nat_mod_one_l to nat_mod_lt

---

theories/Basics/Overture.v

The existing comment had a few problems:  it was out of date (mentioning a field of a class); it mixed up the tracking class `Funext` and the axiom `isequiv_apD10`; and it contained technical things that don't belong in Overture.v.  I rewrote the text from scratch.

Overture: replace comment about Funext class

---

theories/Types/Paths.v

We add some expected variants of `transport_paths_FlFr`. There are a few places these could be used, but I haven't looked for them yet. I'm doing some cleanup elsewhere, where they will come in handy.

Add variants of transport_paths_FlFr

---

theories/Homotopy/Join/Core.v

Here is a double recursion principle for `Join`. It is slightly more general than a typical double recursion principle since we allow for the types in each join to be different. This generalisation makes the overall lemma clearer to state and prove.
One place this will be used is in CayleyDickson.v where we define a H-space multiplication operation on `Join (Susp A) (Susp A)` for a Cayley-Dickson imaginaroid `A`. This lemma makes the construction there much clearer.
Presumably there ought to be a dependent variant of this, but I haven't yet thought about how to state or prove it.

double recursion for join

---

theories/Homotopy/CayleyDickson.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Suspension.v

We fix the issue in #2149 which didn't affect much of the later proofs in the file. I don't know why this doesn't affect anything later on. It seems like the H-space construction would have gone through still?
We take this opportunity to clean up the argument in this file. For instance, we have a derived negation and conjugation on the suspension, with further properties given properties of the underlying negation. This all works without needing to assume a Cayley-Dickson imaginaroid structure.
We clean up the argument in `cd_op` making it easier to read, prove and use. We could add beta rules for `Join_rec2` in the future, to make computations easier. We currently don't need to do this yet.

cleanup in CayleyDickson and fix #2149

---

theories/Basics/Equivalences.v
theories/Basics/PathGroupoids.v
theories/Colimits/Coeq.v
theories/Colimits/GraphQuotient.v
theories/Colimits/Pushout.v
theories/Homotopy/Hopf.v
theories/Types/Sigma.v

Now that we have identity systems, #2143, we can use these to characterize path spaces of certain HITs. In this PR we characterize path spaces of graph quotients, coequalizers and pushouts, using the induction principle given by [Kraus and von Raumer](https://arxiv.org/pdf/1901.06022). These results will be helpful towards characterizing the colimits in Wärn's zigzag-construction.
We first introduce transportDD. This is a doubly dependent transport over doubly dependent type families, defined in PathGroupods.v. In Equivalences.v, we prove that both transportD and transportDD are equivalences. In Sigma.v, we show that transportDD is a curried version of transport over a sigma type.
Next up we prove induction and recursion principles for descent data over graphs, parallel pairs, and spans. …

Path spaces of graph quotients, coequalizers, and pushouts

---

theories/Algebra/Groups/FreeProduct.v

We do some minor cleanup in `FreeProduct` and add some useful induction principles.

better induction principles for FreeProduct + cleanup

---

theories/Colimits/Coeq.v
theories/Colimits/Colimit.v
theories/Diagrams/ConstantDiagram.v
theories/Diagrams/Diagram.v

In this PR we add more results pertaining to `functor_colimit`. The library currently supports two approaches to use colimits. One either considers *concrete colimits* that are the HITs defined from the data of the diagrams, or *abstract colimits* that are arbitrary types with the correct universal property. As per the implementation of today, a concrete colimit is an abstract colimit once function extensionality is assumed. 
This PR adds a sort of third approach, where we allow ourselves to use both concrete and abstract colimits at the same time. The map `functor_colimit` has a diagram map `m : D1 => D2` as input, and outputs a map `Colimit D1 -> Colimit D2`. We add `functor_Colimit_half` that acts like the above function, but you can choose an arbitrary cocone `Q` over the target …

Functoriality results for Colimits

---

theories/Basics/Decidable.v
theories/Metatheory/TruncImpliesFunext.v
theories/Modalities/Notnot.v
theories/Universes/HProp.v

I noticed that one can strengthen
```coq
IsHProp(forall x y, Decidable (x = y))
```
to
```coq
forall x, IsHProp(forall y, Decidable (x = y))
```
using a cute argument involving restricting to a component.  Not sure if this is useful, but since it's slightly non-trivial, I'm pushing it.
The weaker result is `ishprop_decpaths` in Basics/Decidable.v, but because of dependencies, the new result can't go there.  I originally used `merely A` in the proof, but realized that it can be avoided by using `not (not A)` in this case, which reduces the dependencies.  I put this in `HProp.v`, since that file had similar dependencies and already had one result involving decidable types and being an h-proposition.
I also added in the fact that for decidable `A`, `~~A` has the universal property of …

forall y, Decidable (x = y) is an hprop

---

theories/Algebra/Groups/Subgroup.v

This lets us coerce groups to their subgroups. The coercion is always printed as to not introduce sneaky terms.

make maximal_subgroup a printed coercion

---

theories/Algebra/Groups/Group.v

This lemmas have been extremely useful when simplifying group terms. It may be worth investigating if `grp_auto` can work with them in the future.
There are other places we could probably be using these, but I haven't looked in detail yet.

add more usable group cancellation lemmas

---

theories/Algebra/Groups/Kernel.v
theories/Algebra/Groups/ShortExactSequence.v
theories/Algebra/Groups/Subgroup.v
theories/Algebra/Rings/Ideal.v

These were awkward to write down when they had implicit arguments. There is no good reason to keep them implicit any longer.

remove implicit arguments in trivial_subgroup and maximal_subgroup

---

theories/Algebra/AbGroups/AbelianGroup.v

This makes working with equivalences of abelian groups easier when working with groups since you can do `emap abgroup_group`. Even though they are the same thing under the hood, the terms get difficult to work with without explicit casting.

abgroup_group is a functor

---

theories/Algebra/Groups/Subgroup.v

Some improvements to the normal subgroup lemmas we had.
Relies on:
- #2176

improve normal subgroup lemmas

---

theories/Colimits/Pushout.v

I've proven these lemmas many times before, but never managed to push them. Here is a fresh attempt.

add functoriality lemmas for pushout

---

theories/Algebra/Groups/Group.v

Here are the basics on conjugation in groups.

conjugation of group elements

---

theories/Algebra/AbGroups/Centralizer.v
theories/Algebra/Groups/Group.v

This idiom was used a few times and I have further use for it elsewhere.

group unit lemmas

---

theories/Algebra/Groups/Subgroup.v

First, we rename `IsTrivialSubgroup` to `IsTrivialGroup`. `maximal_subgroup` is now a coercion, which means we can write `IsTrivialGroup G` for a subgroup `G`, therefore dropping the `sub` seemed appropriate.
Next we simplify the definition by only requiring a map into the trivial group, which corresponds to a subgroup inclusion. The reverse inclusion is trivial, and is stated for completeness. It didn't need to be part of the data.
Finally we show that a group is trivial iff it is isomorphic to the trivial group. Seems negligible on paper, but some details need to be provided.

improvements to trivial group

---

theories/Algebra/Groups/FreeGroup.v

I forgot to PR this before #2172.
We state some useful results that come up often when working with maps out of free groups.

some helpful lemmas for FreeGroup

---

theories/Algebra/Groups/Subgroup.v

This isn't true definitionally due to the way we define subgroups. This lemma at least lets us pass along the obvious equivalence when it appears in arguments.
Relies on (because of Require)
- #2186

group of maximal subgroup of a group is iso to said group

---

theories/Algebra/Rings/Vector.v
theories/Spaces/List/Theory.v
theories/Spaces/Nat/Core.v

Added various small results and improvements that will be used in future PRs.
**Nat.Core:**
- Properties of `nat_max` and `nat_min`.
**List.Theory:**
-  Results for `take` (two takes are the same as a take with the minimum, commutativity, invariance of `take n` with respect to concatenation if n is less than or equal to the length of the first list).
- Adapted the `Build_Vector` constructor to get a `Build_list`  constructor for a list given a function from `nat`, changed the results for Vectors so that they are based on this.
- Simplification of definitions by @jdchristensen

Defining properties of maxima and minima, lemmas for the take operation in lists, lists from sequences.

---

theories/Algebra/Groups/Commutator.v

In this PR we define the commutator of group elements `[x, y] := x * y * x^ * y^` and state and prove the basic identities about them.
We also prove the Hall-Witt identity and its variant. This is a Jacobi-like identity for commutators of groups.
Next we show that precomposing the predicate of a normal subgroup with a commutator is itself a subgroup. I couldn't find the name of this idea.
We define the commutator subgroup of two subgroups of a group, and then study the commutator of a group with itself which we call the derived subgroup. We show that it is normal and furthermore the quotient is commutative. We then state and prove that it is an abelianization and therefore automatically isomrophic to our abelianization.
Finally we prove the "three subgroups lemma" which will allow us to …

Commutators, commutator subgroups and three subgroups lemma

---

theories/Algebra/Groups/Subgroup.v

Similarly to `IsTrivialGroup` we define what it means for a subgroup to be maximal (with respect to the tautological predicate). This means that the predicate of the subgroup always has a section.
We also add a comment mentioning that being isomorphic to the maximal subgroup is not enough to be maximal. Take `2Z` and `Z` in `Z`.

maximal subgroups

---

theories/Algebra/Groups/Subgroup.v

- `subgroup_group` is a (displayed) functor.
- All trivial subgroups (of different groups) are isomorphic.

`subgroup_group` iso lemmas and all trivial subgroups are iso

---

theories/Basics/PathGroupoids.v
theories/BoundedSearch.v
theories/Types/Equiv.v
theories/Universes/HProp.v

The commits are independent and self-explanatory.

Misc cleanups to PathGroupoids, Equiv, HProp and BoundedSearch

---

theories/BoundedSearch.v
theories/Spaces/List/Theory.v
theories/Spaces/Nat/Core.v

I noticed that there are two ways to prove that it's decidable whether a bounded natural satisfies a decidable predicate.  One is already in List/Theory, which I extended with `decidable_exists_bounded_nat`.  But BoundedSearch essentially proves this as well, as I illustrate with `decidable_search`.
On the one hand, it's nice that BoundedSearch avoids needing to use lists.  On the other hand, BoundedSearch requires `merely`, which currently requires Modalities (although I suspect this dependency can easily be removed with some reorganization).
Maybe it's worth having both?  If so, I'll add comments pointing each one to the other.  Or, we could just keep one.
Incidentally, the one in List/Theory is hard to find.  Since the statement of the lemma doesn't involve lists, it's not an obvious …

Variants of decidable_exists_nat

---

theories/Algebra/Groups.v
theories/Algebra/Groups/Finite.v
theories/Algebra/Groups/Lagrange.v
theories/Algebra/Groups/QuotientGroup.v
theories/Algebra/Groups/Subgroup.v
theories/Spaces/Nat/Division.v

We cleanup `Lagrange.v` by giving the theorem a proper name and making the corollary use division. We didn't have a good theory of division and divisibility of nats at the time of writing, but now we do.
I also improve the comments a bit.

cleanups and improvements to lagrange

---

theories/Algebra/Groups/Subgroup.v

Being a trivial group is invariant under group isomoprhism of the groups of the subgroups.

being trivial is invariant under iso

---

theories/Misc/UStructures.v
theories/Spaces/List/Theory.v
theories/Spaces/NatSeq/Core.v
theories/Spaces/NatSeq/UStructure.v

Work on types of sequences `[nat -> X]`, will be used for formalising searchable types. Some definitions are stated in the generality of `nat`-graded equivalence relations, which we call `UStructures` here. This could be further generalised to directed systems or uniform spaces in the topological sense later.

Sequences, uniform structures

---

theories/HoTT.v

I noticed a few missing Exports in HoTT.v.  I didn't systematically check for others.

HoTT.v: add (some) missing Exports

---

test/bugs/github754.v
theories/Basics/Notations.v
theories/Categories.v
theories/Categories/Adjoint/UniversalMorphisms/Core.v
theories/Categories/Category.v
theories/Categories/Category/Pi.v
theories/Categories/Category/Utf8.v
theories/Categories/Comma.v
theories/Categories/Comma/Core.v
theories/Categories/Comma/Dual.v
theories/Categories/Comma/Functorial.v
theories/Categories/Comma/InducedFunctors.v
theories/Categories/Comma/Notations.v
theories/Categories/Comma/Projection.v
theories/Categories/Comma/ProjectionFunctors.v
theories/Categories/Comma/Utf8.v
theories/Categories/Functor/Prod/Core.v
theories/Categories/LaxComma.v
theories/Categories/LaxComma/Core.v
theories/Categories/LaxComma/Notations.v
theories/Categories/LaxComma/Utf8.v
theories/Categories/Limits/Core.v
theories/Categories/Notations.v
theories/Categories/UniversalProperties.v
theories/Categories/Utf8.v

This should fix some of the recent warnings we have been seeing.
If I've understood correctly, there should be no change in semantics.

fix: change Warnings Append -> Warnings

---

theories/WildCat/Core.v

@patrick-nicodemus Can you check whether this gets rids of the loop in typeclass search that you mentioned?

WildCat/Core: reduce is1cat_is1cat_strong to a hint to avoid loops

---

etc/generate_coqproject.sh

When a merge is in progress, `git ls-files ...` can list the same file more than once.  This means we end up with a makefile that causes a lot of warning messages, even if you just do `make clean`.  So we use `sort -u` to remove the duplicates.

generate_coqproject: remove duplicates from list of .v files

---

theories/Algebra/Rings.v

I noticed that a few Export lines were missing from the meta-file.

Rings.v: add missing Exports

---

theories/Colimits/CoeqUnivProp.v
theories/Diagrams/ConstantDiagram.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinAssoc.v
theories/Homotopy/Join/TriJoin.v
theories/WildCat.v
theories/WildCat/Category.v
theories/WildCat/FunctorCat.v
theories/WildCat/Graph.v
theories/WildCat/Products.v
theories/WildCat/Yoneda.v
theories/WildCat/ZeroGroupoid.v

Introduces a bundled type of Graphs and a bundled type of Categories. 
Proves that Graph is a (0,1)-category and a 2-graph.
Proves that Category is a (0,1)-category and a 3-graph with "wild modifications" as 3-cells.

Bundled categories

---

theories/Homotopy/EMSpace.v

These were accidentally switched to local instances in #2244.
@patrick-nicodemus Any chance you can create a file that imports HoTT.v and then prints the typeclass database, and then use this to compare the sorted outputs before and after #2244 and #2239?  Ideally, the change in #2247 to Rings.v would be in place during both checks, for the most coverage.

EMSpace: add #[export] to the instances

---

test/Tactics/transport_paths.v
theories/Types/Paths.v

In this PR, we reorganise our `transport_paths` lemmas, grouping them by number of functions and putting them in order of left to right. We also test the associated tactics expected usage making sure things are working as expected. We also add some missing lemmas and fix some mistakes observed during testing.
There is a unification problem in one of the tactics that I wasn't able to understand, so I will mark this as draft for now.

reorganise transport_paths lemmas and add tests

---

test/Tactics/napply.v

We mark these warnings as fatal so that they can trigger the `Fail` command more reliably and not litter the CI with warnings.

chore: fix warnings in test/

---

theories/Homotopy/ClassifyingSpace.v

We remove some rewrites and fix some comments.

Cleanup in ClassifyingSpace.v

---

theories/Algebra/Groups/FreeProduct.v
theories/Algebra/Groups/GroupCoeq.v

Elimination principles for GroupCoeq

---

theories/Basics/PathGroupoids.v
theories/Homotopy/Join/Core.v
theories/Homotopy/Join/JoinSusp.v
theories/Homotopy/Smash.v
theories/Homotopy/Suspension.v
theories/Homotopy/Wedge.v
theories/Pointed/pSusp.v
theories/Spaces/Spheres.v

Some miscellaneous things that are useful in some out-of-tree work, and which also simplify some of the technical proofs in the library.  I could have limited the changes to the long proofs to be just a line or two, but while I was looking at them, I simplified them a bit and removed some rewrites.  A couple of slow `Defined` or `Qed` lines became slightly slower, but the difference was fairly small, so I think it's worth it to have proofs without rewrites.
The commits can be read independently or together.

Add things related to suspensions and joins

---

theories/Algebra/AbGroups/AbHom.v
theories/Algebra/AbGroups/AbelianGroup.v
theories/Algebra/AbGroups/TensorProduct.v
theories/Algebra/AbSES/BaerSum.v
theories/Algebra/AbSES/Ext.v
theories/Algebra/Categorical/MonoidObject.v
theories/Algebra/Universal/Homomorphism.v
theories/WildCat/Coproducts.v
theories/WildCat/Core.v
theories/WildCat/DisplayedEquiv.v
theories/WildCat/Equiv.v
theories/WildCat/FunctorCat.v
theories/WildCat/Monoidal.v
theories/WildCat/Paths.v
theories/WildCat/TwoOneCat.v

This collects a few changes from the `Hint Mode` rewrite which I deemed sufficiently unobtrusive that I think they are worth submitting again in a separate PR.
Each of these changes is motivated by identifying breakages in the code due to the `Hint Mode +` changes in the WildCat library, I have previously argued that this elaboration behavior is not robust, so my motivation for this PR is that I think these fix potential future bugs due to refactoring (e.g., the current PR I have outstanding to refactor (2,1)-cats so that they depend on the definition of a bicategory)
Some of the changes are clear improvements to the existing code as well and are unlikely to be controversial.
I believe the only change in this PR which could affect downstream users is that I defined one or two new …

Clean annotations

---

theories/Algebra/AbSES/Core.v
theories/Algebra/Groups/Group.v
theories/Algebra/ooGroup.v
theories/Homotopy/ClassifyingSpace.v
theories/Homotopy/Cover.v
theories/Homotopy/EvaluationFibration.v
theories/Homotopy/ExactSequence.v
theories/Homotopy/HSpace/Core.v
theories/Homotopy/HomotopyGroup.v
theories/Homotopy/Smash.v
theories/Homotopy/Wedge.v
theories/Pointed/Core.v
theories/Pointed/Loops.v
theories/Pointed/pEquiv.v
theories/Pointed/pFiber.v
theories/Pointed/pMap.v
theories/Pointed/pModality.v
theories/Pointed/pSusp.v
theories/Pointed/pTrunc.v
theories/Spectra/Spectrum.v

The bidirectionality hint for `Build_pMap` and `Build_pEquiv'` is changed from `& _ _ _ _` to `_ _ & _ _`.  Both work, but the new way expresses the intention more clearly.  The same hint is added to `Build_pEquiv`.
The comments near two of these are updated to be more accurate.  (The third is in the same file as one of the others, so I didn't add a comment there.)
Because these hints work so well, almost every use in the library doesn't need arguments one and two, so they have been made implicit.  (In the case of `Build_pEquiv'`, they had already been declared implicit, but the `Arguments` command accidentally undid this.)

Make A and B implicit arguments in Build_{pMap,pEquiv,pEquiv'}; add/adjust bidirectionality hint &

---

theories/Algebra/AbSES/Core.v
theories/Algebra/Groups/Group.v
theories/Algebra/Rings/Ring.v
theories/Pointed/Core.v
theories/WildCat/Core.v
theories/WildCat/DisplayedEquiv.v
theories/WildCat/Equiv.v
theories/WildCat/Induced.v
theories/WildCat/Opposite.v
theories/WildCat/Universe.v

This commit "unboxes" `HasMorExt` and `IsUnivalent1Cat`, removing the constructor term necessary to build an instance of these, which will make terms slightly smaller. I guess the performance gains are slightly offset because the definition still has to be unfolded.
Of course the proofs are shorter by one line because one no longer has to apply the constructor.
What do you think, is this a good idea?
@Alizter suggested I use "Typeclasses Opaque" after this, but the documentation says:
> Definitional typeclasses are not wrapped inside records, and the trivial projection of an instance of such a typeclass is convertible to the instance itself. This can be useful to make instances of existing objects easily and to reduce proof size by not inserting useless trivial projections. **The …

unboxed HasMorExt and IsUnivalent1Cat

---

theories/Basics/Equivalences.v
theories/Categories/Category/Sigma/Univalent.v
theories/Classes/categories/ua_category.v
theories/Classes/theory/ua_homomorphism.v
theories/Colimits/Sequential.v
theories/Diagrams/Cocone.v
theories/Diagrams/Cone.v
theories/Diagrams/Diagram.v
theories/HFiber.v
theories/Modalities/Lex.v
theories/Modalities/Meet.v
theories/Modalities/Open.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Spectra/Spectrum.v
theories/Types/Paths.v
theories/Types/Sigma.v
theories/WildCat/Equiv.v

`isequiv_compose` had `f` and `g` as implicit arguments, just because of the way it was defined with implicit generalization of arguments.  That meant that it was often used in an unwieldy `@isequiv_compose` form with lots of underscores.  This PR makes `f` and `g` into explicit arguments, which makes many places cleaner, although it means that `apply` has to change to `rapply` in a few other places.

Make f and g explicit arguments to isequiv_compose

---

theories/Basics/PathGroupoids.v
theories/Diagrams/CommutativeSquares.v
theories/Diagrams/Diagram.v
theories/HIT/V.v
theories/Homotopy/Suspension.v
theories/Truncations/Connectedness.v
theories/Types/Paths.v

I noticed that a lot of proofs in Paths.v were essentially reproving isequiv_concat_lr using isequiv_compose.  This PR directly uses isequiv_concat_lr for those results.  While doing this, I thought it would be cleaner to explicitly define concat_l, concat_r and concat_lr (corresponding to equiv_concat_l, equiv_concat_r and equiv_concat_lr).  We already had a notation concatR, but in all of the places it was used, rhs_V worked better.  So the first commit removes concatR, and the next two commits add the new definitions and then use them.
The fourth commit is independent, but similar in spirit.
The library builds after each commit.

Add and use concat_l, concat_r and concat_lr

---

theories/Algebra/Groups/FreeProduct.v
theories/Misc/BarInduction.v
theories/Truncations/Core.v

The makes some changes that were originally in https://github.com/jdchristensen/HoTT/pull/39 but didn't make it into #2274.
The main thing is that `decidable_trunc_decidable` is added (as an instance), which abstracts out something done in BarInduction.v.  One other result is generalized, and a few proofs are simplified.
Since some things get moved around, it's best to read this one commit at a time.  The commits that move things don't make any changes.
@thchatzidiamantis Can you look this over as well?

Improvements to Truncations/Core

---

theories/Basics/Tactics.v
theories/Pointed/pSusp.v
theories/WildCat/Core.v

I created `lhs'`, `rhs'`, `lhs_V'` and `rhs_V'` which are like the unprimed versions, but work for any transitive relation.  (Symmetry is also needed in two cases.)  The main use case is for reasoning in a wild category or with homotopies of (pointed) functions, as demonstrated in the second and third commits.
Since `paths' is a transitive and symmetric relation, these also work for paths.  If the existing tactics are replaced with these, then almost all of the library builds fine, with just a few lines failing.  I tried very hard to tweak these so that they could completely replace the existing tactics, but I couldn't find a way to make them as robust, so I decided to create these primed versions.
The core issue is that we start with `@transitivity A R _`, which is different from …

Generalize lhs and rhs tactics to other relations

---

theories/Homotopy/BlakersMassey.v
theories/Homotopy/Cofiber.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Truncations/Connectedness.v

The main goal here is in the last commit, which adds a result saying that if `f : X -> Y` is a map with 1-connected domain whose cofibre is n.+1 connected, then f is n-connected.  To make this go through smoothly, I tweaked many things in the library.  The two biggest changes are in BlakersMassey:
- In the results about pushouts, instead of assuming that both maps are surjective, I only assume that `g` is.  I needed this to handle the inductive step uniformly.
- Unfortunately, the way it worked out for cofibres, I needed the opposite case, where only `f` is assumed to be surjective.  I could have reversed the pushout that defines the cofibre to make this work out, but it does seem slightly more natural in the current form, so instead I also added the result about the flipped pushout, …

Cofiber: add isconnmap_isconnected_cofiber, converse of isconnected_cofiber

---

theories/Basics/Equivalences.v
theories/Modalities/ReflectiveSubuniverse.v
theories/Spaces/Finite/Finite.v
theories/Truncations/Connectedness.v
theories/Universes/BAut.v
theories/WildCat/Opposite.v

Each commit is independent, and the library builds after each commit.
The fifth commit, changing Connectedness.v, is the only one with any substance.  I noticed that `is0connected_merely_allpaths` can be generalized to any truncation level.  I also added an `isconnmap` version of this and also of the converse statement.
The first commit moves a result that was in a strange place, interrupting the flow of other related results.
The others are pretty self-explanatory; see the commit messages.

Miscellaneous improvements

---

theories/Categories/Category/Objects.v

This PR adds helper functions and theorems for working with initial and terminal objects, as suggested by @jdchristensen in #2288.
Changes:
- Add `map_from_initial` and `map_to_terminal` for canonical morphisms
- Add `initial_morphism_unique` and `terminal_morphism_unique` theorems  
- Make `unique` tactic global by removing `Local` modifier
These helpers provide cleaner access to the unique morphisms from/to initial/terminal objects, which will be useful for the stable categories formalization and other category theory developments.

Add canonical morphism helpers to Objects.v

---

theories/Categories/Category/Objects.v

I should have noticed when reviewing #2291 that the `unique` tactic is essentially reproving `path_contr` each time.
@CharlesCNorton I think you'll find `path_contr` useful in other places.  Can you give this PR a quick review?

Category/Objects: use path_contr

---

.github/workflows/ci.yml

Fixed repeated typos:
“enviornment” → “environment”
“stategy” → “strategy”
“varible” → “variable”
“globablly” → “globally”

Various typo fixes in ci.yml

---

.github/workflows/ci.yml

This is an attempt to fix the doc-dep-graphs build, which is failing with:
```
+ (script @ line 12) $ cabal update
Config file path source is default config file.
Config file /home/coq/.cabal/config not found.
Writing default configuration to /home/coq/.cabal/config
<repo>/root.json does not have enough signatures signed with the appropriate keys
```

Add "ghcup install cabal" to work around error

---

theories/Categories/Additive/Biproducts.v

Extracting Biproducts.v from stable categories formalization (#2288).
**Status: WIP - not ready for merge**
Changes from original formalization:
- Fixed imports (removed non-existent ZeroMorphismLemmas.v)
- Made `ZeroObject` implicit throughout using `` `{Z : ZeroObject C} ``
- Updated `zero_morphism` calls to use implicit Z parameter
- Removed unused definitions (bi_inl, bi_inr, bi_outl, bi_outr, biproduct)
- Removed unused lemma (biproduct_prod_unique)
- Applied HoTT style conventions
The file provides:
- `BiproductData`: injection/projection morphisms
- `IsBiproduct`: axioms (beta_l, beta_r, mixed_l, mixed_r)
- `HasBiproductUniversal`: universal properties as product and coproduct
- `Biproduct`: complete structure combining the above
- Operations: biproduct_coprod_mor, …

[WIP] Add biproduct infrastructure for additive categories

---

theories/Misc/CompactTypes.v
theories/Types/Sigma.v
theories/Universes/TruncType.v

We add definitions and basic facts about compact and searchable types, including some examples and characterisations. We prove that the type `nat->X` is uniformly searchable if `X` is searchable. Useful lemmas about propositions and Σ-types are added to `TruncType` and `Sigma` respectively.

Add results on compact and searchable types (mostly following Escardo), lemmas for HProps
